[workspace]
resolver = "3"
members = [
    "crates/aaf",
    "crates/opentime",
    "crates/otio-aaf",
    "crates/otio-adapter",
    "crates/otio-ale",
    "crates/otio-capi",
    "crates/otio-cmx3600",
    "crates/otio-core",
    "crates/otio-fcp7",
    "crates/otio-fcpx",
    "crates/otio-python",
    "crates/otio-wasm",
    "crates/otio-xml",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "Apache-2.0"
repository = "https://github.com/jhodges10/otio-rust"
authors = ["Contributors to the otio-rust project"]

[workspace.dependencies]
opentime = { version = "0.1.0", path = "crates/opentime" }
otio-adapter = { version = "0.1.0", path = "crates/otio-adapter" }
otio-core = { version = "0.1.0", path = "crates/otio-core" }
otio-xml = { version = "0.1.0", path = "crates/otio-xml" }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
