// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

package otio

/*
#include <otio.h>
#include <stdlib.h>
*/
import "C"

import (
	"strconv"
)

// A DropFrame is whether a timecode is written in drop-frame form.
//
// C: OtioDropFrame
type DropFrame int32

const (
	// DropFrameInferFromRate means use drop-frame form if the rate is a
	// drop-frame rate.
	DropFrameInferFromRate DropFrame = 0
	// DropFrameForceNo means never use drop-frame form.
	DropFrameForceNo DropFrame = 1
	// DropFrameForceYes means use drop-frame form, failing if the rate has none.
	DropFrameForceYes DropFrame = 2
)

// String gives the name the C interface spells this by.
func (v DropFrame) String() string {
	switch v {
	case DropFrameInferFromRate:
		return "OTIO_DROP_FRAME_INFER_FROM_RATE"
	case DropFrameForceNo:
		return "OTIO_DROP_FRAME_FORCE_NO"
	case DropFrameForceYes:
		return "OTIO_DROP_FRAME_FORCE_YES"
	}
	return "DropFrame(" + strconv.Itoa(int(v)) + ")"
}

// A EDLStyle is which system's conventions an EDL is written for.
//
// C: OtioEdlStyle
type EDLStyle int32

const (
	// EDLStyleAvid means avid Media Composer.
	EDLStyleAvid EDLStyle = 0
	// EDLStyleNucoda means nucoda.
	EDLStyleNucoda EDLStyle = 1
	// EDLStylePremiere means adobe Premiere Pro.
	EDLStylePremiere EDLStyle = 2
)

// String gives the name the C interface spells this by.
func (v EDLStyle) String() string {
	switch v {
	case EDLStyleAvid:
		return "OTIO_EDL_STYLE_AVID"
	case EDLStyleNucoda:
		return "OTIO_EDL_STYLE_NUCODA"
	case EDLStylePremiere:
		return "OTIO_EDL_STYLE_PREMIERE"
	}
	return "EDLStyle(" + strconv.Itoa(int(v)) + ")"
}

// A Format is a file format this library reads and writes.
//
// C: OtioFormat
type Format int32

const (
	// FormatOTIOJSON means openTimelineIO's own JSON, the .otio file.
	FormatOTIOJSON Format = 0
	// FormatALE means avid Log Exchange, the .ale file.
	FormatALE Format = 1
	// FormatCMX3600 means cMX 3600 EDL, the .edl file.
	FormatCMX3600 Format = 2
	// FormatFcp7XML means final Cut Pro 7 XML, the .xml file.
	FormatFcp7XML Format = 3
	// FormatFcpxXML means final Cut Pro X XML, the .fcpxml file.
	FormatFcpxXML Format = 4
)

// String gives the name the C interface spells this by.
func (v Format) String() string {
	switch v {
	case FormatOTIOJSON:
		return "OTIO_FORMAT_OTIO_JSON"
	case FormatALE:
		return "OTIO_FORMAT_ALE"
	case FormatCMX3600:
		return "OTIO_FORMAT_CMX_3600"
	case FormatFcp7XML:
		return "OTIO_FORMAT_FCP7_XML"
	case FormatFcpxXML:
		return "OTIO_FORMAT_FCPX_XML"
	}
	return "Format(" + strconv.Itoa(int(v)) + ")"
}

// A MissingFramePolicy is what to show for a frame an image sequence is
// missing.
//
// C: OtioMissingFramePolicy
type MissingFramePolicy int32

const (
	// MissingFramePolicyError means treat the gap as an error.
	MissingFramePolicyError MissingFramePolicy = 0
	// MissingFramePolicyBlack means show black.
	MissingFramePolicyBlack MissingFramePolicy = 1
	// MissingFramePolicyHold means hold the previous frame.
	MissingFramePolicyHold MissingFramePolicy = 2
)

// String gives the name the C interface spells this by.
func (v MissingFramePolicy) String() string {
	switch v {
	case MissingFramePolicyError:
		return "OTIO_MISSING_FRAME_ERROR"
	case MissingFramePolicyBlack:
		return "OTIO_MISSING_FRAME_BLACK"
	case MissingFramePolicyHold:
		return "OTIO_MISSING_FRAME_HOLD"
	}
	return "MissingFramePolicy(" + strconv.Itoa(int(v)) + ")"
}

// A NeighborGapPolicy is what to do about a transition at the very start or
// end of a track when asking for its neighbours.
//
// C: OtioNeighborGapPolicy
type NeighborGapPolicy int32

const (
	// NeighborGapPolicyNever means report no neighbour, which is the literal
	// truth.
	NeighborGapPolicyNever NeighborGapPolicy = 0
	// NeighborGapPolicyAroundTransitions means report a gap the length of the
	// transition's overhang.
	NeighborGapPolicyAroundTransitions NeighborGapPolicy = 1
)

// String gives the name the C interface spells this by.
func (v NeighborGapPolicy) String() string {
	switch v {
	case NeighborGapPolicyNever:
		return "OTIO_NEIGHBOR_GAP_NEVER"
	case NeighborGapPolicyAroundTransitions:
		return "OTIO_NEIGHBOR_GAP_AROUND_TRANSITIONS"
	}
	return "NeighborGapPolicy(" + strconv.Itoa(int(v)) + ")"
}

// A NodeKind is what kind of object a handle names.
//
// These follow the schemas of upstream OpenTimelineIO 0.19.0. An object
// whose schema this library does not know reads as NodeKindUnknownSchema and
// keeps its fields verbatim.
//
// C: OtioNodeKind
type NodeKind int32

const (
	// NodeKindItem means a bare Item.
	NodeKindItem NodeKind = 0
	// NodeKindClip means a Clip.
	NodeKindClip NodeKind = 1
	// NodeKindGap means a Gap.
	NodeKindGap NodeKind = 2
	// NodeKindTrack means a Track.
	NodeKindTrack NodeKind = 3
	// NodeKindStack means a Stack.
	NodeKindStack NodeKind = 4
	// NodeKindTimeline means a Timeline.
	NodeKindTimeline NodeKind = 5
	// NodeKindTransition means a Transition.
	NodeKindTransition NodeKind = 6
	// NodeKindMarker means a Marker.
	NodeKindMarker NodeKind = 7
	// NodeKindEffect means an Effect.
	NodeKindEffect NodeKind = 8
	// NodeKindTimeEffect means a TimeEffect.
	NodeKindTimeEffect NodeKind = 9
	// NodeKindLinearTimeWarp means a LinearTimeWarp.
	NodeKindLinearTimeWarp NodeKind = 10
	// NodeKindFreezeFrame means a FreezeFrame.
	NodeKindFreezeFrame NodeKind = 11
	// NodeKindExternalReference means an ExternalReference.
	NodeKindExternalReference NodeKind = 12
	// NodeKindMissingReference means a MissingReference.
	NodeKindMissingReference NodeKind = 13
	// NodeKindGeneratorReference means a GeneratorReference.
	NodeKindGeneratorReference NodeKind = 14
	// NodeKindImageSequenceReference means an ImageSequenceReference.
	NodeKindImageSequenceReference NodeKind = 15
	// NodeKindSerializableCollection means a SerializableCollection.
	NodeKindSerializableCollection NodeKind = 16
	// NodeKindSerializableObject means a SerializableObject.
	NodeKindSerializableObject NodeKind = 17
	// NodeKindSerializableObjectWithMetadata means a
	// SerializableObjectWithMetadata.
	NodeKindSerializableObjectWithMetadata NodeKind = 18
	// NodeKindComposable means a Composable.
	NodeKindComposable NodeKind = 19
	// NodeKindComposition means a bare Composition.
	NodeKindComposition NodeKind = 20
	// NodeKindMediaReference means a bare MediaReference.
	NodeKindMediaReference NodeKind = 21
	// NodeKindUnknownSchema means an object whose schema this library does not
	// know.
	NodeKindUnknownSchema NodeKind = 22
	// NodeKindOther means a schema added to the core since this ABI was written.
	//
	// Nothing produces this today. It exists so that a core that grows a new
	// object reports something honest to a caller built against this header
	// rather than a kind that means something else.
	NodeKindOther NodeKind = 23
)

// String gives the name the C interface spells this by.
func (v NodeKind) String() string {
	switch v {
	case NodeKindItem:
		return "OTIO_NODE_KIND_ITEM"
	case NodeKindClip:
		return "OTIO_NODE_KIND_CLIP"
	case NodeKindGap:
		return "OTIO_NODE_KIND_GAP"
	case NodeKindTrack:
		return "OTIO_NODE_KIND_TRACK"
	case NodeKindStack:
		return "OTIO_NODE_KIND_STACK"
	case NodeKindTimeline:
		return "OTIO_NODE_KIND_TIMELINE"
	case NodeKindTransition:
		return "OTIO_NODE_KIND_TRANSITION"
	case NodeKindMarker:
		return "OTIO_NODE_KIND_MARKER"
	case NodeKindEffect:
		return "OTIO_NODE_KIND_EFFECT"
	case NodeKindTimeEffect:
		return "OTIO_NODE_KIND_TIME_EFFECT"
	case NodeKindLinearTimeWarp:
		return "OTIO_NODE_KIND_LINEAR_TIME_WARP"
	case NodeKindFreezeFrame:
		return "OTIO_NODE_KIND_FREEZE_FRAME"
	case NodeKindExternalReference:
		return "OTIO_NODE_KIND_EXTERNAL_REFERENCE"
	case NodeKindMissingReference:
		return "OTIO_NODE_KIND_MISSING_REFERENCE"
	case NodeKindGeneratorReference:
		return "OTIO_NODE_KIND_GENERATOR_REFERENCE"
	case NodeKindImageSequenceReference:
		return "OTIO_NODE_KIND_IMAGE_SEQUENCE_REFERENCE"
	case NodeKindSerializableCollection:
		return "OTIO_NODE_KIND_SERIALIZABLE_COLLECTION"
	case NodeKindSerializableObject:
		return "OTIO_NODE_KIND_SERIALIZABLE_OBJECT"
	case NodeKindSerializableObjectWithMetadata:
		return "OTIO_NODE_KIND_SERIALIZABLE_OBJECT_WITH_METADATA"
	case NodeKindComposable:
		return "OTIO_NODE_KIND_COMPOSABLE"
	case NodeKindComposition:
		return "OTIO_NODE_KIND_COMPOSITION"
	case NodeKindMediaReference:
		return "OTIO_NODE_KIND_MEDIA_REFERENCE"
	case NodeKindUnknownSchema:
		return "OTIO_NODE_KIND_UNKNOWN_SCHEMA"
	case NodeKindOther:
		return "OTIO_NODE_KIND_OTHER"
	}
	return "NodeKind(" + strconv.Itoa(int(v)) + ")"
}

// A ReferencePoint is which clock a three- or four-point edit lines its
// media up against.
//
// C: OtioReferencePoint
type ReferencePoint int32

const (
	// ReferencePointSource means use the media's own timing, and take as much of
	// it as fits.
	ReferencePointSource ReferencePoint = 0
	// ReferencePointSequence means line the media up against the track, trimming
	// it to the gap.
	ReferencePointSequence ReferencePoint = 1
	// ReferencePointFit means stretch or squeeze the media to fill the gap
	// exactly.
	ReferencePointFit ReferencePoint = 2
)

// String gives the name the C interface spells this by.
func (v ReferencePoint) String() string {
	switch v {
	case ReferencePointSource:
		return "OTIO_REFERENCE_POINT_SOURCE"
	case ReferencePointSequence:
		return "OTIO_REFERENCE_POINT_SEQUENCE"
	case ReferencePointFit:
		return "OTIO_REFERENCE_POINT_FIT"
	}
	return "ReferencePoint(" + strconv.Itoa(int(v)) + ")"
}

// A Status is what a call did, or why it could not.
//
// StatusOK is zero, so if (otio_...(...)) { /* failed */ } reads the way a C
// programmer expects.
//
// C: OtioStatus
type Status int32

const (
	// StatusOK means the call succeeded.
	StatusOK Status = 0
	// StatusNullPointer means a pointer argument that may not be nil was nil.
	StatusNullPointer Status = 1
	// StatusInvalidUTF8 means a string argument was not valid UTF-8.
	StatusInvalidUTF8 Status = 2
	// StatusNoValue means the call succeeded, and the answer is that there is no
	// value.
	//
	// An item with no source_range and a clip with no active media reference
	// both report this. It is not an error.
	StatusNoValue Status = 3
	// StatusStaleHandle means a node handle named an object that no longer
	// exists.
	StatusStaleHandle Status = 4
	// StatusInvalidArgument means an argument was outside the range the call
	// accepts.
	StatusInvalidArgument Status = 5
	// StatusCoreError means the document could not answer the question asked of
	// it.
	//
	// Asking a marker for its duration, or a track for a child it does not hold,
	// lands here. [ErrorMessage] says which.
	StatusCoreError Status = 6
	// StatusTimeError means a timecode or time string could not be read or
	// written.
	StatusTimeError Status = 7
	// StatusParseError means a file was not valid for the format it was read as.
	StatusParseError Status = 8
	// StatusUnsupported means the document holds something the target format
	// cannot express.
	StatusUnsupported Status = 9
	// StatusIoError means a file could not be read from or written to disk.
	StatusIoError Status = 10
	// StatusPanic means a panic in the Rust core was caught at the boundary.
	//
	// The library is left in an unspecified state; a caller that sees this
	// should stop using the document it was working on.
	StatusPanic Status = 11
)

// String gives the name the C interface spells this by.
func (v Status) String() string {
	switch v {
	case StatusOK:
		return "OTIO_STATUS_OK"
	case StatusNullPointer:
		return "OTIO_STATUS_NULL_POINTER"
	case StatusInvalidUTF8:
		return "OTIO_STATUS_INVALID_UTF8"
	case StatusNoValue:
		return "OTIO_STATUS_NO_VALUE"
	case StatusStaleHandle:
		return "OTIO_STATUS_STALE_HANDLE"
	case StatusInvalidArgument:
		return "OTIO_STATUS_INVALID_ARGUMENT"
	case StatusCoreError:
		return "OTIO_STATUS_CORE_ERROR"
	case StatusTimeError:
		return "OTIO_STATUS_TIME_ERROR"
	case StatusParseError:
		return "OTIO_STATUS_PARSE_ERROR"
	case StatusUnsupported:
		return "OTIO_STATUS_UNSUPPORTED"
	case StatusIoError:
		return "OTIO_STATUS_IO_ERROR"
	case StatusPanic:
		return "OTIO_STATUS_PANIC"
	}
	return "Status(" + strconv.Itoa(int(v)) + ")"
}

// A ValueKind is what kind of value sits at a path.
//
// C: OtioValueKind
type ValueKind int32

const (
	// ValueKindNull means jSON nil.
	ValueKindNull ValueKind = 0
	// ValueKindBool means a boolean.
	ValueKindBool ValueKind = 1
	// ValueKindInt means a signed integer.
	ValueKindInt ValueKind = 2
	// ValueKindUInt means an unsigned integer too large to be signed.
	ValueKindUInt ValueKind = 3
	// ValueKindDouble means a number.
	ValueKindDouble ValueKind = 4
	// ValueKindString means a string.
	ValueKindString ValueKind = 5
	// ValueKindRationalTime means a RationalTime.
	ValueKindRationalTime ValueKind = 6
	// ValueKindTimeRange means a TimeRange.
	ValueKindTimeRange ValueKind = 7
	// ValueKindTimeTransform means a TimeTransform.
	ValueKindTimeTransform ValueKind = 8
	// ValueKindColor means a Color.
	ValueKindColor ValueKind = 9
	// ValueKindV2d means a V2d.
	ValueKindV2d ValueKind = 10
	// ValueKindBox2d means a Box2d.
	ValueKindBox2d ValueKind = 11
	// ValueKindVector means an array.
	ValueKindVector ValueKind = 12
	// ValueKindDictionary means a dictionary.
	ValueKindDictionary ValueKind = 13
	// ValueKindObject means a whole OTIO object, named by a handle.
	ValueKindObject ValueKind = 14
	// ValueKindOther means a kind added to the core since this ABI was written.
	//
	// Nothing produces this today. It exists so that a core that grows a new
	// metadata type reports something honest rather than a kind that means
	// something else.
	ValueKindOther ValueKind = 15
)

// String gives the name the C interface spells this by.
func (v ValueKind) String() string {
	switch v {
	case ValueKindNull:
		return "OTIO_VALUE_NULL"
	case ValueKindBool:
		return "OTIO_VALUE_BOOL"
	case ValueKindInt:
		return "OTIO_VALUE_INT"
	case ValueKindUInt:
		return "OTIO_VALUE_UINT"
	case ValueKindDouble:
		return "OTIO_VALUE_DOUBLE"
	case ValueKindString:
		return "OTIO_VALUE_STRING"
	case ValueKindRationalTime:
		return "OTIO_VALUE_RATIONAL_TIME"
	case ValueKindTimeRange:
		return "OTIO_VALUE_TIME_RANGE"
	case ValueKindTimeTransform:
		return "OTIO_VALUE_TIME_TRANSFORM"
	case ValueKindColor:
		return "OTIO_VALUE_COLOR"
	case ValueKindV2d:
		return "OTIO_VALUE_V2D"
	case ValueKindBox2d:
		return "OTIO_VALUE_BOX2D"
	case ValueKindVector:
		return "OTIO_VALUE_VECTOR"
	case ValueKindDictionary:
		return "OTIO_VALUE_DICTIONARY"
	case ValueKindObject:
		return "OTIO_VALUE_OBJECT"
	case ValueKindOther:
		return "OTIO_VALUE_OTHER"
	}
	return "ValueKind(" + strconv.Itoa(int(v)) + ")"
}
