// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

package otio

/*
#include <otio.h>
#include <stdlib.h>
*/
import "C"

import (
	"runtime"
	"unsafe"
)

// ReadFromBytes reads a document from the bytes of a file in some format.
//
// options may be nil for the format's usual behaviour.
//
// C: otio_read_from_bytes
func ReadFromBytes(format Format, data []byte, options *ReadOptions) (Node, error) {
	var cData *C.uint8_t
	if len(data) > 0 {
		cData = (*C.uint8_t)(unsafe.Pointer(&data[0]))
	}
	var cOptions *C.OtioReadOptions
	if options != nil {
		value, release := options.c()
		defer release()
		cOptions = &value
	}
	var outDocument *C.OtioDocument
	var cError C.OtioBuffer
	if status := C.otio_read_from_bytes(C.OtioFormat(format), cData, C.size_t(len(data)), cOptions, &outDocument, &cError); status != C.OTIO_STATUS_OK {
		return Node{}, statusError(status, cError)
	}
	root, err := rootOf(takeDocument(outDocument))
	if err != nil {
		return Node{}, err
	}
	return root, nil
}

// ReadFromFile reads a document from a file on disk in some format.
//
// An AAF is read where it lies, seeking around the file, rather than copied
// into memory first.
//
// A nil options means none.
//
// C: otio_read_from_file
func ReadFromFile(format Format, path string, options *ReadOptions) (Node, error) {
	cPath := C.CString(path)
	defer C.free(unsafe.Pointer(cPath))
	var cOptions *C.OtioReadOptions
	if options != nil {
		value, release := options.c()
		defer release()
		cOptions = &value
	}
	var outDocument *C.OtioDocument
	var cError C.OtioBuffer
	if status := C.otio_read_from_file(C.OtioFormat(format), cPath, cOptions, &outDocument, &cError); status != C.OTIO_STATUS_OK {
		return Node{}, statusError(status, cError)
	}
	root, err := rootOf(takeDocument(outDocument))
	if err != nil {
		return Node{}, err
	}
	return root, nil
}

// ReadOptionsDefault returns the defaults, for a caller that wants to change
// one field.
//
// C: otio_read_options_default
func ReadOptionsDefault() ReadOptions {
	value := C.otio_read_options_default()
	return readOptionsFromC(value)
}

// WriteOptionsDefault returns the defaults, for a caller that wants to
// change one field.
//
// C: otio_write_options_default
func WriteOptionsDefault() WriteOptions {
	value := C.otio_write_options_default()
	return writeOptionsFromC(value)
}

// WriteToBytes writes a document as the bytes of a file in some format.
//
// The buffer is NUL-terminated, so a text format's output can be used as a C
// string; len is what matters for a binary one.
//
// A nil options means none.
//
// C: otio_write_to_bytes
func WriteToBytes(format Format, root Node, options *WriteOptions) ([]byte, error) {
	at, err := rootedAt(root)
	if err != nil {
		return nil, err
	}
	var cOptions *C.OtioWriteOptions
	if options != nil {
		value, release := options.c()
		defer release()
		cOptions = &value
	}
	var outBytes C.OtioBuffer
	var cError C.OtioBuffer
	if status := C.otio_write_to_bytes(C.OtioFormat(format), at.ptr, cOptions, &outBytes, &cError); status != C.OTIO_STATUS_OK {
		return nil, statusError(status, cError)
	}
	defer C.otio_buffer_free(outBytes)
	runtime.KeepAlive(at.doc)
	return goBytes(outBytes), nil
}

// WriteToFile writes a document to a file on disk in some format.
//
// A nil options means none.
//
// C: otio_write_to_file
func WriteToFile(format Format, root Node, path string, options *WriteOptions) error {
	at, err := rootedAt(root)
	if err != nil {
		return err
	}
	cPath := C.CString(path)
	defer C.free(unsafe.Pointer(cPath))
	var cOptions *C.OtioWriteOptions
	if options != nil {
		value, release := options.c()
		defer release()
		cOptions = &value
	}
	var cError C.OtioBuffer
	if status := C.otio_write_to_file(C.OtioFormat(format), at.ptr, cPath, cOptions, &cError); status != C.OTIO_STATUS_OK {
		return statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return nil
}

// FlattenStack collapses a stack's tracks into one, top layer winning where
// it is visible.
//
// C: otio_algorithm_flatten_stack
func FlattenStack(stack Node) (Node, error) {
	at := stack.at()
	cStack, err := at.doc.handleOf(stack)
	if err != nil {
		return Node{}, err
	}
	var outTrack C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_algorithm_flatten_stack(at.ptr, cStack, &outTrack, &cError); status != C.OTIO_STATUS_OK {
		return Node{}, statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return Node{doc: at.doc, h: outTrack}, nil
}

// FlattenTracks collapses a list of tracks into one, lowest first.
//
// A nil tracks means none.
//
// C: otio_algorithm_flatten_tracks
func FlattenTracks(tracks []Node) (Node, error) {
	at, err := siteOfAll(tracks)
	if err != nil {
		return Node{}, err
	}
	cTracks := make([]C.OtioNode, len(tracks))
	for index, item := range tracks {
		handle, err := at.doc.handleOf(item)
		if err != nil {
			return Node{}, err
		}
		cTracks[index] = handle
	}
	var cTracksFirst *C.OtioNode
	if len(cTracks) > 0 {
		cTracksFirst = &cTracks[0]
	}
	var outTrack C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_algorithm_flatten_tracks(at.ptr, cTracksFirst, C.size_t(len(tracks)), &outTrack, &cError); status != C.OTIO_STATUS_OK {
		return Node{}, statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return Node{doc: at.doc, h: outTrack}, nil
}

// TrackTrimmedToRange returns a copy of a track holding only what falls
// inside a span.
//
// The copy is added to the same document and has no parent.
//
// C: otio_algorithm_track_trimmed_to_range
func TrackTrimmedToRange(track Node, trimRange TimeRange) (Node, error) {
	at := track.at()
	cTrack, err := at.doc.handleOf(track)
	if err != nil {
		return Node{}, err
	}
	cTrimRange, releaseTrimRange := trimRange.c()
	defer releaseTrimRange()
	var outTrack C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_algorithm_track_trimmed_to_range(at.ptr, cTrack, cTrimRange, &outTrack, &cError); status != C.OTIO_STATUS_OK {
		return Node{}, statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return Node{doc: at.doc, h: outTrack}, nil
}

// FromJSON reads a document from OTIO JSON.
//
// C: otio_document_from_json
func FromJSON(json string) (Node, error) {
	cJSON := C.CString(json)
	defer C.free(unsafe.Pointer(cJSON))
	var outDocument *C.OtioDocument
	var cError C.OtioBuffer
	if status := C.otio_document_from_json(cJSON, &outDocument, &cError); status != C.OTIO_STATUS_OK {
		return Node{}, statusError(status, cError)
	}
	root, err := rootOf(takeDocument(outDocument))
	if err != nil {
		return Node{}, err
	}
	return root, nil
}

// ReadOTIOFile reads a document from a .otio file on disk.
//
// C: otio_document_read_from_file
func ReadOTIOFile(path string) (Node, error) {
	cPath := C.CString(path)
	defer C.free(unsafe.Pointer(cPath))
	var outDocument *C.OtioDocument
	var cError C.OtioBuffer
	if status := C.otio_document_read_from_file(cPath, &outDocument, &cError); status != C.OTIO_STATUS_OK {
		return Node{}, statusError(status, cError)
	}
	root, err := rootOf(takeDocument(outDocument))
	if err != nil {
		return Node{}, err
	}
	return root, nil
}

// WriteOTIOFile writes a document to a .otio file on disk.
//
// C: otio_document_write_to_file
func WriteOTIOFile(root Node, path string, indent int) error {
	at, err := rootedAt(root)
	if err != nil {
		return err
	}
	cPath := C.CString(path)
	defer C.free(unsafe.Pointer(cPath))
	var cError C.OtioBuffer
	if status := C.otio_document_write_to_file(at.ptr, cPath, C.size_t(indent), &cError); status != C.OTIO_STATUS_OK {
		return statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return nil
}

// Fill drops an item into a gap on a track, fitting it as the reference
// point says.
//
// C: otio_edit_fill
func Fill(item Node, track Node, trackTime RationalTime, referencePoint ReferencePoint) error {
	at := track.at()
	cItem, err := at.doc.adopt(item)
	if err != nil {
		return err
	}
	cTrack, err := at.doc.handleOf(track)
	if err != nil {
		return err
	}
	cTrackTime, releaseTrackTime := trackTime.c()
	defer releaseTrackTime()
	var cError C.OtioBuffer
	if status := C.otio_edit_fill(at.ptr, cItem, cTrack, cTrackTime, C.OtioReferencePoint(referencePoint), &cError); status != C.OTIO_STATUS_OK {
		return statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return nil
}

// Insert inserts an item at an instant, pushing what follows later.
//
// A nil fillTemplate means none.
//
// C: otio_edit_insert
func Insert(item Node, composition Node, time RationalTime, removeTransitions bool, fillTemplate *Node) error {
	at := composition.at()
	cItem, err := at.doc.adoptOrphan(item)
	if err != nil {
		return err
	}
	cComposition, err := at.doc.handleOf(composition)
	if err != nil {
		return err
	}
	cTime, releaseTime := time.c()
	defer releaseTime()
	cFillTemplate := C.otio_node_none()
	if fillTemplate != nil {
		handle, err := at.doc.adopt(*fillTemplate)
		if err != nil {
			return err
		}
		cFillTemplate = handle
	}
	var cError C.OtioBuffer
	if status := C.otio_edit_insert(at.ptr, cItem, cComposition, cTime, C.bool(removeTransitions), cFillTemplate, &cError); status != C.OTIO_STATUS_OK {
		return statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return nil
}

// Overwrite lays an item over a span of a composition, replacing what was
// there.
//
// fill_template is the item to fill any gap the edit opens with, or NodeNone
// for a plain gap.
//
// A nil fillTemplate means none.
//
// C: otio_edit_overwrite
func Overwrite(item Node, composition Node, span TimeRange, removeTransitions bool, fillTemplate *Node) error {
	at := composition.at()
	cItem, err := at.doc.adoptOrphan(item)
	if err != nil {
		return err
	}
	cComposition, err := at.doc.handleOf(composition)
	if err != nil {
		return err
	}
	cRange, releaseSpan := span.c()
	defer releaseSpan()
	cFillTemplate := C.otio_node_none()
	if fillTemplate != nil {
		handle, err := at.doc.adopt(*fillTemplate)
		if err != nil {
			return err
		}
		cFillTemplate = handle
	}
	var cError C.OtioBuffer
	if status := C.otio_edit_overwrite(at.ptr, cItem, cComposition, cRange, C.bool(removeTransitions), cFillTemplate, &cError); status != C.OTIO_STATUS_OK {
		return statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return nil
}

// Remove takes whatever sits at an instant out of a composition.
//
// With fill set, a gap takes its place; without, what follows moves up.
//
// A nil fillTemplate means none.
//
// C: otio_edit_remove
func Remove(composition Node, time RationalTime, fill bool, fillTemplate *Node) error {
	at := composition.at()
	cComposition, err := at.doc.handleOf(composition)
	if err != nil {
		return err
	}
	cTime, releaseTime := time.c()
	defer releaseTime()
	cFillTemplate := C.otio_node_none()
	if fillTemplate != nil {
		handle, err := at.doc.adopt(*fillTemplate)
		if err != nil {
			return err
		}
		cFillTemplate = handle
	}
	var cError C.OtioBuffer
	if status := C.otio_edit_remove(at.ptr, cComposition, cTime, C.bool(fill), cFillTemplate, &cError); status != C.OTIO_STATUS_OK {
		return statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return nil
}

// Ripple moves an item's in and out points, sliding everything after it.
//
// C: otio_edit_ripple
func Ripple(item Node, deltaIn RationalTime, deltaOut RationalTime) error {
	at := item.at()
	cItem, err := at.doc.handleOf(item)
	if err != nil {
		return err
	}
	cDeltaIn, releaseDeltaIn := deltaIn.c()
	defer releaseDeltaIn()
	cDeltaOut, releaseDeltaOut := deltaOut.c()
	defer releaseDeltaOut()
	var cError C.OtioBuffer
	if status := C.otio_edit_ripple(at.ptr, cItem, cDeltaIn, cDeltaOut, &cError); status != C.OTIO_STATUS_OK {
		return statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return nil
}

// Roll moves the cut between an item and its neighbour.
//
// C: otio_edit_roll
func Roll(item Node, deltaIn RationalTime, deltaOut RationalTime) error {
	at := item.at()
	cItem, err := at.doc.handleOf(item)
	if err != nil {
		return err
	}
	cDeltaIn, releaseDeltaIn := deltaIn.c()
	defer releaseDeltaIn()
	cDeltaOut, releaseDeltaOut := deltaOut.c()
	defer releaseDeltaOut()
	var cError C.OtioBuffer
	if status := C.otio_edit_roll(at.ptr, cItem, cDeltaIn, cDeltaOut, &cError); status != C.OTIO_STATUS_OK {
		return statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return nil
}

// Slice cuts whatever sits at an instant into two.
//
// C: otio_edit_slice
func Slice(composition Node, time RationalTime, removeTransitions bool) error {
	at := composition.at()
	cComposition, err := at.doc.handleOf(composition)
	if err != nil {
		return err
	}
	cTime, releaseTime := time.c()
	defer releaseTime()
	var cError C.OtioBuffer
	if status := C.otio_edit_slice(at.ptr, cComposition, cTime, C.bool(removeTransitions), &cError); status != C.OTIO_STATUS_OK {
		return statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return nil
}

// Slide moves an item along its track, taking the time from its neighbours.
//
// C: otio_edit_slide
func Slide(item Node, delta RationalTime) error {
	at := item.at()
	cItem, err := at.doc.handleOf(item)
	if err != nil {
		return err
	}
	cDelta, releaseDelta := delta.c()
	defer releaseDelta()
	var cError C.OtioBuffer
	if status := C.otio_edit_slide(at.ptr, cItem, cDelta, &cError); status != C.OTIO_STATUS_OK {
		return statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return nil
}

// Slip moves the media inside an item without moving the item.
//
// C: otio_edit_slip
func Slip(item Node, delta RationalTime) error {
	at := item.at()
	cItem, err := at.doc.handleOf(item)
	if err != nil {
		return err
	}
	cDelta, releaseDelta := delta.c()
	defer releaseDelta()
	var cError C.OtioBuffer
	if status := C.otio_edit_slip(at.ptr, cItem, cDelta, &cError); status != C.OTIO_STATUS_OK {
		return statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return nil
}

// Trim moves an item's in and out points without moving its neighbours.
//
// A nil fillTemplate means none.
//
// C: otio_edit_trim
func Trim(item Node, deltaIn RationalTime, deltaOut RationalTime, fillTemplate *Node) error {
	at := item.at()
	cItem, err := at.doc.handleOf(item)
	if err != nil {
		return err
	}
	cDeltaIn, releaseDeltaIn := deltaIn.c()
	defer releaseDeltaIn()
	cDeltaOut, releaseDeltaOut := deltaOut.c()
	defer releaseDeltaOut()
	cFillTemplate := C.otio_node_none()
	if fillTemplate != nil {
		handle, err := at.doc.adopt(*fillTemplate)
		if err != nil {
			return err
		}
		cFillTemplate = handle
	}
	var cError C.OtioBuffer
	if status := C.otio_edit_trim(at.ptr, cItem, cDeltaIn, cDeltaOut, cFillTemplate, &cError); status != C.OTIO_STATUS_OK {
		return statusError(status, cError)
	}
	runtime.KeepAlive(at.doc)
	return nil
}

// NewClip creates a clip. name may be empty for an unnamed one.
//
// C: otio_clip_new
func NewClip(name string) (Clip, error) {
	doc, err := newDocument()
	if err != nil {
		return Clip{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_clip_new(doc.ptr, cName, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return Clip{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapClip(Node{doc: doc, h: outNode}), nil
}

// NewComposable creates a composable: something that sits in a composition
// and nothing more.
//
// An empty name means none.
//
// C: otio_composable_new
func NewComposable(name string) (Composable, error) {
	doc, err := newDocument()
	if err != nil {
		return Composable{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_composable_new(doc.ptr, cName, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return Composable{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapComposable(Node{doc: doc, h: outNode}), nil
}

// NewComposition creates a bare composition: children with no layout of its
// own.
//
// An empty name means none.
//
// C: otio_composition_new
func NewComposition(name string) (Composition, error) {
	doc, err := newDocument()
	if err != nil {
		return Composition{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_composition_new(doc.ptr, cName, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return Composition{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapComposition(Node{doc: doc, h: outNode}), nil
}

// NewEffect creates an effect. effect_name is the effect's own name, such as
// "Blur", which is separate from the object's name.
//
// An empty name means none.
//
// An empty effectName means none.
//
// C: otio_effect_new
func NewEffect(name string, effectName string) (Effect, error) {
	doc, err := newDocument()
	if err != nil {
		return Effect{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var cEffectName *C.char
	if effectName != "" {
		cEffectName = C.CString(effectName)
		defer C.free(unsafe.Pointer(cEffectName))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_effect_new(doc.ptr, cName, cEffectName, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return Effect{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapEffect(Node{doc: doc, h: outNode}), nil
}

// NewExternalReference creates a media reference pointing at a URL.
//
// An empty name means none.
//
// An empty targetURL means none.
//
// C: otio_external_reference_new
func NewExternalReference(name string, targetURL string) (ExternalReference, error) {
	doc, err := newDocument()
	if err != nil {
		return ExternalReference{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var cTargetURL *C.char
	if targetURL != "" {
		cTargetURL = C.CString(targetURL)
		defer C.free(unsafe.Pointer(cTargetURL))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_external_reference_new(doc.ptr, cName, cTargetURL, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return ExternalReference{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapExternalReference(Node{doc: doc, h: outNode}), nil
}

// NewFreezeFrame creates a freeze frame: a hold on a single frame.
//
// An empty name means none.
//
// C: otio_freeze_frame_new
func NewFreezeFrame(name string) (FreezeFrame, error) {
	doc, err := newDocument()
	if err != nil {
		return FreezeFrame{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_freeze_frame_new(doc.ptr, cName, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return FreezeFrame{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapFreezeFrame(Node{doc: doc, h: outNode}), nil
}

// NewGap creates a gap.
//
// An empty name means none.
//
// C: otio_gap_new
func NewGap(name string) (Gap, error) {
	doc, err := newDocument()
	if err != nil {
		return Gap{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_gap_new(doc.ptr, cName, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return Gap{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapGap(Node{doc: doc, h: outNode}), nil
}

// NewGeneratorReference creates a media reference for generated media, such
// as colour bars.
//
// An empty name means none.
//
// An empty generatorKind means none.
//
// C: otio_generator_reference_new
func NewGeneratorReference(name string, generatorKind string) (GeneratorReference, error) {
	doc, err := newDocument()
	if err != nil {
		return GeneratorReference{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var cGeneratorKind *C.char
	if generatorKind != "" {
		cGeneratorKind = C.CString(generatorKind)
		defer C.free(unsafe.Pointer(cGeneratorKind))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_generator_reference_new(doc.ptr, cName, cGeneratorKind, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return GeneratorReference{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapGeneratorReference(Node{doc: doc, h: outNode}), nil
}

// NewImageSequenceReference creates a media reference for a numbered
// sequence of image files.
//
// The filename parts and the numbers start empty and at zero; set them with
// [SetNumbers] and the calls beside it.
//
// An empty name means none.
//
// C: otio_image_sequence_reference_new
func NewImageSequenceReference(name string) (ImageSequenceReference, error) {
	doc, err := newDocument()
	if err != nil {
		return ImageSequenceReference{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_image_sequence_reference_new(doc.ptr, cName, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return ImageSequenceReference{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapImageSequenceReference(Node{doc: doc, h: outNode}), nil
}

// NewItem creates a bare item: something that occupies time without saying
// what fills it.
//
// An empty name means none.
//
// C: otio_item_new
func NewItem(name string) (Item, error) {
	doc, err := newDocument()
	if err != nil {
		return Item{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_item_new(doc.ptr, cName, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return Item{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapItem(Node{doc: doc, h: outNode}), nil
}

// NewLinearTimeWarp creates a constant-rate speed change. A time_scalar of
// 2.0 plays twice as fast.
//
// An empty name means none.
//
// C: otio_linear_time_warp_new
func NewLinearTimeWarp(name string, timeScalar float64) (LinearTimeWarp, error) {
	doc, err := newDocument()
	if err != nil {
		return LinearTimeWarp{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_linear_time_warp_new(doc.ptr, cName, C.double(timeScalar), &outNode, &cError); status != C.OTIO_STATUS_OK {
		return LinearTimeWarp{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapLinearTimeWarp(Node{doc: doc, h: outNode}), nil
}

// NewMarker creates a marker covering marked_range.
//
// An empty name means none.
//
// C: otio_marker_new
func NewMarker(name string, markedRange TimeRange) (Marker, error) {
	doc, err := newDocument()
	if err != nil {
		return Marker{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	cMarkedRange, releaseMarkedRange := markedRange.c()
	defer releaseMarkedRange()
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_marker_new(doc.ptr, cName, cMarkedRange, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return Marker{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapMarker(Node{doc: doc, h: outNode}), nil
}

// NewMissingReference creates a media reference for media known to exist
// somewhere unknown.
//
// An empty name means none.
//
// C: otio_missing_reference_new
func NewMissingReference(name string) (MissingReference, error) {
	doc, err := newDocument()
	if err != nil {
		return MissingReference{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_missing_reference_new(doc.ptr, cName, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return MissingReference{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapMissingReference(Node{doc: doc, h: outNode}), nil
}

// NodeNone returns the handle that names no object.
//
// Fields that may be absent, such as a timeline's tracks before one is set,
// report this. Compare against it with IsNone.
//
// C: otio_node_none
func NodeNone() Node {
	value := C.otio_node_none()
	return Node{doc: nil, h: value}
}

// NewSerializableCollection creates a serializable collection: a group of
// objects with no timing.
//
// An empty name means none.
//
// C: otio_serializable_collection_new
func NewSerializableCollection(name string) (SerializableCollection, error) {
	doc, err := newDocument()
	if err != nil {
		return SerializableCollection{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_serializable_collection_new(doc.ptr, cName, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return SerializableCollection{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapSerializableCollection(Node{doc: doc, h: outNode}), nil
}

// NewStack creates a stack.
//
// An empty name means none.
//
// C: otio_stack_new
func NewStack(name string) (Stack, error) {
	doc, err := newDocument()
	if err != nil {
		return Stack{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_stack_new(doc.ptr, cName, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return Stack{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapStack(Node{doc: doc, h: outNode}), nil
}

// NewTimeEffect creates a time effect: an effect that alters timing and has
// no parameters.
//
// An empty name means none.
//
// An empty effectName means none.
//
// C: otio_time_effect_new
func NewTimeEffect(name string, effectName string) (TimeEffect, error) {
	doc, err := newDocument()
	if err != nil {
		return TimeEffect{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var cEffectName *C.char
	if effectName != "" {
		cEffectName = C.CString(effectName)
		defer C.free(unsafe.Pointer(cEffectName))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_time_effect_new(doc.ptr, cName, cEffectName, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return TimeEffect{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapTimeEffect(Node{doc: doc, h: outNode}), nil
}

// NewTimeline creates a timeline, with an empty stack named "tracks" already
// in it.
//
// Upstream's Timeline() builds that stack in its constructor, and its own
// tests append to a fresh timeline's tracks without making one first, so a
// timeline from here arrives the same way rather than leaving every binding
// to invent the difference. Replace it with [SetTracks] to use a stack of
// your own; the one built here is thrown away with the document.
//
// An empty name means none.
//
// C: otio_timeline_new
func NewTimeline(name string) (Timeline, error) {
	doc, err := newDocument()
	if err != nil {
		return Timeline{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_timeline_new(doc.ptr, cName, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return Timeline{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapTimeline(Node{doc: doc, h: outNode}), nil
}

// NewTrack creates a track. kind may be empty, which means "Video", as
// upstream's default does.
//
// C: otio_track_new
func NewTrack(name string, kind string) (Track, error) {
	doc, err := newDocument()
	if err != nil {
		return Track{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var cKind *C.char
	if kind != "" {
		cKind = C.CString(kind)
		defer C.free(unsafe.Pointer(cKind))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_track_new(doc.ptr, cName, cKind, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return Track{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapTrack(Node{doc: doc, h: outNode}), nil
}

// NewTransition creates a transition. Its offsets start at zero.
//
// An empty name means none.
//
// An empty transitionType means none.
//
// C: otio_transition_new
func NewTransition(name string, transitionType string) (Transition, error) {
	doc, err := newDocument()
	if err != nil {
		return Transition{}, err
	}
	var cName *C.char
	if name != "" {
		cName = C.CString(name)
		defer C.free(unsafe.Pointer(cName))
	}
	var cTransitionType *C.char
	if transitionType != "" {
		cTransitionType = C.CString(transitionType)
		defer C.free(unsafe.Pointer(cTransitionType))
	}
	var outNode C.OtioNode
	var cError C.OtioBuffer
	if status := C.otio_transition_new(doc.ptr, cName, cTransitionType, &outNode, &cError); status != C.OTIO_STATUS_OK {
		return Transition{}, statusError(status, cError)
	}
	runtime.KeepAlive(doc)
	return wrapTransition(Node{doc: doc, h: outNode}), nil
}
