// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

//! Builds the OpenTimelineIO package and runs its tests.
//!
//! The package is Zig over the C ABI of the otio-rust core, and it links
//! against a static library it expects to find in `lib/`:
//!
//! ```sh
//! cargo build -p otio-capi --release
//! cp target/release/libotio.a sdk/zig/lib/
//! zig build test
//! ```
//!
//! For a Windows MSVC target the library is `otio.lib`, built with the
//! static C runtime Zig links, and stripped of Rust's copy of compiler-rt,
//! which collides with Zig's own (see `scripts/strip-msvc-builtins.sh`):
//!
//! ```sh
//! RUSTFLAGS="-C target-feature=+crt-static" cargo build -p otio-capi --release --target x86_64-pc-windows-msvc
//! scripts/strip-msvc-builtins.sh target/x86_64-pc-windows-msvc/release/otio.lib
//! cp target/x86_64-pc-windows-msvc/release/otio.lib sdk/zig/lib/
//! zig build test -Dtarget=x86_64-windows-msvc
//! ```

const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const library = b.option(
        []const u8,
        "library",
        "Where libotio.a (otio.lib for MSVC) is, if not lib/",
    ) orelse "lib";

    const otio = b.addModule("otio", .{
        .root_source_file = b.path("src/root.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    otio.addLibraryPath(.{ .cwd_relative = library });
    otio.linkSystemLibrary("otio", .{});
    // What the Rust standard library needs underneath it. A Rust panic
    // unwinds, and the unwinder is not in libc: on Darwin it comes with the
    // system, on MSVC it is the C runtime's own, and everywhere else Zig's
    // own is asked for by name. The Windows import libraries are the ones
    // `rustc --print native-static-libs` lists for both Windows ABIs.
    if (target.result.os.tag.isDarwin()) {
        otio.linkFramework("CoreFoundation", .{});
        otio.linkFramework("Security", .{});
        otio.linkSystemLibrary("iconv", .{});
    } else if (target.result.os.tag == .windows) {
        for ([_][]const u8{ "kernel32", "ntdll", "userenv", "ws2_32", "dbghelp" }) |name|
            otio.linkSystemLibrary(name, .{});
        if (target.result.abi != .msvc) otio.linkSystemLibrary("unwind", .{});
    } else {
        otio.linkSystemLibrary("unwind", .{});
    }

    const tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("test/suite.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "otio", .module = otio }},
        }),
    });
    const run = b.addRunArtifact(tests);
    run.has_side_effects = true;

    const step = b.step("test", "Run the package's tests");
    step.dependOn(&run.step);
}
