// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace OpenTimelineIO;

public partial class Clip
{
    /// <summary>
    /// Returns which of a clip's media references is in use.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_clip_active_media_reference_key</c>
    /// </para>
    /// </remarks>
    public string ActiveMediaReferenceKey()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_clip_active_media_reference_key(at.Pointer, at.Handle, out var outKey, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.Text(outKey);
    }

    /// <summary>
    /// Returns one of a clip's media references.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A null <c>key</c> means the active one. Reports <c>Status.NoValue</c>
    /// if the key names nothing, which for the active key is a clip with no
    /// media.
    /// </para>
    /// <para>
    /// C: <c>otio_clip_media_reference</c>
    /// </para>
    /// </remarks>
    public SerializableObject? MediaReference(string? key)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cKey = scratch.Utf8(key);
            var status = Native.otio_clip_media_reference(at.Pointer, at.Handle, cKey, out var outReference, out var error);
            GC.KeepAlive(at.Arena);
            if (status == Status.NoValue)
            {
                Interop.Release(error);
                return null;
            }
            Interop.Check(status, error);
            return Interop.MakeObject(at.Arena, outReference);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Returns how many media references a clip holds.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_clip_media_reference_count</c>
    /// </para>
    /// </remarks>
    public int MediaReferenceCount()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_clip_media_reference_count(at.Pointer, at.Handle, out var outCount, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return (int)outCount;
    }

    /// <summary>
    /// Returns the key of one of a clip's media references.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The references are ordered by key, so walking the indices walks them
    /// in a stable order.
    /// </para>
    /// <para>
    /// C: <c>otio_clip_media_reference_key_at</c>
    /// </para>
    /// </remarks>
    public string MediaReferenceKeyAt(int index)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_clip_media_reference_key_at(at.Pointer, at.Handle, (nuint)index, out var outKey, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.Text(outKey);
    }

    /// <summary>
    /// Removes one of a clip's media references, and returns it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Where there is nothing to report this answers null, which is an answer
    /// rather than a failure.
    /// </para>
    /// <para>
    /// C: <c>otio_clip_remove_media_reference</c>
    /// </para>
    /// </remarks>
    public SerializableObject? RemoveMediaReference(string key)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cKey = scratch.Utf8(key);
            var status = Native.otio_clip_remove_media_reference(at.Pointer, at.Handle, cKey, out var outReference, out var error);
            GC.KeepAlive(at.Arena);
            if (status == Status.NoValue)
            {
                Interop.Release(error);
                return null;
            }
            Interop.Check(status, error);
            return Interop.MakeObject(at.Arena, outReference);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Sets which of a clip's media references is in use.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_clip_set_active_media_reference_key</c>
    /// </para>
    /// </remarks>
    public void SetActiveMediaReferenceKey(string key)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cKey = scratch.Utf8(key);
            var status = Native.otio_clip_set_active_media_reference_key(at.Pointer, at.Handle, cKey, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Sets one of a clip's media references, adding it if the key is new.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_clip_set_media_reference</c>
    /// </para>
    /// </remarks>
    public void SetMediaReference(string key, SerializableObject reference)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cKey = scratch.Utf8(key);
            var cReference = Interop.Adopt(at, reference);
            var status = Native.otio_clip_set_media_reference(at.Pointer, at.Handle, cKey, cReference, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }
}

public partial class Composition
{
    /// <summary>
    /// Adds a child to the end of a composition.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_composition_append_child</c>
    /// </para>
    /// </remarks>
    public void AppendChild(SerializableObject child)
    {
        var at = Interop.Locate(this);
        var cChild = Interop.AdoptOrphan(at, child);
        var status = Native.otio_composition_append_child(at.Pointer, at.Handle, cChild, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Returns the child of a composition that covers an instant.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>shallow</c> stops at the composition's own children rather than
    /// descending into nested ones. Reports <c>Status.NoValue</c> when
    /// nothing covers it.
    /// </para>
    /// <para>
    /// C: <c>otio_composition_child_at_time</c>
    /// </para>
    /// </remarks>
    public SerializableObject? ChildAtTime(RationalTime time, bool shallow)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_composition_child_at_time(at.Pointer, at.Handle, time.ToNative(), (shallow ? (byte)1 : (byte)0), out var outChild, out var error);
        GC.KeepAlive(at.Arena);
        if (status == Status.NoValue)
        {
            Interop.Release(error);
            return null;
        }
        Interop.Check(status, error);
        return Interop.MakeObject(at.Arena, outChild);
    }

    /// <summary>
    /// Returns the children of a composition that touch a span.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_composition_children_in_range</c>
    /// </para>
    /// </remarks>
    public SerializableObject[] ChildrenInRange(TimeRange searchRange)
    {
        var at = Interop.Locate(this);
        nuint count;
        var sizingStatus = Native.otio_composition_children_in_range(at.Pointer, at.Handle, searchRange.ToNative(), null, 0, out count, out var sizingError);
        Interop.Check(sizingStatus, sizingError);
        var buffer0 = new Native.OtioNode[(int)count];
        var fillingStatus = Native.otio_composition_children_in_range(at.Pointer, at.Handle, searchRange.ToNative(), buffer0, (nuint)buffer0.Length, out count, out var fillingError);
        Interop.Check(fillingStatus, fillingError);
        GC.KeepAlive(at.Arena);
        if ((int)count > buffer0.Length) { count = (nuint)buffer0.Length; }
        var buffer0Taken = new SerializableObject[(int)count];
        for (int slot = 0; slot < (int)count; slot++)
        {
            buffer0Taken[slot] = Interop.MakeObject(at.Arena, buffer0[slot]);
        }
        return buffer0Taken;
    }

    /// <summary>
    /// Removes every child of a composition, and returns them.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_composition_clear_children</c>
    /// </para>
    /// </remarks>
    public SerializableObject[] ClearChildren()
    {
        var at = Interop.Locate(this);
        nuint count;
        // otio_composition_clear_children answers and empties in one go, so the buffer is sized first.
        nuint room;
        var sizingStatus = Native.otio_node_child_count(at.Pointer, at.Handle, out room, out var sizingError);
        Interop.Check(sizingStatus, sizingError);
        var buffer0 = new Native.OtioNode[(int)room];
        var fillingStatus = Native.otio_composition_clear_children(at.Pointer, at.Handle, buffer0, (nuint)buffer0.Length, out count, out var fillingError);
        Interop.Check(fillingStatus, fillingError);
        GC.KeepAlive(at.Arena);
        if ((int)count > buffer0.Length) { count = (nuint)buffer0.Length; }
        var buffer0Taken = new SerializableObject[(int)count];
        for (int slot = 0; slot < (int)count; slot++)
        {
            buffer0Taken[slot] = Interop.MakeObject(at.Arena, buffer0[slot]);
        }
        return buffer0Taken;
    }

    /// <summary>
    /// Removes a child by handle.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_composition_detach_child</c>
    /// </para>
    /// </remarks>
    public void DetachChild(SerializableObject child)
    {
        var at = Interop.Locate(this);
        var cChild = Interop.RequireHere(at, child);
        var status = Native.otio_composition_detach_child(at.Pointer, at.Handle, cChild, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Returns every object of a kind at or below a composition.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A null <c>search_range</c> searches all of it. <c>shallow</c> stops
    /// the walk at the composition's own children.
    /// </para>
    /// <para>
    /// C: <c>otio_composition_find_children_of_kind</c>
    /// </para>
    /// </remarks>
    public SerializableObject[] FindChildrenOfKind(NodeKind kind, TimeRange? searchRange, bool shallow)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cSearchRange = searchRange is null ? IntPtr.Zero : scratch.Struct(searchRange.Value.ToNative());
            nuint count;
            var sizingStatus = Native.otio_composition_find_children_of_kind(at.Pointer, at.Handle, kind, cSearchRange, (shallow ? (byte)1 : (byte)0), null, 0, out count, out var sizingError);
            Interop.Check(sizingStatus, sizingError);
            var buffer0 = new Native.OtioNode[(int)count];
            var fillingStatus = Native.otio_composition_find_children_of_kind(at.Pointer, at.Handle, kind, cSearchRange, (shallow ? (byte)1 : (byte)0), buffer0, (nuint)buffer0.Length, out count, out var fillingError);
            Interop.Check(fillingStatus, fillingError);
            GC.KeepAlive(at.Arena);
            if ((int)count > buffer0.Length) { count = (nuint)buffer0.Length; }
            var buffer0Taken = new SerializableObject[(int)count];
            for (int slot = 0; slot < (int)count; slot++)
            {
                buffer0Taken[slot] = Interop.MakeObject(at.Arena, buffer0[slot]);
            }
            return buffer0Taken;
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Returns how much unused media a child has on each side.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_composition_handles_of_child</c>
    /// </para>
    /// </remarks>
    public Handles HandlesOfChild(SerializableObject child)
    {
        var at = Interop.Locate(this);
        var cChild = Interop.RequireHere(at, child);
        var status = Native.otio_composition_handles_of_child(at.Pointer, at.Handle, cChild, out var outHandles, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Handles.FromNative(outHandles);
    }

    /// <summary>
    /// Returns whether a composition holds an object directly.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_composition_has_child</c>
    /// </para>
    /// </remarks>
    public bool HasChild(SerializableObject child)
    {
        var at = Interop.Locate(this);
        var cChild = Interop.RequireHere(at, child);
        var status = Native.otio_composition_has_child(at.Pointer, at.Handle, cChild, out var outHas, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return outHas != 0;
    }

    /// <summary>
    /// Returns where a child sits in its composition.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_composition_index_of_child</c>
    /// </para>
    /// </remarks>
    public int IndexOfChild(SerializableObject child)
    {
        var at = Interop.Locate(this);
        var cChild = Interop.RequireHere(at, child);
        var status = Native.otio_composition_index_of_child(at.Pointer, at.Handle, cChild, out var outIndex, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return (int)outIndex;
    }

    /// <summary>
    /// Adds a child to a composition at an index.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A negative index counts from the end, as upstream's Python does. The
    /// child must not already be in a composition.
    /// </para>
    /// <para>
    /// C: <c>otio_composition_insert_child</c>
    /// </para>
    /// </remarks>
    public void InsertChild(long index, SerializableObject child)
    {
        var at = Interop.Locate(this);
        var cChild = Interop.AdoptOrphan(at, child);
        var status = Native.otio_composition_insert_child(at.Pointer, at.Handle, index, cChild, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Returns whether an object descends from a composition at any depth.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_composition_is_parent_of</c>
    /// </para>
    /// </remarks>
    public bool IsParentOf(SerializableObject other)
    {
        var at = Interop.Locate(this);
        var cOther = Interop.RequireHere(at, other);
        var status = Native.otio_composition_is_parent_of(at.Pointer, at.Handle, cOther, out var outIs, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return outIs != 0;
    }

    /// <summary>
    /// Returns the children on either side of one, or <c>None</c> where there
    /// is none.
    /// </summary>
    /// <remarks>
    /// <para>
    /// With <c>NeighborGapPolicy.AroundTransitions</c>, a transition at the
    /// head or tail of a track gets a gap materialized for its overhang,
    /// which is why this takes a document it may edit.
    /// </para>
    /// <para>
    /// C: <c>otio_composition_neighbors_of</c>
    /// </para>
    /// </remarks>
    public (SerializableObject before, SerializableObject after) NeighborsOf(SerializableObject child, NeighborGapPolicy policy)
    {
        var at = Interop.Locate(this);
        var cChild = Interop.RequireHere(at, child);
        var status = Native.otio_composition_neighbors_of(at.Pointer, at.Handle, cChild, policy, out var outBefore, out var outAfter, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return (Interop.MakeObject(at.Arena, outBefore), Interop.MakeObject(at.Arena, outAfter));
    }

    /// <summary>
    /// Returns where a child sits in a composition's clock, at any depth.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_composition_range_of_child</c>
    /// </para>
    /// </remarks>
    public TimeRange RangeOfChild(SerializableObject child)
    {
        var at = Interop.Locate(this);
        var cChild = Interop.RequireHere(at, child);
        var status = Native.otio_composition_range_of_child(at.Pointer, at.Handle, cChild, out var outRange, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return TimeRange.FromNative(outRange);
    }

    /// <summary>
    /// Returns where the child at an index sits in its composition's clock.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A negative index counts from the end.
    /// </para>
    /// <para>
    /// C: <c>otio_composition_range_of_child_at_index</c>
    /// </para>
    /// </remarks>
    public TimeRange RangeOfChildAtIndex(long index)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_composition_range_of_child_at_index(at.Pointer, at.Handle, index, out var outRange, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return TimeRange.FromNative(outRange);
    }

    /// <summary>
    /// Returns where every child of a composition sits, in one pass.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>out_nodes</c> and <c>out_ranges</c> are filled in step, so entry
    /// <c>i</c> of one goes with entry <c>i</c> of the other. Either may be
    /// null when only the count is wanted.
    /// </para>
    /// <para>
    /// C: <c>otio_composition_ranges_of_children</c>
    /// </para>
    /// </remarks>
    public (SerializableObject[] nodes, TimeRange[] ranges) RangesOfChildren()
    {
        var at = Interop.Locate(this);
        nuint count;
        var sizingStatus = Native.otio_composition_ranges_of_children(at.Pointer, at.Handle, null, null, 0, out count, out var sizingError);
        Interop.Check(sizingStatus, sizingError);
        var buffer0 = new Native.OtioNode[(int)count];
        var buffer1 = new Native.OtioTimeRange[(int)count];
        var fillingStatus = Native.otio_composition_ranges_of_children(at.Pointer, at.Handle, buffer0, buffer1, (nuint)buffer0.Length, out count, out var fillingError);
        Interop.Check(fillingStatus, fillingError);
        GC.KeepAlive(at.Arena);
        if ((int)count > buffer0.Length) { count = (nuint)buffer0.Length; }
        var buffer0Taken = new SerializableObject[(int)count];
        for (int slot = 0; slot < (int)count; slot++)
        {
            buffer0Taken[slot] = Interop.MakeObject(at.Arena, buffer0[slot]);
        }
        var buffer1Taken = new TimeRange[(int)count];
        for (int slot = 0; slot < (int)count; slot++)
        {
            buffer1Taken[slot] = TimeRange.FromNative(buffer1[slot]);
        }
        return (buffer0Taken, buffer1Taken);
    }

    /// <summary>
    /// Removes a child by index, and returns it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The child stays in the document with no parent.
    /// </para>
    /// <para>
    /// C: <c>otio_composition_remove_child</c>
    /// </para>
    /// </remarks>
    public SerializableObject RemoveChild(long index)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_composition_remove_child(at.Pointer, at.Handle, index, out var outChild, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.MakeObject(at.Arena, outChild);
    }

    /// <summary>
    /// Clips a range to a composition's own trim.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Reports <c>Status.NoValue</c> when nothing of it is left.
    /// </para>
    /// <para>
    /// C: <c>otio_composition_trim_child_range</c>
    /// </para>
    /// </remarks>
    public TimeRange? TrimChildRange(TimeRange childRange)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_composition_trim_child_range(at.Pointer, at.Handle, childRange.ToNative(), out var outRange, out var error);
        GC.KeepAlive(at.Arena);
        if (status == Status.NoValue)
        {
            Interop.Release(error);
            return null;
        }
        Interop.Check(status, error);
        return TimeRange.FromNative(outRange);
    }

    /// <summary>
    /// Returns where a child sits after the composition's trim, at any depth.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Reports <c>Status.NoValue</c> when the trim excludes it entirely.
    /// </para>
    /// <para>
    /// C: <c>otio_composition_trimmed_range_of_child</c>
    /// </para>
    /// </remarks>
    public TimeRange? TrimmedRangeOfChild(SerializableObject child)
    {
        var at = Interop.Locate(this);
        var cChild = Interop.RequireHere(at, child);
        var status = Native.otio_composition_trimmed_range_of_child(at.Pointer, at.Handle, cChild, out var outRange, out var error);
        GC.KeepAlive(at.Arena);
        if (status == Status.NoValue)
        {
            Interop.Release(error);
            return null;
        }
        Interop.Check(status, error);
        return TimeRange.FromNative(outRange);
    }

    /// <summary>
    /// Returns where the child at an index sits, after the composition's own
    /// trim.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_composition_trimmed_range_of_child_at_index</c>
    /// </para>
    /// </remarks>
    public TimeRange TrimmedRangeOfChildAtIndex(long index)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_composition_trimmed_range_of_child_at_index(at.Pointer, at.Handle, index, out var outRange, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return TimeRange.FromNative(outRange);
    }
}

public partial class Effect
{
    /// <summary>
    /// Returns an effect's own name, such as <c>"LinearTimeWarp"</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_effect_effect_name</c>
    /// </para>
    /// </remarks>
    public string EffectName()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_effect_effect_name(at.Pointer, at.Handle, out var outName, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.Text(outName);
    }

    /// <summary>
    /// Returns whether an effect is applied.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_effect_enabled</c>
    /// </para>
    /// </remarks>
    public bool Enabled()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_effect_enabled(at.Pointer, at.Handle, out var outEnabled, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return outEnabled != 0;
    }

    /// <summary>
    /// Sets an effect's own name.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_effect_set_effect_name</c>
    /// </para>
    /// </remarks>
    public void SetEffectName(string effectName)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cEffectName = scratch.Utf8(effectName);
            var status = Native.otio_effect_set_effect_name(at.Pointer, at.Handle, cEffectName, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Sets whether an effect is applied.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_effect_set_enabled</c>
    /// </para>
    /// </remarks>
    public void SetEnabled(bool enabled)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_effect_set_enabled(at.Pointer, at.Handle, (enabled ? (byte)1 : (byte)0), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Sets a speed change's multiplier.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_effect_set_time_scalar</c>
    /// </para>
    /// </remarks>
    public void SetTimeScalar(double scalar)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_effect_set_time_scalar(at.Pointer, at.Handle, scalar, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Returns a speed change's multiplier.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Only a <c>LinearTimeWarp</c> and a <c>FreezeFrame</c> have one;
    /// anything else reports <c>Status.CoreError</c>.
    /// </para>
    /// <para>
    /// C: <c>otio_effect_time_scalar</c>
    /// </para>
    /// </remarks>
    public double TimeScalar()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_effect_time_scalar(at.Pointer, at.Handle, out var outScalar, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return outScalar;
    }
}

public partial class ExternalReference
{
    /// <summary>
    /// Sets where an external reference's media lives.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_external_reference_set_target_url</c>
    /// </para>
    /// </remarks>
    public void SetTargetUrl(string url)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cURL = scratch.Utf8(url);
            var status = Native.otio_external_reference_set_target_url(at.Pointer, at.Handle, cURL, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Returns where an external reference's media lives.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_external_reference_target_url</c>
    /// </para>
    /// </remarks>
    public string TargetUrl()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_external_reference_target_url(at.Pointer, at.Handle, out var outURL, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.Text(outURL);
    }
}

public partial class GeneratorReference
{
    /// <summary>
    /// Returns which generator a generator reference names, such as
    /// <c>"SMPTEBars"</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_generator_reference_kind</c>
    /// </para>
    /// </remarks>
    public string GeneratorKind()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_generator_reference_kind(at.Pointer, at.Handle, out var outKind, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.Text(outKind);
    }

    /// <summary>
    /// Sets which generator a generator reference names.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_generator_reference_set_kind</c>
    /// </para>
    /// </remarks>
    public void SetGeneratorKind(string kind)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cKind = scratch.Utf8(kind);
            var status = Native.otio_generator_reference_set_kind(at.Pointer, at.Handle, cKind, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }
}

public partial class ImageSequenceReference
{
    /// <summary>
    /// Returns the part of each frame's filename before the frame number.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_image_sequence_reference_name_prefix</c>
    /// </para>
    /// </remarks>
    public string NamePrefix()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_image_sequence_reference_name_prefix(at.Pointer, at.Handle, out var outPrefix, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.Text(outPrefix);
    }

    /// <summary>
    /// Returns the part of each frame's filename after the frame number.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_image_sequence_reference_name_suffix</c>
    /// </para>
    /// </remarks>
    public string NameSuffix()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_image_sequence_reference_name_suffix(at.Pointer, at.Handle, out var outSuffix, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.Text(outSuffix);
    }

    /// <summary>
    /// Returns the numbers describing how an image sequence is laid out.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_image_sequence_reference_numbers</c>
    /// </para>
    /// </remarks>
    public ImageSequence Numbers()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_image_sequence_reference_numbers(at.Pointer, at.Handle, out var outNumbers, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return ImageSequence.FromNative(outNumbers);
    }

    /// <summary>
    /// Sets the part of each frame's filename before the frame number.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_image_sequence_reference_set_name_prefix</c>
    /// </para>
    /// </remarks>
    public void SetNamePrefix(string prefix)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cPrefix = scratch.Utf8(prefix);
            var status = Native.otio_image_sequence_reference_set_name_prefix(at.Pointer, at.Handle, cPrefix, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Sets the part of each frame's filename after the frame number.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_image_sequence_reference_set_name_suffix</c>
    /// </para>
    /// </remarks>
    public void SetNameSuffix(string suffix)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cSuffix = scratch.Utf8(suffix);
            var status = Native.otio_image_sequence_reference_set_name_suffix(at.Pointer, at.Handle, cSuffix, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Sets the numbers describing how an image sequence is laid out.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_image_sequence_reference_set_numbers</c>
    /// </para>
    /// </remarks>
    public void SetNumbers(ImageSequence numbers)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_image_sequence_reference_set_numbers(at.Pointer, at.Handle, numbers.ToNative(), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Sets the directory an image sequence's frames sit in.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_image_sequence_reference_set_target_url_base</c>
    /// </para>
    /// </remarks>
    public void SetTargetUrlBase(string urlBase)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cURLBase = scratch.Utf8(urlBase);
            var status = Native.otio_image_sequence_reference_set_target_url_base(at.Pointer, at.Handle, cURLBase, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Returns the directory an image sequence's frames sit in.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_image_sequence_reference_target_url_base</c>
    /// </para>
    /// </remarks>
    public string TargetUrlBase()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_image_sequence_reference_target_url_base(at.Pointer, at.Handle, out var outURLBase, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.Text(outURLBase);
    }
}

public partial class Item
{
    /// <summary>
    /// Adds an effect to an item. Effects apply in the order they are added.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_append_effect</c>
    /// </para>
    /// </remarks>
    public void AppendEffect(SerializableObject effectHandle)
    {
        var at = Interop.Locate(this);
        var cEffectHandle = Interop.Adopt(at, effectHandle);
        var status = Native.otio_item_append_effect(at.Pointer, at.Handle, cEffectHandle, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Adds a marker to an item.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_append_marker</c>
    /// </para>
    /// </remarks>
    public void AppendMarker(SerializableObject markerHandle)
    {
        var at = Interop.Locate(this);
        var cMarkerHandle = Interop.Adopt(at, markerHandle);
        var status = Native.otio_item_append_marker(at.Pointer, at.Handle, cMarkerHandle, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Returns the span of media an object could draw on, before trimming.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_available_range</c>
    /// </para>
    /// </remarks>
    public TimeRange AvailableRange()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_available_range(at.Pointer, at.Handle, out var outRange, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return TimeRange.FromNative(outRange);
    }

    /// <summary>
    /// Clears an item's display tint.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_clear_color</c>
    /// </para>
    /// </remarks>
    public void ClearColor()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_clear_color(at.Pointer, at.Handle, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Clears an item's source range, so that it takes all of its media.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_clear_source_range</c>
    /// </para>
    /// </remarks>
    public void ClearSourceRange()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_clear_source_range(at.Pointer, at.Handle, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Returns an item's display tint, and the name that goes with it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>out_name</c> may be null if the name is not wanted. Reports
    /// <c>Status.NoValue</c> for an untinted item.
    /// </para>
    /// <para>
    /// C: <c>otio_item_color</c>
    /// </para>
    /// </remarks>
    public (global::OpenTimelineIO.Color color, string name)? Color()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_color(at.Pointer, at.Handle, out var outColor, out var outName, out var error);
        GC.KeepAlive(at.Arena);
        if (status == Status.NoValue)
        {
            Interop.Release(error);
            return null;
        }
        Interop.Check(status, error);
        return (global::OpenTimelineIO.Color.FromNative(outColor), Interop.Text(outName));
    }

    /// <summary>
    /// Returns how long an object occupies its parent's timeline.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_duration</c>
    /// </para>
    /// </remarks>
    public RationalTime Duration()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_duration(at.Pointer, at.Handle, out var outDuration, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return RationalTime.FromNative(outDuration);
    }

    /// <summary>
    /// Returns one of an item's effects.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_effect_at</c>
    /// </para>
    /// </remarks>
    public SerializableObject EffectAt(int index)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_effect_at(at.Pointer, at.Handle, (nuint)index, out var outEffect, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.MakeObject(at.Arena, outEffect);
    }

    /// <summary>
    /// Returns how many effects an item carries.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_effect_count</c>
    /// </para>
    /// </remarks>
    public int EffectCount()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_effect_count(at.Pointer, at.Handle, out var outCount, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return (int)outCount;
    }

    /// <summary>
    /// Returns whether an item contributes to its composition.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_enabled</c>
    /// </para>
    /// </remarks>
    public bool Enabled()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_enabled(at.Pointer, at.Handle, out var outEnabled, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return outEnabled != 0;
    }

    /// <summary>
    /// Returns one of an item's markers.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_marker_at</c>
    /// </para>
    /// </remarks>
    public SerializableObject MarkerAt(int index)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_marker_at(at.Pointer, at.Handle, (nuint)index, out var outMarker, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.MakeObject(at.Arena, outMarker);
    }

    /// <summary>
    /// Returns how many markers an item carries.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_marker_count</c>
    /// </para>
    /// </remarks>
    public int MarkerCount()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_marker_count(at.Pointer, at.Handle, out var outCount, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return (int)outCount;
    }

    /// <summary>
    /// Returns where an object sits in its parent's clock.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_range_in_parent</c>
    /// </para>
    /// </remarks>
    public TimeRange RangeInParent()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_range_in_parent(at.Pointer, at.Handle, out var outRange, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return TimeRange.FromNative(outRange);
    }

    /// <summary>
    /// Removes one of an item's effects, and returns it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_remove_effect</c>
    /// </para>
    /// </remarks>
    public SerializableObject RemoveEffect(int index)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_remove_effect(at.Pointer, at.Handle, (nuint)index, out var outEffect, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.MakeObject(at.Arena, outEffect);
    }

    /// <summary>
    /// Removes one of an item's markers, and returns it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The marker stays in the document; remove it with
    /// <c>RemoveFromTimelineRecursive</c> if nothing else holds it.
    /// </para>
    /// <para>
    /// C: <c>otio_item_remove_marker</c>
    /// </para>
    /// </remarks>
    public SerializableObject RemoveMarker(int index)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_remove_marker(at.Pointer, at.Handle, (nuint)index, out var outMarker, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.MakeObject(at.Arena, outMarker);
    }

    /// <summary>
    /// Sets an item's display tint. <c>name</c> may be null for an unnamed
    /// colour.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_set_color</c>
    /// </para>
    /// </remarks>
    public void SetColor(global::OpenTimelineIO.Color color, string? name)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cName = scratch.Utf8(name);
            var status = Native.otio_item_set_color(at.Pointer, at.Handle, color.ToNative(), cName, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Sets whether an item contributes to its composition.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_set_enabled</c>
    /// </para>
    /// </remarks>
    public void SetEnabled(bool enabled)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_set_enabled(at.Pointer, at.Handle, (enabled ? (byte)1 : (byte)0), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Sets the portion of its media an item uses.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_set_source_range</c>
    /// </para>
    /// </remarks>
    public void SetSourceRange(TimeRange range)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_set_source_range(at.Pointer, at.Handle, range.ToNative(), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Returns the portion of its media an item uses.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Reports <c>Status.NoValue</c> for an item that takes all of it.
    /// </para>
    /// <para>
    /// C: <c>otio_item_source_range</c>
    /// </para>
    /// </remarks>
    public TimeRange? SourceRange()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_source_range(at.Pointer, at.Handle, out var outRange, out var error);
        GC.KeepAlive(at.Arena);
        if (status == Status.NoValue)
        {
            Interop.Release(error);
            return null;
        }
        Interop.Check(status, error);
        return TimeRange.FromNative(outRange);
    }

    /// <summary>
    /// Returns the span of media an object uses, in its own clock.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_trimmed_range</c>
    /// </para>
    /// </remarks>
    public TimeRange TrimmedRange()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_trimmed_range(at.Pointer, at.Handle, out var outRange, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return TimeRange.FromNative(outRange);
    }

    /// <summary>
    /// Returns where an object sits in its parent's clock, after the parent's
    /// own trim.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Reports <c>Status.NoValue</c> when the parent's trim excludes the
    /// object entirely.
    /// </para>
    /// <para>
    /// C: <c>otio_item_trimmed_range_in_parent</c>
    /// </para>
    /// </remarks>
    public TimeRange? TrimmedRangeInParent()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_trimmed_range_in_parent(at.Pointer, at.Handle, out var outRange, out var error);
        GC.KeepAlive(at.Arena);
        if (status == Status.NoValue)
        {
            Interop.Release(error);
            return null;
        }
        Interop.Check(status, error);
        return TimeRange.FromNative(outRange);
    }

    /// <summary>
    /// Returns the span of media an object shows, including what its
    /// transitions reach into.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_item_visible_range</c>
    /// </para>
    /// </remarks>
    public TimeRange VisibleRange()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_item_visible_range(at.Pointer, at.Handle, out var outRange, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return TimeRange.FromNative(outRange);
    }
}

public partial class Marker
{
    /// <summary>
    /// Returns a marker's tint, and the name that goes with it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>out_name</c> may be null if the name is not wanted. Reports
    /// <c>Status.NoValue</c> for an untinted marker.
    /// </para>
    /// <para>
    /// C: <c>otio_marker_color</c>
    /// </para>
    /// </remarks>
    public (global::OpenTimelineIO.Color color, string name)? Color()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_marker_color(at.Pointer, at.Handle, out var outColor, out var outName, out var error);
        GC.KeepAlive(at.Arena);
        if (status == Status.NoValue)
        {
            Interop.Release(error);
            return null;
        }
        Interop.Check(status, error);
        return (global::OpenTimelineIO.Color.FromNative(outColor), Interop.Text(outName));
    }

    /// <summary>
    /// Returns a marker's note.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_marker_comment</c>
    /// </para>
    /// </remarks>
    public string Comment()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_marker_comment(at.Pointer, at.Handle, out var outComment, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.Text(outComment);
    }

    /// <summary>
    /// Returns the span a marker covers.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_marker_marked_range</c>
    /// </para>
    /// </remarks>
    public TimeRange MarkedRange()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_marker_marked_range(at.Pointer, at.Handle, out var outRange, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return TimeRange.FromNative(outRange);
    }

    /// <summary>
    /// Sets a marker's tint. <c>name</c> may be null for an unnamed colour.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_marker_set_color</c>
    /// </para>
    /// </remarks>
    public void SetColor(global::OpenTimelineIO.Color color, string? name)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cName = scratch.Utf8(name);
            var status = Native.otio_marker_set_color(at.Pointer, at.Handle, color.ToNative(), cName, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Sets a marker's note.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_marker_set_comment</c>
    /// </para>
    /// </remarks>
    public void SetComment(string comment)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cComment = scratch.Utf8(comment);
            var status = Native.otio_marker_set_comment(at.Pointer, at.Handle, cComment, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Sets the span a marker covers.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_marker_set_marked_range</c>
    /// </para>
    /// </remarks>
    public void SetMarkedRange(TimeRange range)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_marker_set_marked_range(at.Pointer, at.Handle, range.ToNative(), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }
}

public partial class MediaReference
{
    /// <summary>
    /// Returns the image bounds a reference says its media has.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Where there is nothing to report this answers null, which is an answer
    /// rather than a failure.
    /// </para>
    /// <para>
    /// C: <c>otio_media_reference_available_image_bounds</c>
    /// </para>
    /// </remarks>
    public Box2d? AvailableImageBounds()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_media_reference_available_image_bounds(at.Pointer, at.Handle, out var outBounds, out var error);
        GC.KeepAlive(at.Arena);
        if (status == Status.NoValue)
        {
            Interop.Release(error);
            return null;
        }
        Interop.Check(status, error);
        return Box2d.FromNative(outBounds);
    }

    /// <summary>
    /// Returns the span of media a reference says is available.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Reports <c>Status.NoValue</c> for a reference that does not say.
    /// </para>
    /// <para>
    /// C: <c>otio_media_reference_available_range</c>
    /// </para>
    /// </remarks>
    public TimeRange? AvailableRange()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_media_reference_available_range(at.Pointer, at.Handle, out var outRange, out var error);
        GC.KeepAlive(at.Arena);
        if (status == Status.NoValue)
        {
            Interop.Release(error);
            return null;
        }
        Interop.Check(status, error);
        return TimeRange.FromNative(outRange);
    }

    /// <summary>
    /// Clears the image bounds a reference says its media has.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_media_reference_clear_available_image_bounds</c>
    /// </para>
    /// </remarks>
    public void ClearAvailableImageBounds()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_media_reference_clear_available_image_bounds(at.Pointer, at.Handle, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Clears the span of media a reference says is available.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_media_reference_clear_available_range</c>
    /// </para>
    /// </remarks>
    public void ClearAvailableRange()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_media_reference_clear_available_range(at.Pointer, at.Handle, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Sets the image bounds a reference says its media has.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_media_reference_set_available_image_bounds</c>
    /// </para>
    /// </remarks>
    public void SetAvailableImageBounds(Box2d bounds)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_media_reference_set_available_image_bounds(at.Pointer, at.Handle, bounds.ToNative(), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Sets the span of media a reference says is available.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_media_reference_set_available_range</c>
    /// </para>
    /// </remarks>
    public void SetAvailableRange(TimeRange range)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_media_reference_set_available_range(at.Pointer, at.Handle, range.ToNative(), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }
}

public partial class SerializableObject
{
    /// <summary>
    /// Returns one of an object's children.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_node_child_at</c>
    /// </para>
    /// </remarks>
    public SerializableObject ChildAt(int index)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_node_child_at(at.Pointer, at.Handle, (nuint)index, out var outChild, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.MakeObject(at.Arena, outChild);
    }

    /// <summary>
    /// Returns how many children an object holds.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Tracks, stacks, bare compositions and serializable collections hold
    /// children; anything else reports <c>Status.CoreError</c>.
    /// </para>
    /// <para>
    /// C: <c>otio_node_child_count</c>
    /// </para>
    /// </remarks>
    public int ChildCount()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_node_child_count(at.Pointer, at.Handle, out var outCount, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return (int)outCount;
    }

    /// <summary>
    /// Returns an object's children.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_node_children</c>
    /// </para>
    /// </remarks>
    public SerializableObject[] Children()
    {
        var at = Interop.Locate(this);
        nuint count;
        var sizingStatus = Native.otio_node_children(at.Pointer, at.Handle, null, 0, out count, out var sizingError);
        Interop.Check(sizingStatus, sizingError);
        var buffer0 = new Native.OtioNode[(int)count];
        var fillingStatus = Native.otio_node_children(at.Pointer, at.Handle, buffer0, (nuint)buffer0.Length, out count, out var fillingError);
        Interop.Check(fillingStatus, fillingError);
        GC.KeepAlive(at.Arena);
        if ((int)count > buffer0.Length) { count = (nuint)buffer0.Length; }
        var buffer0Taken = new SerializableObject[(int)count];
        for (int slot = 0; slot < (int)count; slot++)
        {
            buffer0Taken[slot] = Interop.MakeObject(at.Arena, buffer0[slot]);
        }
        return buffer0Taken;
    }

    /// <summary>
    /// Returns whether two handles name the same object.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This is object identity: two handles are equal only if they were
    /// issued for the same occupant of the same slot.
    /// </para>
    /// <para>
    /// C: <c>otio_node_equal</c>
    /// </para>
    /// </remarks>
    public bool Equals(SerializableObject right)
    {
        var at = Interop.Locate(this);
        if (!Interop.Here(at, right))
        {
            return false;
        }
        var cRight = Interop.HandleOf(at, right);
        var answer = Native.otio_node_equal(at.Handle, cRight);
        GC.KeepAlive(at.Arena);
        return answer != 0;
    }

    /// <summary>
    /// Returns every clip at or below an object, in order.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_node_find_clips</c>
    /// </para>
    /// </remarks>
    public SerializableObject[] FindClips()
    {
        var at = Interop.Locate(this);
        nuint count;
        var sizingStatus = Native.otio_node_find_clips(at.Pointer, at.Handle, null, 0, out count, out var sizingError);
        Interop.Check(sizingStatus, sizingError);
        var buffer0 = new Native.OtioNode[(int)count];
        var fillingStatus = Native.otio_node_find_clips(at.Pointer, at.Handle, buffer0, (nuint)buffer0.Length, out count, out var fillingError);
        Interop.Check(fillingStatus, fillingError);
        GC.KeepAlive(at.Arena);
        if ((int)count > buffer0.Length) { count = (nuint)buffer0.Length; }
        var buffer0Taken = new SerializableObject[(int)count];
        for (int slot = 0; slot < (int)count; slot++)
        {
            buffer0Taken[slot] = Interop.MakeObject(at.Arena, buffer0[slot]);
        }
        return buffer0Taken;
    }

    /// <summary>
    /// Returns the outermost object above this one.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_node_highest_ancestor</c>
    /// </para>
    /// </remarks>
    public SerializableObject HighestAncestor()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_node_highest_ancestor(at.Pointer, at.Handle, out var outAncestor, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.MakeObject(at.Arena, outAncestor);
    }

    /// <summary>
    /// Returns whether a handle names no object.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_node_is_none</c>
    /// </para>
    /// </remarks>
    public bool IsNone()
    {
        var at = Interop.Locate(this);
        var answer = Native.otio_node_is_none(at.Handle);
        GC.KeepAlive(at.Arena);
        return answer != 0;
    }

    /// <summary>
    /// Returns what kind of object a handle names.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_node_kind</c>
    /// </para>
    /// </remarks>
    public NodeKind SchemaKind()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_node_kind(at.Pointer, at.Handle, out var outKind, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return outKind;
    }

    /// <summary>
    /// Returns an object's name, which is empty for an object that has none.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_node_name</c>
    /// </para>
    /// </remarks>
    public string Name()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_node_name(at.Pointer, at.Handle, out var outName, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.Text(outName);
    }

    /// <summary>
    /// Returns the handle that names no object.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Fields that may be absent, such as a timeline's tracks before one is
    /// set, report this. Compare against it with <c>IsNone</c>.
    /// </para>
    /// <para>
    /// C: <c>otio_node_none</c>
    /// </para>
    /// </remarks>
    public static SerializableObject None()
    {
        var answer = Native.otio_node_none();
        return Interop.MakeObject(null, answer);
    }

    /// <summary>
    /// Returns whether an object sits over its neighbours rather than beside
    /// them.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Only a transition does, which is why one does not advance the playhead
    /// when a track is laid out.
    /// </para>
    /// <para>
    /// C: <c>otio_node_overlapping</c>
    /// </para>
    /// </remarks>
    public bool Overlapping()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_node_overlapping(at.Pointer, at.Handle, out var outOverlapping, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return outOverlapping != 0;
    }

    /// <summary>
    /// Returns the composition an object sits in.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Reports <c>Status.NoValue</c> for an object that is in none, which is
    /// what a freshly created one is.
    /// </para>
    /// <para>
    /// C: <c>otio_node_parent</c>
    /// </para>
    /// </remarks>
    public SerializableObject? Parent()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_node_parent(at.Pointer, at.Handle, out var outParent, out var error);
        GC.KeepAlive(at.Arena);
        if (status == Status.NoValue)
        {
            Interop.Release(error);
            return null;
        }
        Interop.Check(status, error);
        return Interop.MakeObject(at.Arena, outParent);
    }

    /// <summary>
    /// Returns the schema name an object serializes as, such as
    /// <c>"Clip"</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_node_schema_name</c>
    /// </para>
    /// </remarks>
    public string SchemaName()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_node_schema_name(at.Pointer, at.Handle, out var outName, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.Text(outName);
    }

    /// <summary>
    /// Returns the schema version an object serializes as.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_node_schema_version</c>
    /// </para>
    /// </remarks>
    public uint SchemaVersion()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_node_schema_version(at.Pointer, at.Handle, out var outVersion, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return outVersion;
    }

    /// <summary>
    /// Sets an object's name.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_node_set_name</c>
    /// </para>
    /// </remarks>
    public void SetName(string name)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cName = scratch.Utf8(name);
            var status = Native.otio_node_set_name(at.Pointer, at.Handle, cName, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Writes one object of a document as OTIO JSON.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Upstream's <c>write_to_string</c> takes any object, not only a
    /// timeline, so this does too.
    /// </para>
    /// <para>
    /// C: <c>otio_node_to_json</c>
    /// </para>
    /// </remarks>
    public string ToJson(int indent)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_node_to_json(at.Pointer, at.Handle, (nuint)indent, out var outJSON, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.Text(outJSON);
    }

    /// <summary>
    /// Restates an instant from one object's clock in another's.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_node_transformed_time</c>
    /// </para>
    /// </remarks>
    public RationalTime TransformedTime(RationalTime time, SerializableObject to)
    {
        var at = Interop.Locate(this);
        var cTo = Interop.RequireHere(at, to);
        var status = Native.otio_node_transformed_time(at.Pointer, time.ToNative(), at.Handle, cTo, out var outTime, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return RationalTime.FromNative(outTime);
    }

    /// <summary>
    /// Restates a span from one object's clock in another's.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_node_transformed_time_range</c>
    /// </para>
    /// </remarks>
    public TimeRange TransformedTimeRange(TimeRange range, SerializableObject to)
    {
        var at = Interop.Locate(this);
        var cTo = Interop.RequireHere(at, to);
        var status = Native.otio_node_transformed_time_range(at.Pointer, range.ToNative(), at.Handle, cTo, out var outRange, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return TimeRange.FromNative(outRange);
    }

    /// <summary>
    /// Returns whether an object covers what is beneath it when its
    /// composition is flattened.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_node_visible</c>
    /// </para>
    /// </remarks>
    public bool Visible()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_node_visible(at.Pointer, at.Handle, out var outVisible, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return outVisible != 0;
    }
}

public partial class Timeline
{
    /// <summary>
    /// Clears where a timeline begins.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_timeline_clear_global_start_time</c>
    /// </para>
    /// </remarks>
    public void ClearGlobalStartTime()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_timeline_clear_global_start_time(at.Pointer, at.Handle, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Returns where a timeline begins, such as <c>01:00:00:00</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Reports <c>Status.NoValue</c> for a timeline that does not say.
    /// </para>
    /// <para>
    /// C: <c>otio_timeline_global_start_time</c>
    /// </para>
    /// </remarks>
    public RationalTime? GlobalStartTime()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_timeline_global_start_time(at.Pointer, at.Handle, out var outTime, out var error);
        GC.KeepAlive(at.Arena);
        if (status == Status.NoValue)
        {
            Interop.Release(error);
            return null;
        }
        Interop.Check(status, error);
        return RationalTime.FromNative(outTime);
    }

    /// <summary>
    /// Sets where a timeline begins.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_timeline_set_global_start_time</c>
    /// </para>
    /// </remarks>
    public void SetGlobalStartTime(RationalTime time)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_timeline_set_global_start_time(at.Pointer, at.Handle, time.ToNative(), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Sets the stack holding a timeline's tracks.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The stack's parent is set to the timeline, as upstream's does.
    /// </para>
    /// <para>
    /// Passing <c>None</c> puts a fresh empty stack there rather than
    /// nothing, because that is what upstream's setter does: its own
    /// <c>test_timeline.py</c> sets <c>tracks</c> to <c>None</c> and then
    /// asserts that <c>tl.tracks</c> is still a <c>Stack</c>. A timeline with
    /// no tracks at all is not a thing a caller can reach through upstream's
    /// API, so it is not one they can reach through this one.
    /// </para>
    /// <para>
    /// Whatever stack was there is not destroyed. It stays in the document,
    /// parentless, so it can be put somewhere else; dropping it is a separate
    /// <c>RemoveFromTimeline</c> call. That is the same bargain
    /// <c>DetachChild</c> makes, and leaving its parent pointing at the
    /// timeline instead would mean an object claiming a parent that has
    /// disowned it. A displaced stack that some other timeline has since
    /// taken as its own keeps that timeline as its parent, since this one is
    /// not the timeline disowning it.
    /// </para>
    /// <para>
    /// A null tracks means none.
    /// </para>
    /// <para>
    /// C: <c>otio_timeline_set_tracks</c>
    /// </para>
    /// </remarks>
    public void SetTracks(SerializableObject? tracks)
    {
        var at = Interop.Locate(this);
        var cTracks = Interop.Adopt(at, tracks);
        var status = Native.otio_timeline_set_tracks(at.Pointer, at.Handle, cTracks, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Returns the stack holding a timeline's tracks.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Reports <c>Status.NoValue</c> for a timeline that has none.
    /// </para>
    /// <para>
    /// C: <c>otio_timeline_tracks</c>
    /// </para>
    /// </remarks>
    public SerializableObject? Tracks()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_timeline_tracks(at.Pointer, at.Handle, out var outTracks, out var error);
        GC.KeepAlive(at.Arena);
        if (status == Status.NoValue)
        {
            Interop.Release(error);
            return null;
        }
        Interop.Check(status, error);
        return Interop.MakeObject(at.Arena, outTracks);
    }
}

public partial class Track
{
    /// <summary>
    /// Returns what a track carries, such as <c>"Video"</c> or
    /// <c>"Audio"</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_track_kind</c>
    /// </para>
    /// </remarks>
    public string Kind()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_track_kind(at.Pointer, at.Handle, out var outKind, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.Text(outKind);
    }

    /// <summary>
    /// Sets what a track carries.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_track_set_kind</c>
    /// </para>
    /// </remarks>
    public void SetKind(string kind)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cKind = scratch.Utf8(kind);
            var status = Native.otio_track_set_kind(at.Pointer, at.Handle, cKind, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }
}

public partial class Transition
{
    /// <summary>
    /// Returns whether a transition is applied.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_transition_enabled</c>
    /// </para>
    /// </remarks>
    public bool Enabled()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_transition_enabled(at.Pointer, at.Handle, out var outEnabled, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return outEnabled != 0;
    }

    /// <summary>
    /// Returns how far a transition reaches into the item before it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_transition_in_offset</c>
    /// </para>
    /// </remarks>
    public RationalTime InOffset()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_transition_in_offset(at.Pointer, at.Handle, out var outOffset, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return RationalTime.FromNative(outOffset);
    }

    /// <summary>
    /// Returns how far a transition reaches into the item after it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_transition_out_offset</c>
    /// </para>
    /// </remarks>
    public RationalTime OutOffset()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_transition_out_offset(at.Pointer, at.Handle, out var outOffset, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return RationalTime.FromNative(outOffset);
    }

    /// <summary>
    /// Sets whether a transition is applied.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_transition_set_enabled</c>
    /// </para>
    /// </remarks>
    public void SetEnabled(bool enabled)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_transition_set_enabled(at.Pointer, at.Handle, (enabled ? (byte)1 : (byte)0), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Sets how far a transition reaches into the item before it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_transition_set_in_offset</c>
    /// </para>
    /// </remarks>
    public void SetInOffset(RationalTime offset)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_transition_set_in_offset(at.Pointer, at.Handle, offset.ToNative(), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Sets how far a transition reaches into the item after it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_transition_set_out_offset</c>
    /// </para>
    /// </remarks>
    public void SetOutOffset(RationalTime offset)
    {
        var at = Interop.Locate(this);
        var status = Native.otio_transition_set_out_offset(at.Pointer, at.Handle, offset.ToNative(), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Sets the kind of transition.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_transition_set_type</c>
    /// </para>
    /// </remarks>
    public void SetType(string transitionType)
    {
        var at = Interop.Locate(this);
        var scratch = new Interop.Scratch();
        try
        {
            var cTransitionType = scratch.Utf8(transitionType);
            var status = Native.otio_transition_set_type(at.Pointer, at.Handle, cTransitionType, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Returns the kind of transition, such as <c>"SMPTE_Dissolve"</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_transition_type</c>
    /// </para>
    /// </remarks>
    public string Type()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_transition_type(at.Pointer, at.Handle, out var outType, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.Text(outType);
    }
}
