// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace OpenTimelineIO;

/// <summary>A failure the library reported.</summary>
/// <remarks>
/// <para>
/// Where "there is nothing here" is one of the answers — an item with no
/// source range, a clip with no active media reference — the call answers
/// null instead of throwing, because that is an answer rather than a failure.
/// </para>
/// </remarks>
public class OtioException : Exception
{
    /// <summary>Makes one from what the library said.</summary>
    public OtioException(Status status, string message)
        : base(string.IsNullOrEmpty(message) ? status.CName() : message)
    {
        this.Status = status;
    }

    /// <summary>What kind of failure it was.</summary>
    public Status Status { get; }
}

/// <summary>The refusal of an object that belongs to another timeline.</summary>
/// <remarks>
/// <para>
/// A call that only names an object — asking whether a track holds it,
/// detaching it, flattening a list of tracks — refuses one from elsewhere
/// before the library is asked, so nothing has moved when this is thrown. Its
/// status is <c>Status.InvalidArgument</c>, so code that reads the status
/// reads what it always did; catching this type is what tells this SDK's own
/// refusal apart from the library's, which is the difference between "nothing
/// was touched" and "the library looked and said no".
/// </para>
/// </remarks>
public sealed class OtherTimelineException : OtioException
{
    /// <summary>Makes one, saying what was refused.</summary>
    internal OtherTimelineException(string message)
        : base(Status.InvalidArgument, message)
    {
    }
}

/// <summary>The arena the core keeps a timeline's objects in.</summary>
/// <remarks>
/// <para>
/// It is not part of this SDK's surface. An object carries the arena it lives
/// in, a new object starts in one of its own, and putting an object into a
/// timeline moves it into the timeline's — so what a caller is left holding is
/// objects. The arena goes when the last object naming it does, or earlier if
/// somebody says Close.
/// </para>
/// </remarks>
internal sealed class Arena
{
    private IntPtr pointer;

    internal Arena(IntPtr pointer)
    {
        this.pointer = pointer;
    }

    /// <summary>Releases the arena if nobody released it first.</summary>
    ~Arena()
    {
        this.Release();
    }

    /// <summary>
    /// The arena the C interface knows, or zero once it is closed or its
    /// objects have moved elsewhere.
    /// </summary>
    internal IntPtr Pointer => this.pointer;

    /// <summary>Where this arena's objects went, once another absorbed them.</summary>
    internal Arena? MovedInto { get; set; }

    /// <summary>What each of this arena's handles became on the way over.</summary>
    internal Dictionary<ulong, Native.OtioNode> Translation { get; } = new();

    /// <summary>
    /// Records what the library left in the slot it was handed, so that an
    /// arena it took over and freed is not freed a second time.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A call that failed leaves the arena where it was, and this says so too:
    /// the finalizer is only let go once there is nothing left to free.
    /// </para>
    /// </remarks>
    internal void Taken(IntPtr left)
    {
        this.pointer = left;
        if (left == IntPtr.Zero)
        {
            GC.SuppressFinalize(this);
        }
    }

    /// <summary>Releases the arena and everything in it.</summary>
    /// <remarks>
    /// <para>
    /// Closing twice is harmless, and every object that lived here fails
    /// afterwards rather than reading freed memory: the pointer is zeroed, and
    /// the C interface refuses a null document.
    /// </para>
    /// </remarks>
    internal void Close()
    {
        this.Release();
        GC.SuppressFinalize(this);
    }

    private void Release()
    {
        if (this.pointer != IntPtr.Zero)
        {
            Native.otio_document_free(this.pointer);
            this.pointer = IntPtr.Zero;
        }
    }
}

/// <summary>
/// An object resolved: the arena holding it now, that arena's document, and
/// the handle it answers to there.
/// </summary>
internal readonly struct Site
{
    internal Site(Arena? arena, Native.OtioNode handle)
    {
        this.Arena = arena;
        this.Handle = handle;
    }

    /// <summary>The arena, for keeping it alive across the call.</summary>
    internal Arena? Arena { get; }

    /// <summary>The handle the object answers to in that arena.</summary>
    internal Native.OtioNode Handle { get; }

    /// <summary>The document the C interface knows, or zero once it has gone.</summary>
    internal IntPtr Pointer => this.Arena?.Pointer ?? IntPtr.Zero;
}

/// <summary>An object in a timeline: a clip, a track, a timeline, a marker.</summary>
/// <remarks>
/// <para>
/// Objects are built on their own and put together afterwards:
/// </para>
/// <code>
/// var track = new Track("V1", "Video");
/// var clip = new Clip("shot_01");
/// track.AppendChild(clip);
/// </code>
/// <para>
/// Behind that, the core keeps its objects in arenas and an object is an index
/// into one. This SDK does that bookkeeping: a new object gets an arena of its
/// own, and putting it into a timeline moves it into the timeline's. An object
/// holds the arena it lives in, so the timeline lasts as long as anything
/// naming it, and Close ends it sooner where the moment matters. An object of a
/// closed timeline names nothing and every call on it fails rather than reading
/// freed memory.
/// </para>
/// <para>
/// It is the root of the OTIO schema ladder, and every schema below it is a
/// class deriving from it, so a Clip has every member of an Item, a Composable
/// and a SerializableObjectWithMetadata. Every handle the library hands back
/// arrives as the class its schema names, so <c>node as Clip</c> asks what an
/// object really is and gets a true answer.
/// </para>
/// <para>
/// Two objects are equal when they are the same object of the same timeline. A
/// handle is a value here, so there may be several wrappers for one object and
/// equality is the question worth asking.
/// </para>
/// </remarks>
public partial class SerializableObject
{
    internal SerializableObject(Arena? arena, Native.OtioNode handle)
    {
        this.Arena = arena;
        this.Handle = handle;
    }

    /// <summary>What a constructor built, as its base receives it.</summary>
    internal SerializableObject(Site made)
        : this(made.Arena, made.Handle)
    {
    }

    /// <summary>
    /// The arena the object was issued in. This is the plumbing: Interop.Locate
    /// follows it to wherever its objects are now.
    /// </summary>
    internal Arena? Arena { get; }

    /// <summary>The handle the object is, in the arena that issued it.</summary>
    internal Native.OtioNode Handle { get; }

    /// <summary>Releases the timeline this object belongs to, and everything in it.</summary>
    /// <remarks>
    /// <para>
    /// Not required: the timeline goes when the last object naming it does.
    /// This is for code that would rather say when — a viewer opening one file
    /// after another, say. Closing twice is harmless, and every object that
    /// lived in the timeline fails afterwards.
    /// </para>
    /// </remarks>
    public void Close() => Interop.Locate(this).Arena?.Close();

    /// <summary>Whether the object is of a schema, or of one deriving from it.</summary>
    /// <remarks>
    /// <para>
    /// An object whose timeline has gone, or whose handle no longer resolves,
    /// is of no schema at all, so this answers false rather than guessing.
    /// </para>
    /// </remarks>
    public bool IsA(NodeKind schema)
    {
        var at = Interop.Locate(this);
        if (at.Pointer == IntPtr.Zero)
        {
            return false;
        }
        var status = Native.otio_node_kind(at.Pointer, at.Handle, out var kind, out var error);
        GC.KeepAlive(at.Arena);
        // Not being able to say is answered with false, so the message is only
        // released.
        Interop.Release(error);
        if (status != Status.Ok)
        {
            return false;
        }
        while (true)
        {
            if (kind == schema)
            {
                return true;
            }
            if (!Schemas.Parents.TryGetValue(kind, out var parent))
            {
                return false;
            }
            kind = parent;
        }
    }

    /// <summary>Whether another object is the same object of the same timeline.</summary>
    /// <remarks>
    /// <para>
    /// The library's own <c>Equals(SerializableObject)</c>, generated from
    /// <c>otio_node_equal</c>, asks the same question and gets the same answer;
    /// this one is here because the runtime needs it, and it answers without a
    /// call so that it still works once the timeline has gone.
    /// </para>
    /// </remarks>
    public override bool Equals(object? other)
    {
        if (other is not SerializableObject node)
        {
            return false;
        }
        var mine = Interop.Locate(this);
        var theirs = Interop.Locate(node);
        return ReferenceEquals(mine.Arena, theirs.Arena)
            && mine.Handle.index == theirs.Handle.index
            && mine.Handle.generation == theirs.Handle.generation;
    }

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        var mine = Interop.Locate(this);
        return HashCode.Combine(mine.Arena, mine.Handle.index, mine.Handle.generation);
    }

    /// <summary>Whether two wrappers name the same object of the same timeline.</summary>
    public static bool operator ==(SerializableObject? left, SerializableObject? right) =>
        left is null ? right is null : left.Equals((object?)right);

    /// <summary>Whether two wrappers name different objects.</summary>
    public static bool operator !=(SerializableObject? left, SerializableObject? right) =>
        !(left == right);
}

/// <summary>Everything the library offers that belongs to no object.</summary>
public static partial class Otio
{
    /// <summary>Reads a timeline from a file, working out its format from the name.</summary>
    /// <remarks>
    /// <para>
    /// It is the short way to say ReadFromFile when the suffix already says
    /// what the file holds, which is how upstream's read_from_file behaves when
    /// no adapter is named.
    /// </para>
    /// </remarks>
    public static SerializableObject Open(string path) =>
        Otio.ReadFromFile(Interop.FormatOf(path), path, null);

    /// <summary>Writes a timeline to a file, working out its format from the name.</summary>
    /// <remarks>
    /// <para>
    /// It is the short way to say WriteToFile, as Open is for ReadFromFile.
    /// Writing starts at the object it is given, so handing it a track writes
    /// that track rather than the timeline around it.
    /// </para>
    /// </remarks>
    public static void Save(SerializableObject root, string path) =>
        Otio.WriteToFile(Interop.FormatOf(path), root, path, null);
}

public static partial class Otio
{
    /// <summary>
    /// Returns the format that claims a filename suffix, such as
    /// <c>"edl"</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The suffix is matched without its dot and without regard to case.
    /// Reports <c>Status.NoValue</c> for a suffix no format claims.
    /// </para>
    /// <para>
    /// C: <c>otio_format_from_suffix</c>
    /// </para>
    /// </remarks>
    public static Format? FormatFromSuffix(string suffix)
    {
        var scratch = new Interop.Scratch();
        try
        {
            var cSuffix = scratch.Utf8(suffix);
            var status = Native.otio_format_from_suffix(cSuffix, out var outFormat, out var error);
            if (status == Status.NoValue)
            {
                Interop.Release(error);
                return null;
            }
            Interop.Check(status, error);
            return outFormat;
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// The tolerance, in seconds, that the range predicates use by default.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Upstream's C++ takes this as a default argument; C has none, so the
    /// value is a call rather than a constant in the header, which keeps the
    /// two from drifting apart.
    /// </para>
    /// <para>
    /// C: <c>otio_default_epsilon_s</c>
    /// </para>
    /// </remarks>
    public static double DefaultEpsilonS()
    {
        var answer = Native.otio_default_epsilon_s();
        return answer;
    }

    /// <summary>
    /// Returns the indentation upstream's Python bindings write by default.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_default_indent</c>
    /// </para>
    /// </remarks>
    public static int DefaultIndent()
    {
        var answer = Native.otio_default_indent();
        return (int)answer;
    }

    /// <summary>
    /// Returns the library's version, as <c>"MAJOR.MINOR.PATCH"</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The string is static and needs no freeing.
    /// </para>
    /// <para>
    /// C: <c>otio_version</c>
    /// </para>
    /// </remarks>
    public static string Version()
    {
        var answer = Native.otio_version();
        return Interop.StaticText(answer);
    }

    /// <summary>
    /// Returns whether a rate is a drop-frame rate.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_is_drop_frame_rate</c>
    /// </para>
    /// </remarks>
    public static bool IsDropFrameRate(double rate)
    {
        var answer = Native.otio_is_drop_frame_rate(rate);
        return answer != 0;
    }

    /// <summary>
    /// Returns whether a rate is one SMPTE timecode is defined for.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_is_smpte_timecode_rate</c>
    /// </para>
    /// </remarks>
    public static bool IsSmpteTimecodeRate(double rate)
    {
        var answer = Native.otio_is_smpte_timecode_rate(rate);
        return answer != 0;
    }

    /// <summary>
    /// Returns the SMPTE timecode rate closest to a rate.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_nearest_smpte_timecode_rate</c>
    /// </para>
    /// </remarks>
    public static double NearestSmpteTimecodeRate(double rate)
    {
        var answer = Native.otio_nearest_smpte_timecode_rate(rate);
        return answer;
    }

    /// <summary>
    /// Reads a document from the bytes of a file in some format.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>options</c> may be null for the format's usual behaviour.
    /// </para>
    /// <para>
    /// C: <c>otio_read_from_bytes</c>
    /// </para>
    /// </remarks>
    public static SerializableObject ReadFromBytes(Format format, byte[] data, ReadOptions? options)
    {
        var scratch = new Interop.Scratch();
        try
        {
            var cOptions = options is null ? IntPtr.Zero : scratch.Struct(options.Value.ToNative(scratch));
            var status = Native.otio_read_from_bytes(format, data, (nuint)data.Length, cOptions, out var outDocument, out var error);
            Interop.Check(status, error);
            return Interop.RootOf(outDocument);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Reads a document from a file on disk in some format.
    /// </summary>
    /// <remarks>
    /// <para>
    /// An AAF is read where it lies, seeking around the file, rather than
    /// copied into memory first.
    /// </para>
    /// <para>
    /// A null options means none.
    /// </para>
    /// <para>
    /// C: <c>otio_read_from_file</c>
    /// </para>
    /// </remarks>
    public static SerializableObject ReadFromFile(Format format, string path, ReadOptions? options)
    {
        var scratch = new Interop.Scratch();
        try
        {
            var cPath = scratch.Utf8(path);
            var cOptions = options is null ? IntPtr.Zero : scratch.Struct(options.Value.ToNative(scratch));
            var status = Native.otio_read_from_file(format, cPath, cOptions, out var outDocument, out var error);
            Interop.Check(status, error);
            return Interop.RootOf(outDocument);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Returns the defaults, for a caller that wants to change one field.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_read_options_default</c>
    /// </para>
    /// </remarks>
    public static ReadOptions ReadOptionsDefault()
    {
        var answer = Native.otio_read_options_default();
        return ReadOptions.FromNative(answer);
    }

    /// <summary>
    /// Returns the defaults, for a caller that wants to change one field.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_write_options_default</c>
    /// </para>
    /// </remarks>
    public static WriteOptions WriteOptionsDefault()
    {
        var answer = Native.otio_write_options_default();
        return WriteOptions.FromNative(answer);
    }

    /// <summary>
    /// Writes a document as the bytes of a file in some format.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The buffer is NUL-terminated, so a text format's output can be used as
    /// a C string; <c>len</c> is what matters for a binary one.
    /// </para>
    /// <para>
    /// A null options means none.
    /// </para>
    /// <para>
    /// C: <c>otio_write_to_bytes</c>
    /// </para>
    /// </remarks>
    public static byte[] WriteToBytes(Format format, SerializableObject root, WriteOptions? options)
    {
        var at = Interop.RootedAt(root);
        var scratch = new Interop.Scratch();
        try
        {
            var cOptions = options is null ? IntPtr.Zero : scratch.Struct(options.Value.ToNative(scratch));
            var status = Native.otio_write_to_bytes(format, at.Pointer, cOptions, out var outBytes, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
            return Interop.Bytes(outBytes);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Writes a document to a file on disk in some format.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A null options means none.
    /// </para>
    /// <para>
    /// C: <c>otio_write_to_file</c>
    /// </para>
    /// </remarks>
    public static void WriteToFile(Format format, SerializableObject root, string path, WriteOptions? options)
    {
        var at = Interop.RootedAt(root);
        var scratch = new Interop.Scratch();
        try
        {
            var cPath = scratch.Utf8(path);
            var cOptions = options is null ? IntPtr.Zero : scratch.Struct(options.Value.ToNative(scratch));
            var status = Native.otio_write_to_file(format, at.Pointer, cPath, cOptions, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Collapses a stack's tracks into one, top layer winning where it is
    /// visible.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_algorithm_flatten_stack</c>
    /// </para>
    /// </remarks>
    public static SerializableObject FlattenStack(SerializableObject stack)
    {
        var at = Interop.Locate(stack);
        var cStack = Interop.RequireHere(at, stack);
        var status = Native.otio_algorithm_flatten_stack(at.Pointer, cStack, out var outTrack, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.MakeObject(at.Arena, outTrack);
    }

    /// <summary>
    /// Collapses a list of tracks into one, lowest first.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A null tracks means none.
    /// </para>
    /// <para>
    /// C: <c>otio_algorithm_flatten_tracks</c>
    /// </para>
    /// </remarks>
    public static SerializableObject FlattenTracks(SerializableObject[] tracks)
    {
        var at = Interop.LocateAll(tracks);
        var cTracks = Interop.RequireHereAll(at, tracks);
        var status = Native.otio_algorithm_flatten_tracks(at.Pointer, cTracks, (nuint)tracks.Length, out var outTrack, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.MakeObject(at.Arena, outTrack);
    }

    /// <summary>
    /// Returns a copy of a track holding only what falls inside a span.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The copy is added to the same document and has no parent.
    /// </para>
    /// <para>
    /// C: <c>otio_algorithm_track_trimmed_to_range</c>
    /// </para>
    /// </remarks>
    public static SerializableObject TrackTrimmedToRange(SerializableObject track, TimeRange trimRange)
    {
        var at = Interop.Locate(track);
        var cTrack = Interop.RequireHere(at, track);
        var status = Native.otio_algorithm_track_trimmed_to_range(at.Pointer, cTrack, trimRange.ToNative(), out var outTrack, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.MakeObject(at.Arena, outTrack);
    }

    /// <summary>
    /// Reads a document from OTIO JSON.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_document_from_json</c>
    /// </para>
    /// </remarks>
    public static SerializableObject FromJson(string json)
    {
        var scratch = new Interop.Scratch();
        try
        {
            var cJSON = scratch.Utf8(json);
            var status = Native.otio_document_from_json(cJSON, out var outDocument, out var error);
            Interop.Check(status, error);
            return Interop.RootOf(outDocument);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Reads a document from a <c>.otio</c> file on disk.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_document_read_from_file</c>
    /// </para>
    /// </remarks>
    public static SerializableObject ReadOtioFile(string path)
    {
        var scratch = new Interop.Scratch();
        try
        {
            var cPath = scratch.Utf8(path);
            var status = Native.otio_document_read_from_file(cPath, out var outDocument, out var error);
            Interop.Check(status, error);
            return Interop.RootOf(outDocument);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Writes a document to a <c>.otio</c> file on disk.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_document_write_to_file</c>
    /// </para>
    /// </remarks>
    public static void WriteOtioFile(SerializableObject root, string path, int indent)
    {
        var at = Interop.RootedAt(root);
        var scratch = new Interop.Scratch();
        try
        {
            var cPath = scratch.Utf8(path);
            var status = Native.otio_document_write_to_file(at.Pointer, cPath, (nuint)indent, out var error);
            GC.KeepAlive(at.Arena);
            Interop.Check(status, error);
        }
        finally
        {
            scratch.Dispose();
        }
    }

    /// <summary>
    /// Drops an item into a gap on a track, fitting it as the reference point
    /// says.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_edit_fill</c>
    /// </para>
    /// </remarks>
    public static void Fill(SerializableObject item, SerializableObject track, RationalTime trackTime, ReferencePoint referencePoint)
    {
        var at = Interop.Locate(track);
        var cItem = Interop.Adopt(at, item);
        var cTrack = Interop.RequireHere(at, track);
        var status = Native.otio_edit_fill(at.Pointer, cItem, cTrack, trackTime.ToNative(), referencePoint, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Inserts an item at an instant, pushing what follows later.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A null fillTemplate means none.
    /// </para>
    /// <para>
    /// C: <c>otio_edit_insert</c>
    /// </para>
    /// </remarks>
    public static void Insert(SerializableObject item, SerializableObject composition, RationalTime time, bool removeTransitions, SerializableObject? fillTemplate)
    {
        var at = Interop.Locate(composition);
        var cItem = Interop.AdoptOrphan(at, item);
        var cComposition = Interop.RequireHere(at, composition);
        var cFillTemplate = Interop.Adopt(at, fillTemplate);
        var status = Native.otio_edit_insert(at.Pointer, cItem, cComposition, time.ToNative(), (removeTransitions ? (byte)1 : (byte)0), cFillTemplate, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Lays an item over a span of a composition, replacing what was there.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>fill_template</c> is the item to fill any gap the edit opens with,
    /// or <c>None</c> for a plain gap.
    /// </para>
    /// <para>
    /// A null fillTemplate means none.
    /// </para>
    /// <para>
    /// C: <c>otio_edit_overwrite</c>
    /// </para>
    /// </remarks>
    public static void Overwrite(SerializableObject item, SerializableObject composition, TimeRange range, bool removeTransitions, SerializableObject? fillTemplate)
    {
        var at = Interop.Locate(composition);
        var cItem = Interop.AdoptOrphan(at, item);
        var cComposition = Interop.RequireHere(at, composition);
        var cFillTemplate = Interop.Adopt(at, fillTemplate);
        var status = Native.otio_edit_overwrite(at.Pointer, cItem, cComposition, range.ToNative(), (removeTransitions ? (byte)1 : (byte)0), cFillTemplate, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Takes whatever sits at an instant out of a composition.
    /// </summary>
    /// <remarks>
    /// <para>
    /// With <c>fill</c> set, a gap takes its place; without, what follows
    /// moves up.
    /// </para>
    /// <para>
    /// A null fillTemplate means none.
    /// </para>
    /// <para>
    /// C: <c>otio_edit_remove</c>
    /// </para>
    /// </remarks>
    public static void Remove(SerializableObject composition, RationalTime time, bool fill, SerializableObject? fillTemplate)
    {
        var at = Interop.Locate(composition);
        var cComposition = Interop.RequireHere(at, composition);
        var cFillTemplate = Interop.Adopt(at, fillTemplate);
        var status = Native.otio_edit_remove(at.Pointer, cComposition, time.ToNative(), (fill ? (byte)1 : (byte)0), cFillTemplate, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Moves an item's in and out points, sliding everything after it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_edit_ripple</c>
    /// </para>
    /// </remarks>
    public static void Ripple(SerializableObject item, RationalTime deltaIn, RationalTime deltaOut)
    {
        var at = Interop.Locate(item);
        var cItem = Interop.RequireHere(at, item);
        var status = Native.otio_edit_ripple(at.Pointer, cItem, deltaIn.ToNative(), deltaOut.ToNative(), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Moves the cut between an item and its neighbour.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_edit_roll</c>
    /// </para>
    /// </remarks>
    public static void Roll(SerializableObject item, RationalTime deltaIn, RationalTime deltaOut)
    {
        var at = Interop.Locate(item);
        var cItem = Interop.RequireHere(at, item);
        var status = Native.otio_edit_roll(at.Pointer, cItem, deltaIn.ToNative(), deltaOut.ToNative(), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Cuts whatever sits at an instant into two.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_edit_slice</c>
    /// </para>
    /// </remarks>
    public static void Slice(SerializableObject composition, RationalTime time, bool removeTransitions)
    {
        var at = Interop.Locate(composition);
        var cComposition = Interop.RequireHere(at, composition);
        var status = Native.otio_edit_slice(at.Pointer, cComposition, time.ToNative(), (removeTransitions ? (byte)1 : (byte)0), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Moves an item along its track, taking the time from its neighbours.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_edit_slide</c>
    /// </para>
    /// </remarks>
    public static void Slide(SerializableObject item, RationalTime delta)
    {
        var at = Interop.Locate(item);
        var cItem = Interop.RequireHere(at, item);
        var status = Native.otio_edit_slide(at.Pointer, cItem, delta.ToNative(), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Moves the media inside an item without moving the item.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_edit_slip</c>
    /// </para>
    /// </remarks>
    public static void Slip(SerializableObject item, RationalTime delta)
    {
        var at = Interop.Locate(item);
        var cItem = Interop.RequireHere(at, item);
        var status = Native.otio_edit_slip(at.Pointer, cItem, delta.ToNative(), out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Moves an item's in and out points without moving its neighbours.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A null fillTemplate means none.
    /// </para>
    /// <para>
    /// C: <c>otio_edit_trim</c>
    /// </para>
    /// </remarks>
    public static void Trim(SerializableObject item, RationalTime deltaIn, RationalTime deltaOut, SerializableObject? fillTemplate)
    {
        var at = Interop.Locate(item);
        var cItem = Interop.RequireHere(at, item);
        var cFillTemplate = Interop.Adopt(at, fillTemplate);
        var status = Native.otio_edit_trim(at.Pointer, cItem, deltaIn.ToNative(), deltaOut.ToNative(), cFillTemplate, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }
}

public partial class SerializableObject
{
    /// <summary>
    /// Returns whether a handle still names a live object.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_document_contains</c>
    /// </para>
    /// </remarks>
    public bool IsLive()
    {
        var at = Interop.Locate(this);
        var answer = Native.otio_document_contains(at.Pointer, at.Handle);
        GC.KeepAlive(at.Arena);
        return answer != 0;
    }

    /// <summary>
    /// Copies an object and everything it owns, into the same document.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The copy has no parent, whatever the original had.
    /// </para>
    /// <para>
    /// C: <c>otio_document_deep_clone</c>
    /// </para>
    /// </remarks>
    public SerializableObject DeepClone()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_document_deep_clone(at.Pointer, at.Handle, out var outNode, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
        return Interop.MakeObject(at.Arena, outNode);
    }

    /// <summary>
    /// Removes one object from the document.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Anything that referred to it still holds a handle, and that handle is
    /// now stale: a lookup fails rather than reaching whatever takes the slot
    /// next. To remove an object together with everything hanging off it, use
    /// [<c>RemoveFromTimelineRecursive</c>].
    /// </para>
    /// <para>
    /// C: <c>otio_document_remove</c>
    /// </para>
    /// </remarks>
    public void RemoveFromTimeline()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_document_remove(at.Pointer, at.Handle, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }

    /// <summary>
    /// Removes an object and everything it owns: children, markers, effects
    /// and media references.
    /// </summary>
    /// <remarks>
    /// <para>
    /// C: <c>otio_document_remove_recursive</c>
    /// </para>
    /// </remarks>
    public void RemoveFromTimelineRecursive()
    {
        var at = Interop.Locate(this);
        var status = Native.otio_document_remove_recursive(at.Pointer, at.Handle, out var error);
        GC.KeepAlive(at.Arena);
        Interop.Check(status, error);
    }
}
