// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

#import "OpenTimelineIO/OTIOPlugins.h"

#import <otio.h>
#include <string.h>

#import "OTIOPrivate.h"

/// Copies a message into the room the library gave for it.
///
/// It is cut short where it does not fit, never halfway through a character,
/// and always ends in a NUL.
static void OTIOSay(char *message, size_t capacity, NSString *text) {
    if (message == NULL || capacity == 0) {
        return;
    }
    const char *bytes = text.UTF8String;
    if (bytes == NULL) {
        bytes = "";
    }
    size_t length = strlen(bytes);
    if (length > capacity - 1) {
        length = capacity - 1;
        while (length > 0 && ((unsigned char)bytes[length] & 0xC0) == 0x80) {
            length -= 1;
        }
    }
    memcpy(message, bytes, length);
    message[length] = '\0';
}

/// What a plugin's failure says, in its own words where it gave any.
static NSString *OTIOReason(NSError *_Nullable error) {
    NSString *text = error.localizedDescription;
    return text.length > 0 ? text : @"it failed and gave no reason";
}

/// Calls the plugin, and answers why it failed or nil where it did not.
///
/// What it answers is brought into the lent arena, which is where the library
/// looks for it, and its handle there written to `outResult`.
static NSString *_Nullable OTIOAsk(
    BOOL linking, id plugin, OTIOArena *lent, OtioNode target, OtioNode arguments,
    OtioNode *outResult) {
    OTIOMetadata *held = OTIO_AUTORELEASE(
        [[OTIOMetadata alloc] initWithObject:OTIOMakeObject(lent, arguments)]);
    OTIOSerializableObject *handed = OTIOMakeObject(lent, target);
    NSError *error = nil;
    OTIOSerializableObject *answer = nil;
    if (linking) {
        if (![handed isKindOfClass:[OTIOClip class]]) {
            return @"otio: a media linker was handed something that is not a clip";
        }
        answer = [(id<OTIOMediaLinker>)plugin linkMediaReferenceForClip:(OTIOClip *)handed
                                                              arguments:held
                                                                  error:&error];
        if (answer == nil) {
            // Nothing, and no failure, leaves the clip as it is.
            return error == nil ? nil : OTIOReason(error);
        }
    } else {
        answer = [(id<OTIOHookScript>)plugin runHookOnObject:handed arguments:held error:&error];
        if (answer == nil) {
            return error == nil ? @"it returned no object to go on with" : OTIOReason(error);
        }
    }
    // An object the hook's caller already held names the lent document
    // through the caller's own arena, and is there already.
    OtioNode handle;
    OTIOArena *theirs = OTIOLocate(answer, &handle);
    if (theirs != nil && theirs != lent && theirs.pointer == lent.pointer) {
        *outResult = handle;
        return nil;
    }
    // An answer built on its own has an arena of its own, which joins the lent
    // one here as appending it to the clip's track would. It is checked before
    // anything moves, as every call that moves an object checks it.
    NSError *moving = nil;
    if (!OTIOCheckMove(lent, answer, NO, &moving)
        || !OTIOMoveHere(lent, answer, &handle, &moving)) {
        return OTIOReason(moving);
    }
    *outResult = handle;
    return nil;
}

/// The one function the library calls for every plugin of one kind.
///
/// Nothing raised in the plugin crosses into the library, whose frames are
/// Rust's: an exception is caught here and becomes the plugin's failure.
static OtioStatus OTIOCall(
    BOOL linking, void *context, OtioDocument *document, OtioNode target,
    OtioNode arguments, OtioNode *outResult, char *message, size_t capacity) {
    OtioStatus status = OTIO_STATUS_PLUGIN_ERROR;
    // The library may call from any thread, and one with no pool of its own.
    @autoreleasepool {
        OTIOArena *lent = OTIO_AUTORELEASE([[OTIOArena alloc] initWithLentPointer:document]);
        NSString *failure = nil;
        @try {
            failure = OTIOAsk(linking, OTIO_BRIDGE(context), lent, target, arguments, outResult);
        } @catch (NSException *exception) {
            failure = [NSString
                stringWithFormat:@"it raised %@: %@", exception.name, exception.reason];
        } @catch (id thrown) {
            failure = [NSString stringWithFormat:@"it threw %@", thrown];
        }
        // The document is lent for the call only. An object the plugin kept
        // names it no longer, and fails rather than reaching it afterwards.
        [lent endLoan];
        if (failure == nil) {
            status = OTIO_STATUS_OK;
        } else {
            OTIOSay(message, capacity, failure);
        }
    }
    return status;
}

static OtioStatus OTIOCallLinker(
    void *context, OtioDocument *document, OtioNode target, OtioNode arguments,
    OtioNode *outResult, char *message, size_t capacity) {
    return OTIOCall(YES, context, document, target, arguments, outResult, message, capacity);
}

static OtioStatus OTIOCallHookScript(
    void *context, OtioDocument *document, OtioNode target, OtioNode arguments,
    OtioNode *outResult, char *message, size_t capacity) {
    return OTIOCall(NO, context, document, target, arguments, outResult, message, capacity);
}

/// Gives back the reference the library was given, once it is done with it.
static void OTIOReleasePlugin(void *context) {
    @autoreleasepool {
        OTIO_BRIDGE_RELEASE(context);
    }
}

/// Hands the library a plugin, retained, as the context of its registration.
static BOOL OTIORegister(NSString *name, id _Nullable plugin, BOOL linking, NSError **error) {
    if (plugin == nil) {
        if (error != NULL) {
            NSString *text = linking ? @"otio: no media linker was given"
                                     : @"otio: no hook script was given";
            *error = [NSError errorWithDomain:OTIOErrorDomain
                                         code:(NSInteger)OTIOStatusNullPointer
                                     userInfo:@{NSLocalizedDescriptionKey: text}];
        }
        return NO;
    }
    void *context = OTIO_BRIDGE_RETAIN(plugin);
    OtioBuffer message = {NULL, 0};
    OtioStatus status = linking
        ? otio_register_media_linker(
              OTIOCString(name), OTIOCallLinker, context, OTIOReleasePlugin, &message)
        : otio_register_hook_script(
              OTIOCString(name), OTIOCallHookScript, context, OTIOReleasePlugin, &message);
    if (status != OTIO_STATUS_OK) {
        // A registration that fails keeps nothing, so nothing else will
        // release it.
        OTIOReleasePlugin(context);
    }
    return OTIOCheck(status, message, error);
}

BOOL OTIORegisterMediaLinker(NSString *name, id<OTIOMediaLinker> linker, NSError **error) {
    return OTIORegister(name, linker, YES, error);
}

BOOL OTIORegisterHookScript(NSString *name, id<OTIOHookScript> script, NSError **error) {
    return OTIORegister(name, script, NO, error);
}

#if __has_feature(blocks)

/// A block, answering as a media linker.
///
/// GNUstep's runtime has the fragile ABI, so the storage is declared on the
/// interface, as everywhere else in this library.
@interface OTIOBlockMediaLinker : NSObject <OTIOMediaLinker> {
@private
    OTIOMediaLinkerBlock _block;
}
- (instancetype)initWithBlock:(OTIOMediaLinkerBlock)block;
@end

@implementation OTIOBlockMediaLinker

- (instancetype)initWithBlock:(OTIOMediaLinkerBlock)block {
    self = [super init];
    if (self) {
        // A block may start on the stack; the copy is one that outlives it.
        _block = [block copy];
    }
    return self;
}

- (void)dealloc {
#if !__has_feature(objc_arc)
    [_block release];
    [super dealloc];
#endif
}

- (nullable OTIOMediaReference *)linkMediaReferenceForClip:(OTIOClip *)clip
                                                 arguments:(OTIOMetadata *)arguments
                                                     error:(NSError **)error {
    return _block(clip, arguments, error);
}

@end

/// A block, answering as a hook script.
@interface OTIOBlockHookScript : NSObject <OTIOHookScript> {
@private
    OTIOHookScriptBlock _block;
}
- (instancetype)initWithBlock:(OTIOHookScriptBlock)block;
@end

@implementation OTIOBlockHookScript

- (instancetype)initWithBlock:(OTIOHookScriptBlock)block {
    self = [super init];
    if (self) {
        _block = [block copy];
    }
    return self;
}

- (void)dealloc {
#if !__has_feature(objc_arc)
    [_block release];
    [super dealloc];
#endif
}

- (nullable OTIOSerializableObject *)runHookOnObject:(OTIOSerializableObject *)target
                                           arguments:(OTIOMetadata *)arguments
                                               error:(NSError **)error {
    return _block(target, arguments, error);
}

@end

BOOL OTIORegisterMediaLinkerUsingBlock(
    NSString *name, OTIOMediaLinkerBlock linker, NSError **error) {
    OTIOBlockMediaLinker *wrapped = OTIO_AUTORELEASE(
        linker == nil ? nil : [[OTIOBlockMediaLinker alloc] initWithBlock:linker]);
    return OTIORegister(name, wrapped, YES, error);
}

BOOL OTIORegisterHookScriptUsingBlock(
    NSString *name, OTIOHookScriptBlock script, NSError **error) {
    OTIOBlockHookScript *wrapped = OTIO_AUTORELEASE(
        script == nil ? nil : [[OTIOBlockHookScript alloc] initWithBlock:script]);
    return OTIORegister(name, wrapped, NO, error);
}

#endif
