// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

#import "OpenTimelineIO/OTIORuntime.h"

#import <otio.h>

#import "OTIOPrivate.h"

NSString *const OTIOErrorDomain = @"OTIOErrorDomain";

const char *_Nullable OTIOCString(NSString *_Nullable text) {
    return text == nil ? NULL : text.UTF8String;
}

NSString *OTIOStringFromC(const char *_Nullable text) {
    return text == NULL ? @"" : [NSString stringWithUTF8String:text];
}

NSString *OTIOStringFromBuffer(OtioBuffer buffer) {
    if (buffer.data == NULL) {
        return @"";
    }
    NSString *text = [[NSString alloc] initWithBytes:buffer.data
                                              length:buffer.len
                                            encoding:NSUTF8StringEncoding];
    otio_buffer_free(buffer);
    if (text == nil) {
        return @"";
    }
    return OTIO_AUTORELEASE(text);
}

NSData *OTIODataFromBuffer(OtioBuffer buffer) {
    if (buffer.data == NULL) {
        return [NSData data];
    }
    NSData *bytes = [NSData dataWithBytes:buffer.data length:buffer.len];
    otio_buffer_free(buffer);
    return bytes;
}

BOOL OTIOCheck(OtioStatus status, NSError **error) {
    if (status == OTIO_STATUS_OK) {
        return YES;
    }
    if (error != NULL) {
        NSString *message = OTIOStringFromC(otio_error_message());
        if (message.length == 0) {
            message = OTIOStringFromC(otio_status_name(status));
        }
        *error = [NSError errorWithDomain:OTIOErrorDomain
                                     code:(NSInteger)status
                                 userInfo:@{NSLocalizedDescriptionKey: message}];
    }
    return NO;
}

/// Reports a failure this library noticed itself, rather than one the C
/// interface reported.
static BOOL OTIOFail(OTIOStatus status, NSString *message, NSError **error) {
    if (error != NULL) {
        *error = [NSError errorWithDomain:OTIOErrorDomain
                                     code:(NSInteger)status
                                 userInfo:@{NSLocalizedDescriptionKey: message}];
    }
    return NO;
}

BOOL OTIOIsNoValue(NSError *_Nullable error) {
    return error != nil && [error.domain isEqualToString:OTIOErrorDomain]
        && error.code == (NSInteger)OTIOStatusNoValue;
}

BOOL OTIOSameDocument(
    OTIODocument *_Nullable owner, OTIOSerializableObject *_Nullable node) {
    if (node == nil) {
        return YES;
    }
    return node.document == owner || otio_node_is_none(node.handle);
}

BOOL OTIORequireSameDocument(
    OTIODocument *_Nullable owner, OTIOSerializableObject *_Nullable node, NSError **error) {
    if (OTIOSameDocument(owner, node)) {
        return YES;
    }
    return OTIOFail(
        OTIOStatusInvalidArgument, @"otio: the object belongs to another document", error);
}

BOOL OTIOSameDocumentAll(
    OTIODocument *_Nullable owner, NSArray<OTIOSerializableObject *> *nodes) {
    for (OTIOSerializableObject *node in nodes) {
        if (!OTIOSameDocument(owner, node)) {
            return NO;
        }
    }
    return YES;
}

BOOL OTIORequireSameDocumentAll(
    OTIODocument *_Nullable owner,
    NSArray<OTIOSerializableObject *> *nodes,
    NSError **error) {
    for (OTIOSerializableObject *node in nodes) {
        if (!OTIORequireSameDocument(owner, node, error)) {
            return NO;
        }
    }
    return YES;
}

/// The part of a path after its last dot, which names a format.
static NSString *OTIOSuffix(NSString *path) {
    NSString *name = [path stringByReplacingOccurrencesOfString:@"\\" withString:@"/"];
    NSRange slash = [name rangeOfString:@"/" options:NSBackwardsSearch];
    if (slash.location != NSNotFound) {
        name = [name substringFromIndex:slash.location + 1];
    }
    NSRange dot = [name rangeOfString:@"." options:NSBackwardsSearch];
    if (dot.location == NSNotFound || dot.location == 0) {
        return @"";
    }
    return [name substringFromIndex:dot.location + 1];
}

BOOL OTIOFormatOfPath(NSString *path, OTIOFormat *outFormat, NSError **error) {
    NSString *suffix = OTIOSuffix(path);
    NSError *reason = nil;
    if (OTIOFormatFromSuffix(suffix, outFormat, &reason)) {
        return YES;
    }
    if (OTIOIsNoValue(reason)) {
        return OTIOFail(
            OTIOStatusNoValue,
            [NSString stringWithFormat:@"otio: no format is written with the suffix .%@", suffix],
            error);
    }
    if (error != NULL) {
        *error = reason;
    }
    return NO;
}

OTIODocument *_Nullable OTIOMakeDocument(OtioDocument *_Nullable pointer) {
    if (pointer == NULL) {
        return nil;
    }
    return OTIO_AUTORELEASE([[OTIODocument alloc] initWithPointer:pointer]);
}

@implementation OTIODocument

- (instancetype)init {
    return [self initWithPointer:otio_document_new()];
}

- (instancetype)initWithPointer:(nullable OtioDocument *)pointer {
    self = [super init];
    if (self) {
        _pointer = pointer;
    }
    return self;
}

- (nullable OtioDocument *)pointer {
    return (OtioDocument *)_pointer;
}

- (void)close {
    if (_pointer != NULL) {
        otio_document_free((OtioDocument *)_pointer);
        _pointer = NULL;
    }
}

- (void)forget {
    _pointer = NULL;
}

- (void)dealloc {
    [self close];
#if !__has_feature(objc_arc)
    [super dealloc];
#endif
}

+ (nullable instancetype)open:(NSString *)path error:(NSError **)error {
    OTIOFormat format;
    if (!OTIOFormatOfPath(path, &format, error)) {
        return nil;
    }
    return [OTIODocument readFromFile:format path:path options:NULL error:error];
}

- (BOOL)save:(NSString *)path error:(NSError **)error {
    OTIOFormat format;
    if (!OTIOFormatOfPath(path, &format, error)) {
        return NO;
    }
    return [self writeToFile:format path:path options:NULL error:error];
}

- (nullable NSDictionary<OTIOSerializableObject *, OTIOSerializableObject *> *)
    absorb:(OTIODocument *)source
     error:(NSError **)error {
    if (self.pointer == NULL || source.pointer == NULL) {
        OTIOFail(OTIOStatusNullPointer, @"otio: the document is closed", error);
        return nil;
    }
    // The call cannot be asked twice to size its answer, because the first ask
    // would already have consumed the source. The source's own count is
    // exactly how many objects will move.
    size_t moving = otio_document_node_count(source.pointer);
    OtioNode *from = (OtioNode *)calloc(moving ? moving : 1, sizeof(OtioNode));
    OtioNode *to = (OtioNode *)calloc(moving ? moving : 1, sizeof(OtioNode));
    OtioDocument *taken = source.pointer;
    size_t count = 0;
    OtioStatus status = otio_document_absorb(self.pointer, &taken, from, to, moving, &count);
    // The call frees the source and clears the pointer it was given once it
    // has consumed it, so the wrapper is told to let go rather than being left
    // to free what has already gone.
    if (taken == NULL) {
        [source forget];
    }
    if (!OTIOCheck(status, error)) {
        free(from);
        free(to);
        return nil;
    }
    if (count > moving) {
        count = moving;
    }
    NSMutableDictionary<OTIOSerializableObject *, OTIOSerializableObject *> *translated =
        [NSMutableDictionary dictionaryWithCapacity:count];
    for (size_t slot = 0; slot < count; slot++) {
        OTIOSerializableObject *was = [OTIOSerializableObject objectWithDocument:source
                                                                         handle:from[slot]];
        [translated setObject:OTIOMakeObject(self, to[slot]) forKey:was];
    }
    free(from);
    free(to);
    return translated;
}

@end

@implementation OTIOSerializableObject

+ (instancetype)objectWithDocument:(nullable OTIODocument *)document handle:(OtioNode)handle {
    return OTIO_AUTORELEASE([[self alloc] initWithDocument:document handle:handle]);
}

- (instancetype)initWithDocument:(nullable OTIODocument *)document handle:(OtioNode)handle {
    self = [super init];
    if (self) {
        _document = OTIO_RETAIN(document);
        _index = handle.index;
        _generation = handle.generation;
    }
    return self;
}

- (void)dealloc {
#if !__has_feature(objc_arc)
    [_document release];
    [super dealloc];
#endif
}

- (nullable OTIODocument *)document {
    return _document;
}

- (OtioNode)handle {
    OtioNode handle;
    handle.index = _index;
    handle.generation = _generation;
    return handle;
}

- (nullable OtioDocument *)documentPointer {
    return _document.pointer;
}

- (BOOL)isA:(OTIONodeKind)schema {
    if (self.documentPointer == NULL) {
        return NO;
    }
    OtioNodeKind kind;
    if (otio_node_kind(self.documentPointer, self.handle, &kind) != OTIO_STATUS_OK) {
        return NO;
    }
    return OTIOSchemaDerives((OTIONodeKind)kind, schema);
}

// The library's own `equals:`, generated from `otio_node_equal`, asks the same
// question and gets the same answer; this one is here because NSDictionary
// needs it, and it answers without a call so that it still works once the
// document has gone.
- (BOOL)isEqual:(nullable id)other {
    if (self == other) {
        return YES;
    }
    if (![other isKindOfClass:[OTIOSerializableObject class]]) {
        return NO;
    }
    OTIOSerializableObject *node = (OTIOSerializableObject *)other;
    return node.document == _document && node.handle.index == _index
        && node.handle.generation == _generation;
}

- (NSUInteger)hash {
    return (NSUInteger)_index * 31u + (NSUInteger)_generation;
}

// A wrapper is a document and a handle and neither can change, so a copy of
// one is itself.
- (id)copyWithZone:(nullable NSZone *)zone {
    (void)zone;
    return OTIO_RETAIN(self);
}

@end
