// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

#import "OpenTimelineIO/OTIOCalls.h"

#import <stdlib.h>

#import <otio.h>

#import "OTIOPrivate.h"

BOOL OTIOFormatFromSuffix(NSString *suffix, OTIOFormat *outFormat, NSError **error) {
    OtioFormat cFormat;
    OtioStatus status = otio_format_from_suffix(OTIOCString(suffix), &cFormat);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outFormat) {
        *outFormat = (OTIOFormat)cFormat;
    }
    return YES;
}

NSString *OTIOFormatName(OTIOFormat format) {
    const char *cReturned = otio_format_name((OtioFormat)format);
    return OTIOStringFromC(cReturned);
}

double OTIODefaultEpsilonS(void) {
    double cReturned = otio_default_epsilon_s();
    return cReturned;
}

NSUInteger OTIODefaultIndent(void) {
    size_t cReturned = otio_default_indent();
    return (NSUInteger)cReturned;
}

NSString *OTIOVersion(void) {
    const char *cReturned = otio_version();
    return OTIOStringFromC(cReturned);
}

BOOL OTIOIsDropFrameRate(double rate) {
    bool cReturned = otio_is_drop_frame_rate(rate);
    return (cReturned ? YES : NO);
}

BOOL OTIOIsSMPTETimecodeRate(double rate) {
    bool cReturned = otio_is_smpte_timecode_rate(rate);
    return (cReturned ? YES : NO);
}

double OTIONearestSMPTETimecodeRate(double rate) {
    double cReturned = otio_nearest_smpte_timecode_rate(rate);
    return cReturned;
}

OTIORationalTime OTIORationalTimeAdd(OTIORationalTime left, OTIORationalTime right) {
    OtioRationalTime cReturned = otio_rational_time_add(OTIORationalTimeToC(left), OTIORationalTimeToC(right));
    return OTIORationalTimeFromC(cReturned);
}

BOOL OTIORationalTimeAlmostEquals(OTIORationalTime left, OTIORationalTime right, double delta) {
    bool cReturned = otio_rational_time_almost_equal(OTIORationalTimeToC(left), OTIORationalTimeToC(right), delta);
    return (cReturned ? YES : NO);
}

OTIORationalTime OTIORationalTimeCeil(OTIORationalTime time) {
    OtioRationalTime cReturned = otio_rational_time_ceil(OTIORationalTimeToC(time));
    return OTIORationalTimeFromC(cReturned);
}

int32_t OTIORationalTimeCompare(OTIORationalTime left, OTIORationalTime right) {
    int32_t cReturned = otio_rational_time_compare(OTIORationalTimeToC(left), OTIORationalTimeToC(right));
    return cReturned;
}

OTIORationalTime OTIORationalTimeDurationFromStartEndTime(OTIORationalTime startTime, OTIORationalTime endTimeExclusive) {
    OtioRationalTime cReturned = otio_rational_time_duration_from_start_end_time(OTIORationalTimeToC(startTime), OTIORationalTimeToC(endTimeExclusive));
    return OTIORationalTimeFromC(cReturned);
}

OTIORationalTime OTIORationalTimeDurationFromStartEndTimeInclusive(OTIORationalTime startTime, OTIORationalTime endTimeInclusive) {
    OtioRationalTime cReturned = otio_rational_time_duration_from_start_end_time_inclusive(OTIORationalTimeToC(startTime), OTIORationalTimeToC(endTimeInclusive));
    return OTIORationalTimeFromC(cReturned);
}

BOOL OTIORationalTimeEquals(OTIORationalTime left, OTIORationalTime right) {
    bool cReturned = otio_rational_time_equal(OTIORationalTimeToC(left), OTIORationalTimeToC(right));
    return (cReturned ? YES : NO);
}

OTIORationalTime OTIORationalTimeFloor(OTIORationalTime time) {
    OtioRationalTime cReturned = otio_rational_time_floor(OTIORationalTimeToC(time));
    return OTIORationalTimeFromC(cReturned);
}

OTIORationalTime OTIORationalTimeFromFrames(double frame, double rate) {
    OtioRationalTime cReturned = otio_rational_time_from_frames(frame, rate);
    return OTIORationalTimeFromC(cReturned);
}

OTIORationalTime OTIORationalTimeFromSeconds(double seconds) {
    OtioRationalTime cReturned = otio_rational_time_from_seconds(seconds);
    return OTIORationalTimeFromC(cReturned);
}

OTIORationalTime OTIORationalTimeFromSecondsAtRate(double seconds, double rate) {
    OtioRationalTime cReturned = otio_rational_time_from_seconds_at_rate(seconds, rate);
    return OTIORationalTimeFromC(cReturned);
}

BOOL OTIORationalTimeFromTimeString(NSString *timeString, double rate, OTIORationalTime *outTime, NSError **error) {
    OtioRationalTime cTime;
    OtioStatus status = otio_rational_time_from_time_string(OTIOCString(timeString), rate, &cTime);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outTime) {
        *outTime = OTIORationalTimeFromC(cTime);
    }
    return YES;
}

BOOL OTIORationalTimeFromTimecode(NSString *timecode, double rate, OTIORationalTime *outTime, NSError **error) {
    OtioRationalTime cTime;
    OtioStatus status = otio_rational_time_from_timecode(OTIOCString(timecode), rate, &cTime);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outTime) {
        *outTime = OTIORationalTimeFromC(cTime);
    }
    return YES;
}

BOOL OTIORationalTimeIsValid(OTIORationalTime time) {
    bool cReturned = otio_rational_time_is_valid(OTIORationalTimeToC(time));
    return (cReturned ? YES : NO);
}

OTIORationalTime OTIORationalTimeNegate(OTIORationalTime time) {
    OtioRationalTime cReturned = otio_rational_time_negate(OTIORationalTimeToC(time));
    return OTIORationalTimeFromC(cReturned);
}

OTIORationalTime OTIORationalTimeRescaledTo(OTIORationalTime time, double rate) {
    OtioRationalTime cReturned = otio_rational_time_rescaled_to(OTIORationalTimeToC(time), rate);
    return OTIORationalTimeFromC(cReturned);
}

OTIORationalTime OTIORationalTimeRescaledToTime(OTIORationalTime time, OTIORationalTime other) {
    OtioRationalTime cReturned = otio_rational_time_rescaled_to_time(OTIORationalTimeToC(time), OTIORationalTimeToC(other));
    return OTIORationalTimeFromC(cReturned);
}

OTIORationalTime OTIORationalTimeRound(OTIORationalTime time) {
    OtioRationalTime cReturned = otio_rational_time_round(OTIORationalTimeToC(time));
    return OTIORationalTimeFromC(cReturned);
}

BOOL OTIORationalTimeStrictlyEquals(OTIORationalTime left, OTIORationalTime right) {
    bool cReturned = otio_rational_time_strictly_equal(OTIORationalTimeToC(left), OTIORationalTimeToC(right));
    return (cReturned ? YES : NO);
}

OTIORationalTime OTIORationalTimeSubtract(OTIORationalTime left, OTIORationalTime right) {
    OtioRationalTime cReturned = otio_rational_time_subtract(OTIORationalTimeToC(left), OTIORationalTimeToC(right));
    return OTIORationalTimeFromC(cReturned);
}

int32_t OTIORationalTimeToFrames(OTIORationalTime time) {
    int32_t cReturned = otio_rational_time_to_frames(OTIORationalTimeToC(time));
    return cReturned;
}

int32_t OTIORationalTimeToFramesAtRate(OTIORationalTime time, double rate) {
    int32_t cReturned = otio_rational_time_to_frames_at_rate(OTIORationalTimeToC(time), rate);
    return cReturned;
}

NSString *_Nullable OTIORationalTimeToNearestTimecodeAt(OTIORationalTime time, double rate, OTIODropFrame dropFrame, NSError **error) {
    OtioBuffer cTimecode;
    OtioStatus status = otio_rational_time_to_nearest_timecode_at(OTIORationalTimeToC(time), rate, (OtioDropFrame)dropFrame, &cTimecode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cTimecode);
}

double OTIORationalTimeToSeconds(OTIORationalTime time) {
    double cReturned = otio_rational_time_to_seconds(OTIORationalTimeToC(time));
    return cReturned;
}

NSString *_Nullable OTIORationalTimeToTimeString(OTIORationalTime time, NSError **error) {
    OtioBuffer cString;
    OtioStatus status = otio_rational_time_to_time_string(OTIORationalTimeToC(time), &cString);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cString);
}

NSString *_Nullable OTIORationalTimeToTimecode(OTIORationalTime time, NSError **error) {
    OtioBuffer cTimecode;
    OtioStatus status = otio_rational_time_to_timecode(OTIORationalTimeToC(time), &cTimecode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cTimecode);
}

NSString *_Nullable OTIORationalTimeToTimecodeAt(OTIORationalTime time, double rate, OTIODropFrame dropFrame, NSError **error) {
    OtioBuffer cTimecode;
    OtioStatus status = otio_rational_time_to_timecode_at(OTIORationalTimeToC(time), rate, (OtioDropFrame)dropFrame, &cTimecode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cTimecode);
}

double OTIORationalTimeValueRescaledTo(OTIORationalTime time, double rate) {
    double cReturned = otio_rational_time_value_rescaled_to(OTIORationalTimeToC(time), rate);
    return cReturned;
}

BOOL OTIOTimeRangeBeforeRange(OTIOTimeRange range, OTIOTimeRange other, double epsilonS) {
    bool cReturned = otio_time_range_before_range(OTIOTimeRangeToC(range), OTIOTimeRangeToC(other), epsilonS);
    return (cReturned ? YES : NO);
}

BOOL OTIOTimeRangeBeforeTime(OTIOTimeRange range, OTIORationalTime time, double epsilonS) {
    bool cReturned = otio_time_range_before_time(OTIOTimeRangeToC(range), OTIORationalTimeToC(time), epsilonS);
    return (cReturned ? YES : NO);
}

BOOL OTIOTimeRangeBeginsRange(OTIOTimeRange range, OTIOTimeRange other, double epsilonS) {
    bool cReturned = otio_time_range_begins_range(OTIOTimeRangeToC(range), OTIOTimeRangeToC(other), epsilonS);
    return (cReturned ? YES : NO);
}

BOOL OTIOTimeRangeBeginsTime(OTIOTimeRange range, OTIORationalTime time, double epsilonS) {
    bool cReturned = otio_time_range_begins_time(OTIOTimeRangeToC(range), OTIORationalTimeToC(time), epsilonS);
    return (cReturned ? YES : NO);
}

OTIOTimeRange OTIOTimeRangeClampedRange(OTIOTimeRange range, OTIOTimeRange other) {
    OtioTimeRange cReturned = otio_time_range_clamped_range(OTIOTimeRangeToC(range), OTIOTimeRangeToC(other));
    return OTIOTimeRangeFromC(cReturned);
}

OTIORationalTime OTIOTimeRangeClampedTime(OTIOTimeRange range, OTIORationalTime time) {
    OtioRationalTime cReturned = otio_time_range_clamped_time(OTIOTimeRangeToC(range), OTIORationalTimeToC(time));
    return OTIORationalTimeFromC(cReturned);
}

BOOL OTIOTimeRangeContainsRange(OTIOTimeRange range, OTIOTimeRange other, double epsilonS) {
    bool cReturned = otio_time_range_contains_range(OTIOTimeRangeToC(range), OTIOTimeRangeToC(other), epsilonS);
    return (cReturned ? YES : NO);
}

BOOL OTIOTimeRangeContainsTime(OTIOTimeRange range, OTIORationalTime time) {
    bool cReturned = otio_time_range_contains_time(OTIOTimeRangeToC(range), OTIORationalTimeToC(time));
    return (cReturned ? YES : NO);
}

OTIOTimeRange OTIOTimeRangeDurationExtendedBy(OTIOTimeRange range, OTIORationalTime by) {
    OtioTimeRange cReturned = otio_time_range_duration_extended_by(OTIOTimeRangeToC(range), OTIORationalTimeToC(by));
    return OTIOTimeRangeFromC(cReturned);
}

OTIORationalTime OTIOTimeRangeEndTimeExclusive(OTIOTimeRange range) {
    OtioRationalTime cReturned = otio_time_range_end_time_exclusive(OTIOTimeRangeToC(range));
    return OTIORationalTimeFromC(cReturned);
}

OTIORationalTime OTIOTimeRangeEndTimeInclusive(OTIOTimeRange range) {
    OtioRationalTime cReturned = otio_time_range_end_time_inclusive(OTIOTimeRangeToC(range));
    return OTIORationalTimeFromC(cReturned);
}

OTIOTimeRange OTIOTimeRangeExtendedBy(OTIOTimeRange range, OTIOTimeRange other) {
    OtioTimeRange cReturned = otio_time_range_extended_by(OTIOTimeRangeToC(range), OTIOTimeRangeToC(other));
    return OTIOTimeRangeFromC(cReturned);
}

BOOL OTIOTimeRangeFinishesRange(OTIOTimeRange range, OTIOTimeRange other, double epsilonS) {
    bool cReturned = otio_time_range_finishes_range(OTIOTimeRangeToC(range), OTIOTimeRangeToC(other), epsilonS);
    return (cReturned ? YES : NO);
}

BOOL OTIOTimeRangeFinishesTime(OTIOTimeRange range, OTIORationalTime time, double epsilonS) {
    bool cReturned = otio_time_range_finishes_time(OTIOTimeRangeToC(range), OTIORationalTimeToC(time), epsilonS);
    return (cReturned ? YES : NO);
}

OTIOTimeRange OTIOTimeRangeFromStartEndTime(OTIORationalTime startTime, OTIORationalTime endTimeExclusive) {
    OtioTimeRange cReturned = otio_time_range_from_start_end_time(OTIORationalTimeToC(startTime), OTIORationalTimeToC(endTimeExclusive));
    return OTIOTimeRangeFromC(cReturned);
}

OTIOTimeRange OTIOTimeRangeFromStartEndTimeInclusive(OTIORationalTime startTime, OTIORationalTime endTimeInclusive) {
    OtioTimeRange cReturned = otio_time_range_from_start_end_time_inclusive(OTIORationalTimeToC(startTime), OTIORationalTimeToC(endTimeInclusive));
    return OTIOTimeRangeFromC(cReturned);
}

BOOL OTIOTimeRangeIntersects(OTIOTimeRange range, OTIOTimeRange other, double epsilonS) {
    bool cReturned = otio_time_range_intersects(OTIOTimeRangeToC(range), OTIOTimeRangeToC(other), epsilonS);
    return (cReturned ? YES : NO);
}

BOOL OTIOTimeRangeIsValid(OTIOTimeRange range) {
    bool cReturned = otio_time_range_is_valid(OTIOTimeRangeToC(range));
    return (cReturned ? YES : NO);
}

BOOL OTIOTimeRangeMeets(OTIOTimeRange range, OTIOTimeRange other, double epsilonS) {
    bool cReturned = otio_time_range_meets(OTIOTimeRangeToC(range), OTIOTimeRangeToC(other), epsilonS);
    return (cReturned ? YES : NO);
}

BOOL OTIOTimeRangeOverlapsRange(OTIOTimeRange range, OTIOTimeRange other, double epsilonS) {
    bool cReturned = otio_time_range_overlaps_range(OTIOTimeRangeToC(range), OTIOTimeRangeToC(other), epsilonS);
    return (cReturned ? YES : NO);
}

BOOL OTIOTimeRangeOverlapsTime(OTIOTimeRange range, OTIORationalTime time) {
    bool cReturned = otio_time_range_overlaps_time(OTIOTimeRangeToC(range), OTIORationalTimeToC(time));
    return (cReturned ? YES : NO);
}

OTIOTimeRange OTIOTimeTransformAppliedToRange(OTIOTimeTransform transform, OTIOTimeRange range) {
    OtioTimeRange cReturned = otio_time_transform_applied_to_range(OTIOTimeTransformToC(transform), OTIOTimeRangeToC(range));
    return OTIOTimeRangeFromC(cReturned);
}

OTIORationalTime OTIOTimeTransformAppliedToTime(OTIOTimeTransform transform, OTIORationalTime time) {
    OtioRationalTime cReturned = otio_time_transform_applied_to_time(OTIOTimeTransformToC(transform), OTIORationalTimeToC(time));
    return OTIORationalTimeFromC(cReturned);
}

OTIOTimeTransform OTIOTimeTransformAppliedToTransform(OTIOTimeTransform transform, OTIOTimeTransform other) {
    OtioTimeTransform cReturned = otio_time_transform_applied_to_transform(OTIOTimeTransformToC(transform), OTIOTimeTransformToC(other));
    return OTIOTimeTransformFromC(cReturned);
}

OTIOSerializableObject *_Nullable OTIOReadFromBytes(OTIOFormat format, NSData *data, const OTIOReadOptions *_Nullable options, NSError **error) {
    OtioReadOptions cOptions;
    const OtioReadOptions *cOptionsPointer = NULL;
    if (options) {
        cOptions = OTIOReadOptionsToC(*options);
        cOptionsPointer = &cOptions;
    }
    OtioDocument * cDocument;
    OtioStatus status = otio_read_from_bytes((OtioFormat)format, (const uint8_t *)data.bytes, (size_t)data.length, cOptionsPointer, &cDocument);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIORootOf(cDocument, error);
}

OTIOSerializableObject *_Nullable OTIOReadFromFile(OTIOFormat format, NSString *path, const OTIOReadOptions *_Nullable options, NSError **error) {
    OtioReadOptions cOptions;
    const OtioReadOptions *cOptionsPointer = NULL;
    if (options) {
        cOptions = OTIOReadOptionsToC(*options);
        cOptionsPointer = &cOptions;
    }
    OtioDocument * cDocument;
    OtioStatus status = otio_read_from_file((OtioFormat)format, OTIOCString(path), cOptionsPointer, &cDocument);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIORootOf(cDocument, error);
}

OTIOReadOptions OTIOReadOptionsDefault(void) {
    OtioReadOptions cReturned = otio_read_options_default();
    return OTIOReadOptionsFromC(cReturned);
}

OTIOWriteOptions OTIOWriteOptionsDefault(void) {
    OtioWriteOptions cReturned = otio_write_options_default();
    return OTIOWriteOptionsFromC(cReturned);
}

NSData *_Nullable OTIOWriteToBytes(OTIOFormat format, OTIOSerializableObject *root, const OTIOWriteOptions *_Nullable options, NSError **error) {
    OTIOArena *at = OTIORootedAt(root, error);
    if (at == nil) { return nil; }
    OtioWriteOptions cOptions;
    const OtioWriteOptions *cOptionsPointer = NULL;
    if (options) {
        cOptions = OTIOWriteOptionsToC(*options);
        cOptionsPointer = &cOptions;
    }
    OtioBuffer cBytes;
    OtioStatus status = otio_write_to_bytes((OtioFormat)format, at.pointer, cOptionsPointer, &cBytes);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIODataFromBuffer(cBytes);
}

BOOL OTIOWriteToFile(OTIOFormat format, OTIOSerializableObject *root, NSString *path, const OTIOWriteOptions *_Nullable options, NSError **error) {
    OTIOArena *at = OTIORootedAt(root, error);
    if (at == nil) { return NO; }
    OtioWriteOptions cOptions;
    const OtioWriteOptions *cOptionsPointer = NULL;
    if (options) {
        cOptions = OTIOWriteOptionsToC(*options);
        cOptionsPointer = &cOptions;
    }
    OtioStatus status = otio_write_to_file((OtioFormat)format, at.pointer, OTIOCString(path), cOptionsPointer);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

OTIOSerializableObject *_Nullable OTIOFlattenStack(OTIOSerializableObject *stack, NSError **error) {
    OTIOArena *at = OTIOLocate(stack, NULL);
    OtioNode cStack;
    if (!OTIORequireHere(at, stack, &cStack, error)) { return nil; }
    OtioNode cTrack;
    OtioStatus status = otio_algorithm_flatten_stack(at.pointer, cStack, &cTrack);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cTrack);
}

OTIOSerializableObject *_Nullable OTIOFlattenTracks(NSArray<OTIOSerializableObject *> *tracks, NSError **error) {
    OTIOArena *at = OTIOLocateAll(tracks, error);
    if (at == nil) { return nil; }
    OtioNode *cTracks = OTIORequireHereAll(at, tracks, error);
    if (cTracks == NULL) { return nil; }
    OtioNode cTrack;
    OtioStatus status = otio_algorithm_flatten_tracks(at.pointer, cTracks, (size_t)tracks.count, &cTrack);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cTrack);
}

OTIOSerializableObject *_Nullable OTIOTrackTrimmedToRange(OTIOSerializableObject *track, OTIOTimeRange trimRange, NSError **error) {
    OTIOArena *at = OTIOLocate(track, NULL);
    OtioNode cTrack;
    if (!OTIORequireHere(at, track, &cTrack, error)) { return nil; }
    OtioNode cTrack;
    OtioStatus status = otio_algorithm_track_trimmed_to_range(at.pointer, cTrack, OTIOTimeRangeToC(trimRange), &cTrack);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cTrack);
}

OTIOSerializableObject *_Nullable OTIOFromJSON(NSString *json, NSError **error) {
    OtioDocument * cDocument;
    OtioStatus status = otio_document_from_json(OTIOCString(json), &cDocument);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIORootOf(cDocument, error);
}

OTIOSerializableObject *_Nullable OTIOReadOTIOFile(NSString *path, NSError **error) {
    OtioDocument * cDocument;
    OtioStatus status = otio_document_read_from_file(OTIOCString(path), &cDocument);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIORootOf(cDocument, error);
}

BOOL OTIOWriteOTIOFile(OTIOSerializableObject *root, NSString *path, NSUInteger indent, NSError **error) {
    OTIOArena *at = OTIORootedAt(root, error);
    if (at == nil) { return NO; }
    OtioStatus status = otio_document_write_to_file(at.pointer, OTIOCString(path), (size_t)indent);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

BOOL OTIOFill(OTIOSerializableObject *item, OTIOSerializableObject *track, OTIORationalTime trackTime, OTIOReferencePoint referencePoint, NSError **error) {
    OTIOArena *at = OTIOLocate(track, NULL);
    OtioNode cItem;
    if (!OTIOAdopt(at, item, &cItem, error)) { return NO; }
    OtioNode cTrack;
    if (!OTIORequireHere(at, track, &cTrack, error)) { return NO; }
    OtioStatus status = otio_edit_fill(at.pointer, cItem, cTrack, OTIORationalTimeToC(trackTime), (OtioReferencePoint)referencePoint);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

BOOL OTIOInsert(OTIOSerializableObject *item, OTIOSerializableObject *composition, OTIORationalTime time, BOOL removeTransitions, OTIOSerializableObject *_Nullable fillTemplate, NSError **error) {
    OTIOArena *at = OTIOLocate(composition, NULL);
    OtioNode cItem;
    if (!OTIOAdopt(at, item, &cItem, error)) { return NO; }
    OtioNode cComposition;
    if (!OTIORequireHere(at, composition, &cComposition, error)) { return NO; }
    OtioNode cFillTemplate;
    if (!OTIOAdopt(at, fillTemplate, &cFillTemplate, error)) { return NO; }
    OtioStatus status = otio_edit_insert(at.pointer, cItem, cComposition, OTIORationalTimeToC(time), (removeTransitions ? true : false), cFillTemplate);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

BOOL OTIOOverwrite(OTIOSerializableObject *item, OTIOSerializableObject *composition, OTIOTimeRange range, BOOL removeTransitions, OTIOSerializableObject *_Nullable fillTemplate, NSError **error) {
    OTIOArena *at = OTIOLocate(composition, NULL);
    OtioNode cItem;
    if (!OTIOAdopt(at, item, &cItem, error)) { return NO; }
    OtioNode cComposition;
    if (!OTIORequireHere(at, composition, &cComposition, error)) { return NO; }
    OtioNode cFillTemplate;
    if (!OTIOAdopt(at, fillTemplate, &cFillTemplate, error)) { return NO; }
    OtioStatus status = otio_edit_overwrite(at.pointer, cItem, cComposition, OTIOTimeRangeToC(range), (removeTransitions ? true : false), cFillTemplate);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

BOOL OTIORemove(OTIOSerializableObject *composition, OTIORationalTime time, BOOL fill, OTIOSerializableObject *_Nullable fillTemplate, NSError **error) {
    OTIOArena *at = OTIOLocate(composition, NULL);
    OtioNode cComposition;
    if (!OTIORequireHere(at, composition, &cComposition, error)) { return NO; }
    OtioNode cFillTemplate;
    if (!OTIOAdopt(at, fillTemplate, &cFillTemplate, error)) { return NO; }
    OtioStatus status = otio_edit_remove(at.pointer, cComposition, OTIORationalTimeToC(time), (fill ? true : false), cFillTemplate);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

BOOL OTIORipple(OTIOSerializableObject *item, OTIORationalTime deltaIn, OTIORationalTime deltaOut, NSError **error) {
    OTIOArena *at = OTIOLocate(item, NULL);
    OtioNode cItem;
    if (!OTIORequireHere(at, item, &cItem, error)) { return NO; }
    OtioStatus status = otio_edit_ripple(at.pointer, cItem, OTIORationalTimeToC(deltaIn), OTIORationalTimeToC(deltaOut));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

BOOL OTIORoll(OTIOSerializableObject *item, OTIORationalTime deltaIn, OTIORationalTime deltaOut, NSError **error) {
    OTIOArena *at = OTIOLocate(item, NULL);
    OtioNode cItem;
    if (!OTIORequireHere(at, item, &cItem, error)) { return NO; }
    OtioStatus status = otio_edit_roll(at.pointer, cItem, OTIORationalTimeToC(deltaIn), OTIORationalTimeToC(deltaOut));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

BOOL OTIOSlice(OTIOSerializableObject *composition, OTIORationalTime time, BOOL removeTransitions, NSError **error) {
    OTIOArena *at = OTIOLocate(composition, NULL);
    OtioNode cComposition;
    if (!OTIORequireHere(at, composition, &cComposition, error)) { return NO; }
    OtioStatus status = otio_edit_slice(at.pointer, cComposition, OTIORationalTimeToC(time), (removeTransitions ? true : false));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

BOOL OTIOSlide(OTIOSerializableObject *item, OTIORationalTime delta, NSError **error) {
    OTIOArena *at = OTIOLocate(item, NULL);
    OtioNode cItem;
    if (!OTIORequireHere(at, item, &cItem, error)) { return NO; }
    OtioStatus status = otio_edit_slide(at.pointer, cItem, OTIORationalTimeToC(delta));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

BOOL OTIOSlip(OTIOSerializableObject *item, OTIORationalTime delta, NSError **error) {
    OTIOArena *at = OTIOLocate(item, NULL);
    OtioNode cItem;
    if (!OTIORequireHere(at, item, &cItem, error)) { return NO; }
    OtioStatus status = otio_edit_slip(at.pointer, cItem, OTIORationalTimeToC(delta));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

BOOL OTIOTrim(OTIOSerializableObject *item, OTIORationalTime deltaIn, OTIORationalTime deltaOut, OTIOSerializableObject *_Nullable fillTemplate, NSError **error) {
    OTIOArena *at = OTIOLocate(item, NULL);
    OtioNode cItem;
    if (!OTIORequireHere(at, item, &cItem, error)) { return NO; }
    OtioNode cFillTemplate;
    if (!OTIOAdopt(at, fillTemplate, &cFillTemplate, error)) { return NO; }
    OtioStatus status = otio_edit_trim(at.pointer, cItem, OTIORationalTimeToC(deltaIn), OTIORationalTimeToC(deltaOut), cFillTemplate);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

@implementation OTIOClip (OTIOGenerated)

- (nullable NSString *)activeMediaReferenceKey:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBuffer cKey;
    OtioStatus status = otio_clip_active_media_reference_key(at.pointer, atHandle, &cKey);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cKey);
}

- (nullable OTIOSerializableObject *)mediaReference:(NSString *_Nullable)key error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cReference;
    OtioStatus status = otio_clip_media_reference(at.pointer, atHandle, OTIOCString(key), &cReference);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cReference);
}

- (BOOL)getMediaReferenceCount:(NSUInteger *)outCount error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    size_t cCount;
    OtioStatus status = otio_clip_media_reference_count(at.pointer, atHandle, &cCount);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outCount) {
        *outCount = (NSUInteger)cCount;
    }
    return YES;
}

- (nullable NSString *)mediaReferenceKeyAt:(NSUInteger)index error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBuffer cKey;
    OtioStatus status = otio_clip_media_reference_key_at(at.pointer, atHandle, (size_t)index, &cKey);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cKey);
}

+ (nullable OTIOClip *)clipWithName:(NSString *_Nullable)name error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_clip_new(at.pointer, OTIOCString(name), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOClip *)OTIOMakeObject(at, cNode);
}

- (nullable OTIOSerializableObject *)removeMediaReference:(NSString *)key error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cReference;
    OtioStatus status = otio_clip_remove_media_reference(at.pointer, atHandle, OTIOCString(key), &cReference);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cReference);
}

- (BOOL)setActiveMediaReferenceKey:(NSString *)key error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_clip_set_active_media_reference_key(at.pointer, atHandle, OTIOCString(key));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setMediaReference:(NSString *)key reference:(OTIOSerializableObject *)reference error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cReference;
    if (!OTIOAdopt(at, reference, &cReference, error)) { return NO; }
    OtioStatus status = otio_clip_set_media_reference(at.pointer, atHandle, OTIOCString(key), cReference);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

@end

@implementation OTIOComposable (OTIOGenerated)

+ (nullable OTIOComposable *)composableWithName:(NSString *_Nullable)name error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_composable_new(at.pointer, OTIOCString(name), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOComposable *)OTIOMakeObject(at, cNode);
}

@end

@implementation OTIOComposition (OTIOGenerated)

- (BOOL)appendChild:(OTIOSerializableObject *)child error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cChild;
    if (!OTIOAdopt(at, child, &cChild, error)) { return NO; }
    OtioStatus status = otio_composition_append_child(at.pointer, atHandle, cChild);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (nullable OTIOSerializableObject *)childAtTime:(OTIORationalTime)time shallow:(BOOL)shallow error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cChild;
    OtioStatus status = otio_composition_child_at_time(at.pointer, atHandle, OTIORationalTimeToC(time), (shallow ? true : false), &cChild);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cChild);
}

- (nullable NSArray<OTIOSerializableObject *> *)childrenInRange:(OTIOTimeRange)searchRange error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    size_t count = 0;
    OtioStatus sizing = otio_composition_children_in_range(at.pointer, atHandle, OTIOTimeRangeToC(searchRange), NULL, 0, &count);
    if (!OTIOCheck(sizing, error)) {
        return nil;
    }
    OtioNode *buffer0 = (OtioNode *)calloc(count ? count : 1, sizeof(OtioNode));
    OtioStatus status = otio_composition_children_in_range(at.pointer, atHandle, OTIOTimeRangeToC(searchRange), buffer0, count, &count);
    if (!OTIOCheck(status, error)) {
        free(buffer0);
        return nil;
    }
    NSMutableArray *buffer0Out = [NSMutableArray arrayWithCapacity:count];
    for (size_t slot = 0; slot < count; slot++) {
        [buffer0Out addObject:OTIOMakeObject(at, buffer0[slot])];
    }
    free(buffer0);
    return buffer0Out;
}

- (nullable NSArray<OTIOSerializableObject *> *)clearChildren:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    size_t count = 0;
    // otio_composition_clear_children answers and empties in one go, so the buffer is sized first.
    size_t room = 0;
    OtioStatus sizing = otio_node_child_count(at.pointer, atHandle, &room);
    if (!OTIOCheck(sizing, error)) {
        return nil;
    }
    OtioNode *buffer0 = (OtioNode *)calloc(room ? room : 1, sizeof(OtioNode));
    OtioStatus status = otio_composition_clear_children(at.pointer, atHandle, buffer0, room, &count);
    if (!OTIOCheck(status, error)) {
        free(buffer0);
        return nil;
    }
    if (count > room) {
        count = room;
    }
    NSMutableArray *buffer0Out = [NSMutableArray arrayWithCapacity:count];
    for (size_t slot = 0; slot < count; slot++) {
        [buffer0Out addObject:OTIOMakeObject(at, buffer0[slot])];
    }
    free(buffer0);
    return buffer0Out;
}

- (BOOL)detachChild:(OTIOSerializableObject *)child error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cChild;
    if (!OTIORequireHere(at, child, &cChild, error)) { return NO; }
    OtioStatus status = otio_composition_detach_child(at.pointer, atHandle, cChild);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (nullable NSArray<OTIOSerializableObject *> *)findChildrenOfKind:(OTIONodeKind)kind searchRange:(const OTIOTimeRange *_Nullable)searchRange shallow:(BOOL)shallow error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioTimeRange cSearchRange;
    const OtioTimeRange *cSearchRangePointer = NULL;
    if (searchRange) {
        cSearchRange = OTIOTimeRangeToC(*searchRange);
        cSearchRangePointer = &cSearchRange;
    }
    size_t count = 0;
    OtioStatus sizing = otio_composition_find_children_of_kind(at.pointer, atHandle, (OtioNodeKind)kind, cSearchRangePointer, (shallow ? true : false), NULL, 0, &count);
    if (!OTIOCheck(sizing, error)) {
        return nil;
    }
    OtioNode *buffer0 = (OtioNode *)calloc(count ? count : 1, sizeof(OtioNode));
    OtioStatus status = otio_composition_find_children_of_kind(at.pointer, atHandle, (OtioNodeKind)kind, cSearchRangePointer, (shallow ? true : false), buffer0, count, &count);
    if (!OTIOCheck(status, error)) {
        free(buffer0);
        return nil;
    }
    NSMutableArray *buffer0Out = [NSMutableArray arrayWithCapacity:count];
    for (size_t slot = 0; slot < count; slot++) {
        [buffer0Out addObject:OTIOMakeObject(at, buffer0[slot])];
    }
    free(buffer0);
    return buffer0Out;
}

- (BOOL)getHandlesOfChild:(OTIOHandles *)outHandles child:(OTIOSerializableObject *)child error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cChild;
    if (!OTIORequireHere(at, child, &cChild, error)) { return NO; }
    OtioHandles cHandles;
    OtioStatus status = otio_composition_handles_of_child(at.pointer, atHandle, cChild, &cHandles);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outHandles) {
        *outHandles = OTIOHandlesFromC(cHandles);
    }
    return YES;
}

- (BOOL)getHasChild:(BOOL *)outHas child:(OTIOSerializableObject *)child error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cChild;
    if (!OTIORequireHere(at, child, &cChild, error)) { return NO; }
    bool cHas;
    OtioStatus status = otio_composition_has_child(at.pointer, atHandle, cChild, &cHas);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outHas) {
        *outHas = (cHas ? YES : NO);
    }
    return YES;
}

- (BOOL)getIndexOfChild:(NSUInteger *)outIndex child:(OTIOSerializableObject *)child error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cChild;
    if (!OTIORequireHere(at, child, &cChild, error)) { return NO; }
    size_t cIndex;
    OtioStatus status = otio_composition_index_of_child(at.pointer, atHandle, cChild, &cIndex);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outIndex) {
        *outIndex = (NSUInteger)cIndex;
    }
    return YES;
}

- (BOOL)insertChild:(int64_t)index child:(OTIOSerializableObject *)child error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cChild;
    if (!OTIOAdopt(at, child, &cChild, error)) { return NO; }
    OtioStatus status = otio_composition_insert_child(at.pointer, atHandle, index, cChild);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)getIsParentOf:(BOOL *)outIs other:(OTIOSerializableObject *)other error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cOther;
    if (!OTIORequireHere(at, other, &cOther, error)) { return NO; }
    bool cIs;
    OtioStatus status = otio_composition_is_parent_of(at.pointer, atHandle, cOther, &cIs);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outIs) {
        *outIs = (cIs ? YES : NO);
    }
    return YES;
}

- (BOOL)getNeighborsOf:(OTIOSerializableObject *_Nullable *_Nullable)outBefore after:(OTIOSerializableObject *_Nullable *_Nullable)outAfter child:(OTIOSerializableObject *)child policy:(OTIONeighborGapPolicy)policy error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cChild;
    if (!OTIORequireHere(at, child, &cChild, error)) { return NO; }
    OtioNode cBefore;
    OtioNode cAfter;
    OtioStatus status = otio_composition_neighbors_of(at.pointer, atHandle, cChild, (OtioNeighborGapPolicy)policy, &cBefore, &cAfter);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outBefore) {
        *outBefore = OTIOMakeObject(at, cBefore);
    }
    if (outAfter) {
        *outAfter = OTIOMakeObject(at, cAfter);
    }
    return YES;
}

+ (nullable OTIOComposition *)compositionWithName:(NSString *_Nullable)name error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_composition_new(at.pointer, OTIOCString(name), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOComposition *)OTIOMakeObject(at, cNode);
}

- (BOOL)getRangeOfChild:(OTIOTimeRange *)outRange child:(OTIOSerializableObject *)child error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cChild;
    if (!OTIORequireHere(at, child, &cChild, error)) { return NO; }
    OtioTimeRange cRange;
    OtioStatus status = otio_composition_range_of_child(at.pointer, atHandle, cChild, &cRange);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outRange) {
        *outRange = OTIOTimeRangeFromC(cRange);
    }
    return YES;
}

- (BOOL)getRangeOfChildAtIndex:(OTIOTimeRange *)outRange index:(int64_t)index error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioTimeRange cRange;
    OtioStatus status = otio_composition_range_of_child_at_index(at.pointer, atHandle, index, &cRange);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outRange) {
        *outRange = OTIOTimeRangeFromC(cRange);
    }
    return YES;
}

- (BOOL)getRangesOfChildren:(NSArray<OTIOSerializableObject *> *_Nullable *_Nullable)outNodes ranges:(NSArray<NSValue *> *_Nullable *_Nullable)outRanges error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    size_t count = 0;
    OtioStatus sizing = otio_composition_ranges_of_children(at.pointer, atHandle, NULL, NULL, 0, &count);
    if (!OTIOCheck(sizing, error)) {
        return NO;
    }
    OtioNode *buffer0 = (OtioNode *)calloc(count ? count : 1, sizeof(OtioNode));
    OtioTimeRange *buffer1 = (OtioTimeRange *)calloc(count ? count : 1, sizeof(OtioTimeRange));
    OtioStatus status = otio_composition_ranges_of_children(at.pointer, atHandle, buffer0, buffer1, count, &count);
    if (!OTIOCheck(status, error)) {
        free(buffer0);
        free(buffer1);
        return NO;
    }
    NSMutableArray *buffer0Out = [NSMutableArray arrayWithCapacity:count];
    for (size_t slot = 0; slot < count; slot++) {
        [buffer0Out addObject:OTIOMakeObject(at, buffer0[slot])];
    }
    free(buffer0);
    NSMutableArray *buffer1Out = [NSMutableArray arrayWithCapacity:count];
    for (size_t slot = 0; slot < count; slot++) {
        [buffer1Out addObject:OTIOTimeRangeBoxed(OTIOTimeRangeFromC(buffer1[slot]))];
    }
    free(buffer1);
    if (outNodes) {
        *outNodes = buffer0Out;
    }
    if (outRanges) {
        *outRanges = buffer1Out;
    }
    return YES;
}

- (nullable OTIOSerializableObject *)removeChild:(int64_t)index error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cChild;
    OtioStatus status = otio_composition_remove_child(at.pointer, atHandle, index, &cChild);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cChild);
}

- (BOOL)getTrimChildRange:(OTIOTimeRange *)outRange childRange:(OTIOTimeRange)childRange error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioTimeRange cRange;
    OtioStatus status = otio_composition_trim_child_range(at.pointer, atHandle, OTIOTimeRangeToC(childRange), &cRange);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outRange) {
        *outRange = OTIOTimeRangeFromC(cRange);
    }
    return YES;
}

- (BOOL)getTrimmedRangeOfChild:(OTIOTimeRange *)outRange child:(OTIOSerializableObject *)child error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cChild;
    if (!OTIORequireHere(at, child, &cChild, error)) { return NO; }
    OtioTimeRange cRange;
    OtioStatus status = otio_composition_trimmed_range_of_child(at.pointer, atHandle, cChild, &cRange);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outRange) {
        *outRange = OTIOTimeRangeFromC(cRange);
    }
    return YES;
}

- (BOOL)getTrimmedRangeOfChildAtIndex:(OTIOTimeRange *)outRange index:(int64_t)index error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioTimeRange cRange;
    OtioStatus status = otio_composition_trimmed_range_of_child_at_index(at.pointer, atHandle, index, &cRange);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outRange) {
        *outRange = OTIOTimeRangeFromC(cRange);
    }
    return YES;
}

@end

@implementation OTIOEffect (OTIOGenerated)

- (nullable NSString *)effectName:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBuffer cName;
    OtioStatus status = otio_effect_effect_name(at.pointer, atHandle, &cName);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cName);
}

- (BOOL)getEnabled:(BOOL *)outEnabled error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    bool cEnabled;
    OtioStatus status = otio_effect_enabled(at.pointer, atHandle, &cEnabled);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outEnabled) {
        *outEnabled = (cEnabled ? YES : NO);
    }
    return YES;
}

+ (nullable OTIOEffect *)effectWithName:(NSString *_Nullable)name effectName:(NSString *_Nullable)effectName error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_effect_new(at.pointer, OTIOCString(name), OTIOCString(effectName), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOEffect *)OTIOMakeObject(at, cNode);
}

- (BOOL)setEffectName:(NSString *)effectName error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_effect_set_effect_name(at.pointer, atHandle, OTIOCString(effectName));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setEnabled:(BOOL)enabled error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_effect_set_enabled(at.pointer, atHandle, (enabled ? true : false));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setTimeScalar:(double)scalar error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_effect_set_time_scalar(at.pointer, atHandle, scalar);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)getTimeScalar:(double *)outScalar error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    double cScalar;
    OtioStatus status = otio_effect_time_scalar(at.pointer, atHandle, &cScalar);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outScalar) {
        *outScalar = cScalar;
    }
    return YES;
}

@end

@implementation OTIOExternalReference (OTIOGenerated)

+ (nullable OTIOExternalReference *)externalReferenceWithName:(NSString *_Nullable)name targetURL:(NSString *_Nullable)targetURL error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_external_reference_new(at.pointer, OTIOCString(name), OTIOCString(targetURL), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOExternalReference *)OTIOMakeObject(at, cNode);
}

- (BOOL)setTargetURL:(NSString *)url error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_external_reference_set_target_url(at.pointer, atHandle, OTIOCString(url));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (nullable NSString *)targetURL:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBuffer cURL;
    OtioStatus status = otio_external_reference_target_url(at.pointer, atHandle, &cURL);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cURL);
}

@end

@implementation OTIOFreezeFrame (OTIOGenerated)

+ (nullable OTIOFreezeFrame *)freezeFrameWithName:(NSString *_Nullable)name error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_freeze_frame_new(at.pointer, OTIOCString(name), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOFreezeFrame *)OTIOMakeObject(at, cNode);
}

@end

@implementation OTIOGap (OTIOGenerated)

+ (nullable OTIOGap *)gapWithName:(NSString *_Nullable)name error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_gap_new(at.pointer, OTIOCString(name), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOGap *)OTIOMakeObject(at, cNode);
}

@end

@implementation OTIOGeneratorReference (OTIOGenerated)

- (nullable NSString *)generatorKind:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBuffer cKind;
    OtioStatus status = otio_generator_reference_kind(at.pointer, atHandle, &cKind);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cKind);
}

+ (nullable OTIOGeneratorReference *)generatorReferenceWithName:(NSString *_Nullable)name generatorKind:(NSString *_Nullable)generatorKind error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_generator_reference_new(at.pointer, OTIOCString(name), OTIOCString(generatorKind), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOGeneratorReference *)OTIOMakeObject(at, cNode);
}

- (BOOL)setGeneratorKind:(NSString *)kind error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_generator_reference_set_kind(at.pointer, atHandle, OTIOCString(kind));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

@end

@implementation OTIOImageSequenceReference (OTIOGenerated)

- (nullable NSString *)namePrefix:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBuffer cPrefix;
    OtioStatus status = otio_image_sequence_reference_name_prefix(at.pointer, atHandle, &cPrefix);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cPrefix);
}

- (nullable NSString *)nameSuffix:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBuffer cSuffix;
    OtioStatus status = otio_image_sequence_reference_name_suffix(at.pointer, atHandle, &cSuffix);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cSuffix);
}

+ (nullable OTIOImageSequenceReference *)imageSequenceReferenceWithName:(NSString *_Nullable)name error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_image_sequence_reference_new(at.pointer, OTIOCString(name), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOImageSequenceReference *)OTIOMakeObject(at, cNode);
}

- (BOOL)getNumbers:(OTIOImageSequence *)outNumbers error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioImageSequence cNumbers;
    OtioStatus status = otio_image_sequence_reference_numbers(at.pointer, atHandle, &cNumbers);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outNumbers) {
        *outNumbers = OTIOImageSequenceFromC(cNumbers);
    }
    return YES;
}

- (BOOL)setNamePrefix:(NSString *)prefix error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_image_sequence_reference_set_name_prefix(at.pointer, atHandle, OTIOCString(prefix));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setNameSuffix:(NSString *)suffix error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_image_sequence_reference_set_name_suffix(at.pointer, atHandle, OTIOCString(suffix));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setNumbers:(OTIOImageSequence)numbers error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_image_sequence_reference_set_numbers(at.pointer, atHandle, OTIOImageSequenceToC(numbers));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setTargetURLBase:(NSString *)urlBase error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_image_sequence_reference_set_target_url_base(at.pointer, atHandle, OTIOCString(urlBase));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (nullable NSString *)targetURLBase:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBuffer cURLBase;
    OtioStatus status = otio_image_sequence_reference_target_url_base(at.pointer, atHandle, &cURLBase);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cURLBase);
}

@end

@implementation OTIOItem (OTIOGenerated)

- (BOOL)appendEffect:(OTIOSerializableObject *)effectHandle error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cEffectHandle;
    if (!OTIOAdopt(at, effectHandle, &cEffectHandle, error)) { return NO; }
    OtioStatus status = otio_item_append_effect(at.pointer, atHandle, cEffectHandle);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)appendMarker:(OTIOSerializableObject *)markerHandle error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cMarkerHandle;
    if (!OTIOAdopt(at, markerHandle, &cMarkerHandle, error)) { return NO; }
    OtioStatus status = otio_item_append_marker(at.pointer, atHandle, cMarkerHandle);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)getAvailableRange:(OTIOTimeRange *)outRange error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioTimeRange cRange;
    OtioStatus status = otio_item_available_range(at.pointer, atHandle, &cRange);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outRange) {
        *outRange = OTIOTimeRangeFromC(cRange);
    }
    return YES;
}

- (BOOL)clearColor:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_item_clear_color(at.pointer, atHandle);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)clearSourceRange:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_item_clear_source_range(at.pointer, atHandle);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)getColor:(OTIOColor *)outColor name:(NSString *_Nullable *_Nullable)outName error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioColor cColor;
    OtioBuffer cName;
    OtioStatus status = otio_item_color(at.pointer, atHandle, &cColor, &cName);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outColor) {
        *outColor = OTIOColorFromC(cColor);
    }
    if (outName) {
        *outName = OTIOStringFromBuffer(cName);
    }
    return YES;
}

- (BOOL)getDuration:(OTIORationalTime *)outDuration error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioRationalTime cDuration;
    OtioStatus status = otio_item_duration(at.pointer, atHandle, &cDuration);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outDuration) {
        *outDuration = OTIORationalTimeFromC(cDuration);
    }
    return YES;
}

- (nullable OTIOSerializableObject *)effectAt:(NSUInteger)index error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cEffect;
    OtioStatus status = otio_item_effect_at(at.pointer, atHandle, (size_t)index, &cEffect);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cEffect);
}

- (BOOL)getEffectCount:(NSUInteger *)outCount error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    size_t cCount;
    OtioStatus status = otio_item_effect_count(at.pointer, atHandle, &cCount);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outCount) {
        *outCount = (NSUInteger)cCount;
    }
    return YES;
}

- (BOOL)getEnabled:(BOOL *)outEnabled error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    bool cEnabled;
    OtioStatus status = otio_item_enabled(at.pointer, atHandle, &cEnabled);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outEnabled) {
        *outEnabled = (cEnabled ? YES : NO);
    }
    return YES;
}

- (nullable OTIOSerializableObject *)markerAt:(NSUInteger)index error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cMarker;
    OtioStatus status = otio_item_marker_at(at.pointer, atHandle, (size_t)index, &cMarker);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cMarker);
}

- (BOOL)getMarkerCount:(NSUInteger *)outCount error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    size_t cCount;
    OtioStatus status = otio_item_marker_count(at.pointer, atHandle, &cCount);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outCount) {
        *outCount = (NSUInteger)cCount;
    }
    return YES;
}

+ (nullable OTIOItem *)itemWithName:(NSString *_Nullable)name error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_item_new(at.pointer, OTIOCString(name), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOItem *)OTIOMakeObject(at, cNode);
}

- (BOOL)getRangeInParent:(OTIOTimeRange *)outRange error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioTimeRange cRange;
    OtioStatus status = otio_item_range_in_parent(at.pointer, atHandle, &cRange);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outRange) {
        *outRange = OTIOTimeRangeFromC(cRange);
    }
    return YES;
}

- (nullable OTIOSerializableObject *)removeEffect:(NSUInteger)index error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cEffect;
    OtioStatus status = otio_item_remove_effect(at.pointer, atHandle, (size_t)index, &cEffect);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cEffect);
}

- (nullable OTIOSerializableObject *)removeMarker:(NSUInteger)index error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cMarker;
    OtioStatus status = otio_item_remove_marker(at.pointer, atHandle, (size_t)index, &cMarker);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cMarker);
}

- (BOOL)setColor:(OTIOColor)color name:(NSString *_Nullable)name error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_item_set_color(at.pointer, atHandle, OTIOColorToC(color), OTIOCString(name));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setEnabled:(BOOL)enabled error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_item_set_enabled(at.pointer, atHandle, (enabled ? true : false));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setSourceRange:(OTIOTimeRange)range error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_item_set_source_range(at.pointer, atHandle, OTIOTimeRangeToC(range));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)getSourceRange:(OTIOTimeRange *)outRange error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioTimeRange cRange;
    OtioStatus status = otio_item_source_range(at.pointer, atHandle, &cRange);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outRange) {
        *outRange = OTIOTimeRangeFromC(cRange);
    }
    return YES;
}

- (BOOL)getTrimmedRange:(OTIOTimeRange *)outRange error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioTimeRange cRange;
    OtioStatus status = otio_item_trimmed_range(at.pointer, atHandle, &cRange);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outRange) {
        *outRange = OTIOTimeRangeFromC(cRange);
    }
    return YES;
}

- (BOOL)getTrimmedRangeInParent:(OTIOTimeRange *)outRange error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioTimeRange cRange;
    OtioStatus status = otio_item_trimmed_range_in_parent(at.pointer, atHandle, &cRange);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outRange) {
        *outRange = OTIOTimeRangeFromC(cRange);
    }
    return YES;
}

- (BOOL)getVisibleRange:(OTIOTimeRange *)outRange error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioTimeRange cRange;
    OtioStatus status = otio_item_visible_range(at.pointer, atHandle, &cRange);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outRange) {
        *outRange = OTIOTimeRangeFromC(cRange);
    }
    return YES;
}

@end

@implementation OTIOLinearTimeWarp (OTIOGenerated)

+ (nullable OTIOLinearTimeWarp *)linearTimeWarpWithName:(NSString *_Nullable)name timeScalar:(double)timeScalar error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_linear_time_warp_new(at.pointer, OTIOCString(name), timeScalar, &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOLinearTimeWarp *)OTIOMakeObject(at, cNode);
}

@end

@implementation OTIOMarker (OTIOGenerated)

- (BOOL)getColor:(OTIOColor *)outColor name:(NSString *_Nullable *_Nullable)outName error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioColor cColor;
    OtioBuffer cName;
    OtioStatus status = otio_marker_color(at.pointer, atHandle, &cColor, &cName);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outColor) {
        *outColor = OTIOColorFromC(cColor);
    }
    if (outName) {
        *outName = OTIOStringFromBuffer(cName);
    }
    return YES;
}

- (nullable NSString *)comment:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBuffer cComment;
    OtioStatus status = otio_marker_comment(at.pointer, atHandle, &cComment);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cComment);
}

- (BOOL)getMarkedRange:(OTIOTimeRange *)outRange error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioTimeRange cRange;
    OtioStatus status = otio_marker_marked_range(at.pointer, atHandle, &cRange);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outRange) {
        *outRange = OTIOTimeRangeFromC(cRange);
    }
    return YES;
}

+ (nullable OTIOMarker *)markerWithName:(NSString *_Nullable)name markedRange:(OTIOTimeRange)markedRange error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_marker_new(at.pointer, OTIOCString(name), OTIOTimeRangeToC(markedRange), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOMarker *)OTIOMakeObject(at, cNode);
}

- (BOOL)setColor:(OTIOColor)color name:(NSString *_Nullable)name error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_marker_set_color(at.pointer, atHandle, OTIOColorToC(color), OTIOCString(name));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setComment:(NSString *)comment error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_marker_set_comment(at.pointer, atHandle, OTIOCString(comment));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setMarkedRange:(OTIOTimeRange)range error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_marker_set_marked_range(at.pointer, atHandle, OTIOTimeRangeToC(range));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

@end

@implementation OTIOMediaReference (OTIOGenerated)

- (BOOL)getAvailableImageBounds:(OTIOBox2d *)outBounds error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBox2d cBounds;
    OtioStatus status = otio_media_reference_available_image_bounds(at.pointer, atHandle, &cBounds);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outBounds) {
        *outBounds = OTIOBox2dFromC(cBounds);
    }
    return YES;
}

- (BOOL)getAvailableRange:(OTIOTimeRange *)outRange error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioTimeRange cRange;
    OtioStatus status = otio_media_reference_available_range(at.pointer, atHandle, &cRange);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outRange) {
        *outRange = OTIOTimeRangeFromC(cRange);
    }
    return YES;
}

- (BOOL)clearAvailableImageBounds:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_media_reference_clear_available_image_bounds(at.pointer, atHandle);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)clearAvailableRange:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_media_reference_clear_available_range(at.pointer, atHandle);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setAvailableImageBounds:(OTIOBox2d)bounds error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_media_reference_set_available_image_bounds(at.pointer, atHandle, OTIOBox2dToC(bounds));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setAvailableRange:(OTIOTimeRange)range error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_media_reference_set_available_range(at.pointer, atHandle, OTIOTimeRangeToC(range));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

@end

@implementation OTIOMissingReference (OTIOGenerated)

+ (nullable OTIOMissingReference *)missingReferenceWithName:(NSString *_Nullable)name error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_missing_reference_new(at.pointer, OTIOCString(name), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOMissingReference *)OTIOMakeObject(at, cNode);
}

@end

@implementation OTIOSerializableObject (OTIOGenerated)

- (nullable OTIOSerializableObject *)childAt:(NSUInteger)index error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cChild;
    OtioStatus status = otio_node_child_at(at.pointer, atHandle, (size_t)index, &cChild);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cChild);
}

- (BOOL)getChildCount:(NSUInteger *)outCount error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    size_t cCount;
    OtioStatus status = otio_node_child_count(at.pointer, atHandle, &cCount);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outCount) {
        *outCount = (NSUInteger)cCount;
    }
    return YES;
}

- (nullable NSArray<OTIOSerializableObject *> *)children:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    size_t count = 0;
    OtioStatus sizing = otio_node_children(at.pointer, atHandle, NULL, 0, &count);
    if (!OTIOCheck(sizing, error)) {
        return nil;
    }
    OtioNode *buffer0 = (OtioNode *)calloc(count ? count : 1, sizeof(OtioNode));
    OtioStatus status = otio_node_children(at.pointer, atHandle, buffer0, count, &count);
    if (!OTIOCheck(status, error)) {
        free(buffer0);
        return nil;
    }
    NSMutableArray *buffer0Out = [NSMutableArray arrayWithCapacity:count];
    for (size_t slot = 0; slot < count; slot++) {
        [buffer0Out addObject:OTIOMakeObject(at, buffer0[slot])];
    }
    free(buffer0);
    return buffer0Out;
}

- (BOOL)equals:(OTIOSerializableObject *)right {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    if (!OTIOHere(at, right)) {
        return NO;
    }
    OtioNode cRight = OTIOHandleOf(right);
    bool cReturned = otio_node_equal(atHandle, cRight);
    return (cReturned ? YES : NO);
}

- (nullable NSArray<OTIOSerializableObject *> *)findClips:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    size_t count = 0;
    OtioStatus sizing = otio_node_find_clips(at.pointer, atHandle, NULL, 0, &count);
    if (!OTIOCheck(sizing, error)) {
        return nil;
    }
    OtioNode *buffer0 = (OtioNode *)calloc(count ? count : 1, sizeof(OtioNode));
    OtioStatus status = otio_node_find_clips(at.pointer, atHandle, buffer0, count, &count);
    if (!OTIOCheck(status, error)) {
        free(buffer0);
        return nil;
    }
    NSMutableArray *buffer0Out = [NSMutableArray arrayWithCapacity:count];
    for (size_t slot = 0; slot < count; slot++) {
        [buffer0Out addObject:OTIOMakeObject(at, buffer0[slot])];
    }
    free(buffer0);
    return buffer0Out;
}

- (nullable OTIOSerializableObject *)highestAncestor:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cAncestor;
    OtioStatus status = otio_node_highest_ancestor(at.pointer, atHandle, &cAncestor);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cAncestor);
}

- (BOOL)isNone {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    bool cReturned = otio_node_is_none(atHandle);
    return (cReturned ? YES : NO);
}

- (BOOL)getSchemaKind:(OTIONodeKind *)outKind error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNodeKind cKind;
    OtioStatus status = otio_node_kind(at.pointer, atHandle, &cKind);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outKind) {
        *outKind = (OTIONodeKind)cKind;
    }
    return YES;
}

- (nullable NSString *)name:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBuffer cName;
    OtioStatus status = otio_node_name(at.pointer, atHandle, &cName);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cName);
}

+ (OTIOSerializableObject *)none {
    OtioNode cReturned = otio_node_none();
    return OTIOMakeObject(nil, cReturned);
}

- (BOOL)getOverlapping:(BOOL *)outOverlapping error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    bool cOverlapping;
    OtioStatus status = otio_node_overlapping(at.pointer, atHandle, &cOverlapping);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outOverlapping) {
        *outOverlapping = (cOverlapping ? YES : NO);
    }
    return YES;
}

- (nullable OTIOSerializableObject *)parent:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cParent;
    OtioStatus status = otio_node_parent(at.pointer, atHandle, &cParent);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cParent);
}

- (nullable NSString *)schemaName:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBuffer cName;
    OtioStatus status = otio_node_schema_name(at.pointer, atHandle, &cName);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cName);
}

- (BOOL)getSchemaVersion:(uint32_t *)outVersion error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    uint32_t cVersion;
    OtioStatus status = otio_node_schema_version(at.pointer, atHandle, &cVersion);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outVersion) {
        *outVersion = cVersion;
    }
    return YES;
}

- (BOOL)setName:(NSString *)name error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_node_set_name(at.pointer, atHandle, OTIOCString(name));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (nullable NSString *)toJSON:(NSUInteger)indent error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBuffer cJSON;
    OtioStatus status = otio_node_to_json(at.pointer, atHandle, (size_t)indent, &cJSON);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cJSON);
}

- (BOOL)getTransformedTime:(OTIORationalTime *)outTime time:(OTIORationalTime)time to:(OTIOSerializableObject *)to error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cTo;
    if (!OTIORequireHere(at, to, &cTo, error)) { return NO; }
    OtioRationalTime cTime;
    OtioStatus status = otio_node_transformed_time(at.pointer, OTIORationalTimeToC(time), atHandle, cTo, &cTime);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outTime) {
        *outTime = OTIORationalTimeFromC(cTime);
    }
    return YES;
}

- (BOOL)getTransformedTimeRange:(OTIOTimeRange *)outRange range:(OTIOTimeRange)range to:(OTIOSerializableObject *)to error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cTo;
    if (!OTIORequireHere(at, to, &cTo, error)) { return NO; }
    OtioTimeRange cRange;
    OtioStatus status = otio_node_transformed_time_range(at.pointer, OTIOTimeRangeToC(range), atHandle, cTo, &cRange);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outRange) {
        *outRange = OTIOTimeRangeFromC(cRange);
    }
    return YES;
}

- (BOOL)getVisible:(BOOL *)outVisible error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    bool cVisible;
    OtioStatus status = otio_node_visible(at.pointer, atHandle, &cVisible);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outVisible) {
        *outVisible = (cVisible ? YES : NO);
    }
    return YES;
}

- (BOOL)isLive {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    bool cReturned = otio_document_contains(at.pointer, atHandle);
    return (cReturned ? YES : NO);
}

- (nullable OTIOSerializableObject *)deepClone:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cNode;
    OtioStatus status = otio_document_deep_clone(at.pointer, atHandle, &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cNode);
}

- (BOOL)removeFromTimeline:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_document_remove(at.pointer, atHandle);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)removeFromTimelineRecursive:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_document_remove_recursive(at.pointer, atHandle);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

@end

@implementation OTIOSerializableCollection (OTIOGenerated)

+ (nullable OTIOSerializableCollection *)serializableCollectionWithName:(NSString *_Nullable)name error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_serializable_collection_new(at.pointer, OTIOCString(name), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOSerializableCollection *)OTIOMakeObject(at, cNode);
}

@end

@implementation OTIOStack (OTIOGenerated)

+ (nullable OTIOStack *)stackWithName:(NSString *_Nullable)name error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_stack_new(at.pointer, OTIOCString(name), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOStack *)OTIOMakeObject(at, cNode);
}

@end

@implementation OTIOTimeEffect (OTIOGenerated)

+ (nullable OTIOTimeEffect *)timeEffectWithName:(NSString *_Nullable)name effectName:(NSString *_Nullable)effectName error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_time_effect_new(at.pointer, OTIOCString(name), OTIOCString(effectName), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOTimeEffect *)OTIOMakeObject(at, cNode);
}

@end

@implementation OTIOTimeline (OTIOGenerated)

- (BOOL)clearGlobalStartTime:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_timeline_clear_global_start_time(at.pointer, atHandle);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)getGlobalStartTime:(OTIORationalTime *)outTime error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioRationalTime cTime;
    OtioStatus status = otio_timeline_global_start_time(at.pointer, atHandle, &cTime);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outTime) {
        *outTime = OTIORationalTimeFromC(cTime);
    }
    return YES;
}

+ (nullable OTIOTimeline *)timelineWithName:(NSString *_Nullable)name error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_timeline_new(at.pointer, OTIOCString(name), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOTimeline *)OTIOMakeObject(at, cNode);
}

- (BOOL)setGlobalStartTime:(OTIORationalTime)time error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_timeline_set_global_start_time(at.pointer, atHandle, OTIORationalTimeToC(time));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setTracks:(OTIOSerializableObject *_Nullable)tracks error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cTracks;
    if (!OTIOAdopt(at, tracks, &cTracks, error)) { return NO; }
    OtioStatus status = otio_timeline_set_tracks(at.pointer, atHandle, cTracks);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (nullable OTIOSerializableObject *)tracks:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioNode cTracks;
    OtioStatus status = otio_timeline_tracks(at.pointer, atHandle, &cTracks);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cTracks);
}

@end

@implementation OTIOTrack (OTIOGenerated)

- (nullable NSString *)kind:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBuffer cKind;
    OtioStatus status = otio_track_kind(at.pointer, atHandle, &cKind);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cKind);
}

+ (nullable OTIOTrack *)trackWithName:(NSString *_Nullable)name kind:(NSString *_Nullable)kind error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_track_new(at.pointer, OTIOCString(name), OTIOCString(kind), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOTrack *)OTIOMakeObject(at, cNode);
}

- (BOOL)setKind:(NSString *)kind error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_track_set_kind(at.pointer, atHandle, OTIOCString(kind));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

@end

@implementation OTIOTransition (OTIOGenerated)

- (BOOL)getEnabled:(BOOL *)outEnabled error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    bool cEnabled;
    OtioStatus status = otio_transition_enabled(at.pointer, atHandle, &cEnabled);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outEnabled) {
        *outEnabled = (cEnabled ? YES : NO);
    }
    return YES;
}

- (BOOL)getInOffset:(OTIORationalTime *)outOffset error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioRationalTime cOffset;
    OtioStatus status = otio_transition_in_offset(at.pointer, atHandle, &cOffset);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outOffset) {
        *outOffset = OTIORationalTimeFromC(cOffset);
    }
    return YES;
}

+ (nullable OTIOTransition *)transitionWithName:(NSString *_Nullable)name transitionType:(NSString *_Nullable)transitionType error:(NSError **)error {
    OTIOArena *at = OTIOFreshArena(error);
    if (at == nil) { return nil; }
    OtioNode cNode;
    OtioStatus status = otio_transition_new(at.pointer, OTIOCString(name), OTIOCString(transitionType), &cNode);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return (OTIOTransition *)OTIOMakeObject(at, cNode);
}

- (BOOL)getOutOffset:(OTIORationalTime *)outOffset error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioRationalTime cOffset;
    OtioStatus status = otio_transition_out_offset(at.pointer, atHandle, &cOffset);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outOffset) {
        *outOffset = OTIORationalTimeFromC(cOffset);
    }
    return YES;
}

- (BOOL)setEnabled:(BOOL)enabled error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_transition_set_enabled(at.pointer, atHandle, (enabled ? true : false));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setInOffset:(OTIORationalTime)offset error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_transition_set_in_offset(at.pointer, atHandle, OTIORationalTimeToC(offset));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setOutOffset:(OTIORationalTime)offset error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_transition_set_out_offset(at.pointer, atHandle, OTIORationalTimeToC(offset));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setType:(NSString *)transitionType error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioStatus status = otio_transition_set_type(at.pointer, atHandle, OTIOCString(transitionType));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (nullable NSString *)type:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self, &atHandle);
    OtioBuffer cType;
    OtioStatus status = otio_transition_type(at.pointer, atHandle, &cType);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cType);
}

@end

@implementation OTIOMetadata

- (instancetype)init {
    [self doesNotRecognizeSelector:_cmd];
    return nil;
}

- (OTIOSerializableObject *)object {
    return _object;
}

- (instancetype)initWithObject:(OTIOSerializableObject *)object {
    self = [super init];
    if (self) {
        _object = OTIO_RETAIN(object);
    }
    return self;
}

- (void)dealloc {
#if !__has_feature(objc_arc)
    [_object release];
    [super dealloc];
#endif
}

- (BOOL)clear:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_clear(at.pointer, atHandle);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)getContains:(BOOL *)outContains path:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    bool cContains;
    OtioStatus status = otio_metadata_contains(at.pointer, atHandle, OTIOCString(path), &cContains);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outContains) {
        *outContains = (cContains ? YES : NO);
    }
    return YES;
}

- (BOOL)getBool:(BOOL *)outValue path:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    bool cValue;
    OtioStatus status = otio_metadata_get_bool(at.pointer, atHandle, OTIOCString(path), &cValue);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outValue) {
        *outValue = (cValue ? YES : NO);
    }
    return YES;
}

- (BOOL)getBox2d:(OTIOBox2d *)outValue path:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioBox2d cValue;
    OtioStatus status = otio_metadata_get_box2d(at.pointer, atHandle, OTIOCString(path), &cValue);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outValue) {
        *outValue = OTIOBox2dFromC(cValue);
    }
    return YES;
}

- (BOOL)getColor:(OTIOColor *)outValue name:(NSString *_Nullable *_Nullable)outName path:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioColor cValue;
    OtioBuffer cName;
    OtioStatus status = otio_metadata_get_color(at.pointer, atHandle, OTIOCString(path), &cValue, &cName);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outValue) {
        *outValue = OTIOColorFromC(cValue);
    }
    if (outName) {
        *outName = OTIOStringFromBuffer(cName);
    }
    return YES;
}

- (BOOL)getDouble:(double *)outValue path:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    double cValue;
    OtioStatus status = otio_metadata_get_double(at.pointer, atHandle, OTIOCString(path), &cValue);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outValue) {
        *outValue = cValue;
    }
    return YES;
}

- (BOOL)getInt:(int64_t *)outValue path:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    int64_t cValue;
    OtioStatus status = otio_metadata_get_int(at.pointer, atHandle, OTIOCString(path), &cValue);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outValue) {
        *outValue = cValue;
    }
    return YES;
}

- (nullable OTIOSerializableObject *)getObject:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioNode cValue;
    OtioStatus status = otio_metadata_get_object(at.pointer, atHandle, OTIOCString(path), &cValue);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOMakeObject(at, cValue);
}

- (BOOL)getRationalTime:(OTIORationalTime *)outValue path:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioRationalTime cValue;
    OtioStatus status = otio_metadata_get_rational_time(at.pointer, atHandle, OTIOCString(path), &cValue);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outValue) {
        *outValue = OTIORationalTimeFromC(cValue);
    }
    return YES;
}

- (nullable NSString *)getString:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioBuffer cValue;
    OtioStatus status = otio_metadata_get_string(at.pointer, atHandle, OTIOCString(path), &cValue);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cValue);
}

- (BOOL)getTimeRange:(OTIOTimeRange *)outValue path:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioTimeRange cValue;
    OtioStatus status = otio_metadata_get_time_range(at.pointer, atHandle, OTIOCString(path), &cValue);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outValue) {
        *outValue = OTIOTimeRangeFromC(cValue);
    }
    return YES;
}

- (BOOL)getTimeTransform:(OTIOTimeTransform *)outValue path:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioTimeTransform cValue;
    OtioStatus status = otio_metadata_get_time_transform(at.pointer, atHandle, OTIOCString(path), &cValue);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outValue) {
        *outValue = OTIOTimeTransformFromC(cValue);
    }
    return YES;
}

- (BOOL)getUint:(uint64_t *)outValue path:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    uint64_t cValue;
    OtioStatus status = otio_metadata_get_uint(at.pointer, atHandle, OTIOCString(path), &cValue);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outValue) {
        *outValue = cValue;
    }
    return YES;
}

- (BOOL)getV2d:(OTIOV2d *)outValue path:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioV2d cValue;
    OtioStatus status = otio_metadata_get_v2d(at.pointer, atHandle, OTIOCString(path), &cValue);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outValue) {
        *outValue = OTIOV2dFromC(cValue);
    }
    return YES;
}

- (nullable NSString *)keyAt:(NSString *)path index:(NSUInteger)index error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioBuffer cKey;
    OtioStatus status = otio_metadata_key_at(at.pointer, atHandle, OTIOCString(path), (size_t)index, &cKey);
    if (!OTIOCheck(status, error)) {
        return nil;
    }
    return OTIOStringFromBuffer(cKey);
}

- (BOOL)getKind:(OTIOValueKind *)outKind path:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioValueKind cKind;
    OtioStatus status = otio_metadata_kind(at.pointer, atHandle, OTIOCString(path), &cKind);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outKind) {
        *outKind = (OTIOValueKind)cKind;
    }
    return YES;
}

- (BOOL)getLen:(NSUInteger *)outLen path:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    size_t cLen;
    OtioStatus status = otio_metadata_len(at.pointer, atHandle, OTIOCString(path), &cLen);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    if (outLen) {
        *outLen = (NSUInteger)cLen;
    }
    return YES;
}

- (BOOL)remove:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_remove(at.pointer, atHandle, OTIOCString(path));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setBool:(NSString *)path value:(BOOL)value error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_set_bool(at.pointer, atHandle, OTIOCString(path), (value ? true : false));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setBox2d:(NSString *)path value:(OTIOBox2d)value error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_set_box2d(at.pointer, atHandle, OTIOCString(path), OTIOBox2dToC(value));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setColor:(NSString *)path value:(OTIOColor)value name:(NSString *_Nullable)name error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_set_color(at.pointer, atHandle, OTIOCString(path), OTIOColorToC(value), OTIOCString(name));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setDictionary:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_set_dictionary(at.pointer, atHandle, OTIOCString(path));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setDouble:(NSString *)path value:(double)value error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_set_double(at.pointer, atHandle, OTIOCString(path), value);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setInt:(NSString *)path value:(int64_t)value error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_set_int(at.pointer, atHandle, OTIOCString(path), value);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setNull:(NSString *)path error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_set_null(at.pointer, atHandle, OTIOCString(path));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setObject:(NSString *)path value:(OTIOSerializableObject *)value error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioNode cValue;
    if (!OTIOAdopt(at, value, &cValue, error)) { return NO; }
    OtioStatus status = otio_metadata_set_object(at.pointer, atHandle, OTIOCString(path), cValue);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setRationalTime:(NSString *)path value:(OTIORationalTime)value error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_set_rational_time(at.pointer, atHandle, OTIOCString(path), OTIORationalTimeToC(value));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setString:(NSString *)path value:(NSString *)value error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_set_string(at.pointer, atHandle, OTIOCString(path), OTIOCString(value));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setTimeRange:(NSString *)path value:(OTIOTimeRange)value error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_set_time_range(at.pointer, atHandle, OTIOCString(path), OTIOTimeRangeToC(value));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setTimeTransform:(NSString *)path value:(OTIOTimeTransform)value error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_set_time_transform(at.pointer, atHandle, OTIOCString(path), OTIOTimeTransformToC(value));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setUint:(NSString *)path value:(uint64_t)value error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_set_uint(at.pointer, atHandle, OTIOCString(path), value);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setV2d:(NSString *)path value:(OTIOV2d)value error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_set_v2d(at.pointer, atHandle, OTIOCString(path), OTIOV2dToC(value));
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

- (BOOL)setVector:(NSString *)path len:(NSUInteger)len error:(NSError **)error {
    OtioNode atHandle;
    OTIOArena *at = OTIOLocate(self.object, &atHandle);
    OtioStatus status = otio_metadata_set_vector(at.pointer, atHandle, OTIOCString(path), (size_t)len);
    if (!OTIOCheck(status, error)) {
        return NO;
    }
    return YES;
}

@end

@implementation OTIOSerializableObjectWithMetadata (OTIOMetadata)

- (OTIOMetadata *)metadata {
    return OTIO_AUTORELEASE([[OTIOMetadata alloc] initWithObject:self]);
}

@end
