//! Writing the TypeScript, and the Rust that keeps it honest.
//!
//! Four files come out of here:
//!
//! - `ts/src/generated/types.ts` — the ABI's enums as string-literal unions,
//!   its structs as interfaces, and a reader and a writer for each, built from
//!   the byte offsets [`super::layout`] computed.
//! - `ts/src/generated/raw.ts` — one TypeScript function per C entry point,
//!   doing the marshalling and nothing else. It throws instead of returning a
//!   status, answers `undefined` instead of `OTIO_STATUS_NO_VALUE`, returns
//!   arrays instead of asking twice, and frees every buffer it reads.
//! - `ts/src/generated/api.ts` — the classes, which are what a user touches.
//! - `src/layout.rs` — assertions that the offsets used by the TypeScript are
//!   the offsets Rust actually lays the structs out at, on `wasm32`. They are
//!   `const`, so a wrong number fails the build rather than misreading memory
//!   at run time.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::ts::layout::{Layout, layout_of};
use crate::ts::plan::{Input, Member, Output, Sdk, VALUES, camel, paragraphs, ts_name};
use otio_sdk_model::{Api, CResult, Type};

/// The structs the SDK reads and writes through the module's memory.
///
/// `OtioBuffer` is not here: the runtime owns it, because every buffer has to
/// be freed and no caller should have to remember that. `OtioDocument` is not
/// here either, being opaque.
const CODECS: &[&str] = &[
    "OtioNode",
    "OtioRationalTime",
    "OtioTimeRange",
    "OtioTimeTransform",
    "OtioColor",
    "OtioV2d",
    "OtioBox2d",
    "OtioImageSequence",
    "OtioHandles",
    "OtioReadOptions",
    "OtioWriteOptions",
];

/// The enums the TypeScript surface leaves out, because the WebAssembly
/// build has no file system.
///
/// A bundle is a directory, or an archive of media copied in from files on
/// disk, and the module can reach neither: the library refuses one there. So
/// rather than offer a format, an option or a policy that can only ever be
/// refused, the surface does not have them. See [`NO_FILE_SYSTEM_VARIANTS`]
/// and [`NO_FILE_SYSTEM_FIELDS`].
const NO_FILE_SYSTEM_ENUMS: &[&str] = &["OtioBundleMediaPolicy"];

/// The enum variants the TypeScript surface leaves out, as enum and variant.
const NO_FILE_SYSTEM_VARIANTS: &[(&str, &str)] =
    &[("OtioFormat", "Otioz"), ("OtioFormat", "Otiod")];

/// The struct fields the TypeScript surface leaves out, as struct and field.
///
/// The structs still have them, since their layout is the library's; the
/// writer leaves them zero, which is the library's default.
const NO_FILE_SYSTEM_FIELDS: &[(&str, &str)] = &[
    ("OtioReadOptions", "bundle_extract_path"),
    ("OtioReadOptions", "bundle_absolute_media_paths"),
    ("OtioWriteOptions", "bundle_media_policy"),
    ("OtioWriteOptions", "bundle_media_base_dir"),
];

/// Whether the TypeScript surface leaves out a field of a struct.
fn left_out(structure: &str, field: &str) -> bool {
    NO_FILE_SYSTEM_FIELDS.contains(&(structure, field))
}

/// A file the generator produces.
pub struct Artifact {
    /// Where it goes, relative to the crate root.
    pub path: String,
    /// What is in it.
    pub text: String,
}

/// The note every generated file carries.
pub fn preamble(comment: &str) -> String {
    format!(
        "{comment} Generated by `cargo run -p otio-sdk-gen`.\n\
         {comment} Do not edit: run the generator instead. The signatures and the prose\n\
         {comment} below are read out of `crates/otio-capi/src`, so this file is that\n\
         {comment} crate restated for TypeScript rather than a second description of it.\n\n"
    )
}

/// How the C ABI's own names are spelled in the SDK's prose.
///
/// A doc comment written for C talks about `otio_stack_new` and
/// `OTIO_STATUS_NO_VALUE`. Carried across unchanged, that is prose about a
/// library the reader is not using. This rewrites those names into the
/// TypeScript ones as the comments are emitted, so the SDK documents itself in
/// its own terms.
pub fn glossary(sdk: &Sdk) -> BTreeMap<String, String> {
    let mut names = BTreeMap::new();
    for (owner, class) in &sdk.classes {
        for property in &class.properties {
            for member in std::iter::once(&property.getter)
                .chain(property.setter.iter())
                .chain(property.clear.iter())
            {
                names.insert(member.symbol.clone(), format!("{owner}#{}", property.name));
            }
        }
        for member in class.methods.iter().chain(class.statics.iter()) {
            let spelling = if member.constructs {
                format!("new {owner}()")
            } else if member.statik {
                format!("{owner}.{}()", member.name)
            } else {
                format!("{owner}#{}", member.name)
            };
            names.insert(member.symbol.clone(), spelling);
        }
    }
    for member in &sdk.free {
        let spelling = match &member.namespace {
            Some(namespace) => format!("{namespace}.{}()", member.name),
            None => format!("{}()", member.name),
        };
        names.insert(member.symbol.clone(), spelling);
    }
    // The calls with no member of their own still turn up in the prose.
    for (symbol, spelling) in [
        ("otio_node_none", "undefined"),
        ("otio_node_is_none", "undefined"),
        ("otio_node_equal", "Node#equals"),
        ("otio_buffer_free", "nothing: the SDK frees every buffer"),
        ("otio_document_new", "a class's own constructor"),
        ("otio_document_free", "Timeline#dispose"),
        ("otio_document_from_json", "deserializeJsonFromString()"),
        ("otio_document_to_json", "serializeJsonToString()"),
        ("otio_read_from_bytes", "adapters.readFromBytes()"),
        ("otio_write_to_bytes", "adapters.writeToBytes()"),
        ("otio_document_absorb", "the move that happens on its own"),
    ] {
        names.insert(symbol.to_string(), spelling.to_string());
    }
    names
}

/// Rewrites a doc comment's C names into the SDK's own.
pub fn translate(doc: &[String], names: &BTreeMap<String, String>) -> Vec<String> {
    doc.iter()
        .map(|line| {
            let mut out = line.clone();
            // "Reports `OTIO_STATUS_NO_VALUE` for ..." is about a status code
            // the SDK never hands out: it answers `undefined` instead.
            out = out
                .replace("Reports `OTIO_STATUS_NO_VALUE`", "Answers `undefined`")
                .replace("reports `OTIO_STATUS_NO_VALUE`", "answers `undefined`")
                .replace("Reports OTIO_STATUS_NO_VALUE", "Answers `undefined`")
                .replace("`OTIO_STATUS_NO_VALUE`", "`undefined`");
            // Everything else is a name, longest first so that
            // `otio_item_set_source_range` is not eaten by `otio_item_set`.
            for (symbol, spelling) in names.iter().rev() {
                out = out.replace(symbol, spelling);
            }
            for status in [
                "OTIO_STATUS_OK",
                "OTIO_STATUS_NULL_POINTER",
                "OTIO_STATUS_INVALID_UTF8",
                "OTIO_STATUS_STALE_HANDLE",
                "OTIO_STATUS_INVALID_ARGUMENT",
                "OTIO_STATUS_CORE_ERROR",
                "OTIO_STATUS_TIME_ERROR",
                "OTIO_STATUS_PARSE_ERROR",
                "OTIO_STATUS_UNSUPPORTED",
                "OTIO_STATUS_IO_ERROR",
                "OTIO_STATUS_PANIC",
            ] {
                let spelling = format!(
                    "an `OtioError` whose status is `\"{}\"`",
                    camel(&status.trim_start_matches("OTIO_STATUS_").to_lowercase())
                );
                out = out.replace(&format!("`{status}`"), &spelling);
                out = out.replace(status, &spelling);
            }
            out
        })
        .collect()
}

/// Renders a doc comment as TSDoc, at the given indentation.
///
/// The input is paragraphs, not lines: the description keeps a comment's
/// prose and leaves the question of where to break it to whoever is writing
/// it out. So this is where the breaking happens, to [`WIDTH`], which is the
/// generated file's own column rather than the one the Rust source happened
/// to be wrapped at.
pub fn tsdoc(doc: &[String], indent: &str) -> String {
    if doc.is_empty() {
        return String::new();
    }
    // A rustdoc intra-doc link means nothing in TypeScript, and the brackets
    // read as noise, so the name inside them is kept and the brackets are not.
    let rendered: Vec<String> = doc
        .iter()
        .map(|line| {
            // A doc comment holding a C example holds `/* ... */`, and the
            // second half of that would close the block comment this is
            // being written into. `*\/` is the escape every JSDoc tool
            // renders back as `*/`.
            let mut out = line
                .replace("*/", "*\\/")
                .replace("[`", "`")
                .replace("`]", "`");
            while let Some(start) = out.find("](") {
                match out[start..].find(')') {
                    Some(end) => out.replace_range(start..start + end + 1, ""),
                    None => break,
                }
            }
            out
        })
        .collect();

    let room = WIDTH.saturating_sub(indent.len() + 3).max(24);
    let mut text = format!("{indent}/**\n");
    for (position, paragraph) in rendered.iter().enumerate() {
        if position > 0 {
            let _ = writeln!(text, "{indent} *");
        }
        if paragraph.is_empty() {
            continue;
        }
        for line in wrap(paragraph, room) {
            let _ = writeln!(text, "{indent} * {line}");
        }
    }
    let _ = writeln!(text, "{indent} */");
    text
}

/// How wide a generated line may be, comment markers included.
const WIDTH: usize = 80;

/// Breaks a paragraph into lines of at most `room` characters.
///
/// Greedy, and it never breaks a word: a long URL or a backticked symbol
/// that does not fit goes over the edge rather than being split into
/// something that no longer means what it said.
fn wrap(paragraph: &str, room: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut line = String::new();
    for word in paragraph.split_whitespace() {
        if line.is_empty() {
            line.push_str(word);
        } else if line.chars().count() + 1 + word.chars().count() <= room {
            line.push(' ');
            line.push_str(word);
        } else {
            lines.push(std::mem::take(&mut line));
            line.push_str(word);
        }
    }
    if !line.is_empty() {
        lines.push(line);
    }
    lines
}

/// The TypeScript name of an enum's variant.
pub fn variant_name_of(rust: &str) -> String {
    // `UInt` would come out as `uInt`, which reads as a typo rather than as a
    // word. Every other variant in the ABI lowercases cleanly.
    if rust == "UInt" {
        return "uint".to_string();
    }
    let mut out = String::with_capacity(rust.len());
    for (index, character) in rust.chars().enumerate() {
        if index == 0 {
            out.extend(character.to_lowercase());
        } else {
            out.push(character);
        }
    }
    out
}

/// The unqualified name a struct is written from, for use inside `types.ts`.
fn local_like(ts: &str) -> String {
    if is_value_class(ts) {
        format!("{ts}Like")
    } else {
        ts.to_string()
    }
}

/// Whether a struct is one of the classes with methods rather than a plain
/// bag of fields.
fn is_value_class(name: &str) -> bool {
    VALUES.contains(&ts_name(name).as_str())
}

/// The TypeScript type a struct is written from, qualified by the module it
/// is declared in.
pub fn like(name: &str) -> String {
    let ts = ts_name(name);
    if is_value_class(&ts) {
        format!("values.{ts}Like")
    } else {
        format!("types.{ts}")
    }
}

/// The TypeScript type a value is read back as, qualified by its module.
pub fn qualified(name: &str) -> String {
    let ts = ts_name(name);
    if is_value_class(&ts) {
        format!("values.{ts}")
    } else {
        format!("types.{ts}")
    }
}

/// Writes `ts/src/generated/types.ts`.
///
/// # Errors
///
/// Fails if a struct's layout cannot be computed.
pub fn types(api: &Api) -> Result<Artifact, String> {
    let mut text = preamble("//");
    text.push_str("import { readCString, type Stack } from \"../runtime.js\";\n");
    text.push_str(
        "import {\n\
         \x20 RationalTime,\n\
         \x20 TimeRange,\n\
         \x20 TimeTransform,\n\
         \x20 type RationalTimeLike,\n\
         \x20 type TimeRangeLike,\n\
         \x20 type TimeTransformLike,\n\
         } from \"./values.js\";\n\n",
    );

    // Enums, as string-literal unions with the codes they cross the boundary
    // as.
    for enumeration in &api.enums {
        if NO_FILE_SYSTEM_ENUMS.contains(&enumeration.name.as_str()) {
            continue;
        }
        let variants: Vec<_> = enumeration
            .variants
            .iter()
            .filter(|variant| {
                !NO_FILE_SYSTEM_VARIANTS
                    .contains(&(enumeration.name.as_str(), variant.name.as_str()))
            })
            .collect();
        let ts = ts_name(&enumeration.name);
        text.push_str(&tsdoc(&paragraphs(&enumeration.docs), ""));
        let _ = writeln!(text, "export type {ts} =");
        for variant in &variants {
            text.push_str(&tsdoc(&paragraphs(&variant.docs), "  "));
            let _ = writeln!(text, "  | \"{}\"", variant_name_of(&variant.name));
        }
        text.truncate(text.trim_end().len());
        text.push_str(";\n\n");

        let lower = camel(&to_snake(&ts));
        let _ = writeln!(text, "const {lower}Codes: Record<{ts}, number> = {{");
        for variant in &variants {
            let _ = writeln!(
                text,
                "  {}: {},",
                variant_name_of(&variant.name),
                variant.value
            );
        }
        text.push_str("};\n\n");
        let _ = writeln!(
            text,
            "const {lower}Names = new Map<number, {ts}>(\n  Object.entries({lower}Codes).map(([name, code]) => [code, name as {ts}]),\n);\n"
        );
        let _ = writeln!(
            text,
            "/** Turns a {ts} into the number the C ABI spells it with. */\n\
             export function encode{ts}(value: {ts}): number {{\n\
             \x20 const code = {lower}Codes[value];\n\
             \x20 if (code === undefined) {{\n\
             \x20   throw new TypeError(`{ts} has no value ${{JSON.stringify(value)}}`);\n\
             \x20 }}\n\
             \x20 return code;\n\
             }}\n"
        );
        let _ = writeln!(
            text,
            "/** Turns the C ABI's number for a {ts} back into its name. */\n\
             export function decode{ts}(code: number): {ts} {{\n\
             \x20 const name = {lower}Names.get(code);\n\
             \x20 if (name === undefined) {{\n\
             \x20   throw new RangeError(`{ts} has no variant numbered ${{code}}`);\n\
             \x20 }}\n\
             \x20 return name;\n\
             }}\n"
        );
    }

    // Structs, as interfaces and codecs.
    for name in CODECS {
        let layout = layout_of(name, api)?;
        let record = api
            .structure(name)
            .ok_or_else(|| format!("`{name}` is not a struct of the interface"))?;
        let ts = ts_name(name);

        // A value class declares its own shape in `values.ts`, where its
        // methods are; here it needs only the codec.
        if !is_value_class(&ts) {
            text.push_str(&tsdoc(&paragraphs(&record.docs), ""));
            let _ = writeln!(text, "export interface {ts} {{");
            for field in &record.fields {
                if left_out(name, &field.name) {
                    continue;
                }
                let placed = layout
                    .fields
                    .iter()
                    .find(|placed| placed.name == field.name)
                    .ok_or_else(|| format!("`{name}` lost its field `{}`", field.name))?;
                let Some(kind) = field_type(&placed.kind) else {
                    // A field that is a pointer to text is written from the
                    // scratch stack and never read back.
                    let _ = writeln!(
                        text,
                        "{}  {}?: string;",
                        tsdoc(&paragraphs(&field.docs), "  "),
                        camel(&field.name)
                    );
                    continue;
                };
                text.push_str(&tsdoc(&paragraphs(&field.docs), "  "));
                let _ = writeln!(text, "  {}: {kind};", camel(&field.name));
            }
            text.push_str("}\n\n");
        }

        text.push_str(&writer(&layout, &ts, name)?);
        if readable(&layout) {
            text.push_str(&reader(&layout, &ts, name)?);
        }
        let _ = writeln!(
            text,
            "/** How many bytes a {ts} takes in the module's memory. */\n\
             export const sizeOf{ts} = {};\n",
            layout.size.size
        );
        let _ = writeln!(
            text,
            "/** What address a {ts} has to start at. */\n\
             export const alignOf{ts} = {};\n",
            layout.size.alignment
        );
    }

    Ok(Artifact {
        path: "ts/src/generated/types.ts".to_string(),
        text,
    })
}

/// Whether every field of a struct can be read back out of memory.
///
/// A pointer to text counts: the only structs the library hands back by value
/// are the two `*_options_default` calls, whose text fields are null, and a
/// null pointer reads back as `undefined`. A pointer to anything else has no
/// reading that would mean something in TypeScript.
fn readable(layout: &Layout) -> bool {
    layout.fields.iter().all(|field| match &field.kind {
        // A pointer to text is readable: the reader copies the string out.
        // Any other pointer is a borrow the SDK cannot make sense of.
        Type::Bytes | Type::Document | Type::List(_) => false,
        _ => true,
    })
}

/// The TypeScript type of a struct's field, or `None` for a pointer to text.
fn field_type(kind: &Type) -> Option<String> {
    Some(match kind {
        Type::Bool => "boolean".to_string(),
        Type::Double | Type::Int32 | Type::Uint32 | Type::Int64 | Type::Uint64 | Type::Size => {
            "number".to_string()
        }
        Type::Enum(named) | Type::Struct(named) => ts_name(named),
        Type::Node => ts_name("OtioNode"),
        Type::Text | Type::Bytes | Type::Document | Type::List(_) => return None,
    })
}

/// Emits the function that writes a struct into the module's memory.
fn writer(layout: &Layout, ts: &str, structure: &str) -> Result<String, String> {
    let mut text = String::new();
    let _ = writeln!(
        text,
        "/** Writes a {ts} into the module's memory at `at`. */\n\
         export function write{ts}(stack: Stack, at: number, value: {}): void {{",
        local_like(ts)
    );
    if layout.fields.is_empty() {
        text.push_str("  void stack;\n  void at;\n  void value;\n");
    }
    for field in &layout.fields {
        let name = camel(&field.name);
        let at = format!("at + {}", field.offset);
        if left_out(structure, &field.name) {
            // Not in the interface, so it is written as zero: the library's
            // default, and for a pointer a null one.
            let line = match &field.kind {
                Type::Bool => format!("  stack.view.setUint8({at}, 0);"),
                Type::Enum(_) => format!("  stack.view.setInt32({at}, 0, true);"),
                Type::Text => format!("  stack.view.setUint32({at}, 0, true);"),
                other => {
                    return Err(format!(
                        "`{}` leaves out a `{}`, which has no zero here",
                        layout.name,
                        other.c_name()
                    ));
                }
            };
            text.push_str(&line);
            text.push('\n');
            continue;
        }
        let line = match &field.kind {
            Type::Double => format!("  stack.view.setFloat64({at}, value.{name}, true);"),
            Type::Bool => format!("  stack.view.setUint8({at}, value.{name} ? 1 : 0);"),
            Type::Int32 => format!("  stack.view.setInt32({at}, value.{name}, true);"),
            Type::Uint32 | Type::Size => {
                format!("  stack.view.setUint32({at}, value.{name}, true);")
            }
            Type::Int64 => format!("  stack.view.setBigInt64({at}, BigInt(value.{name}), true);"),
            Type::Uint64 => format!("  stack.view.setBigUint64({at}, BigInt(value.{name}), true);"),
            Type::Text => format!(
                "  stack.view.setUint32({at}, value.{name} === undefined ? 0 : stack.text(value.{name}), true);"
            ),
            Type::Enum(named) => format!(
                "  stack.view.setInt32({at}, encode{}(value.{name}), true);",
                ts_name(named)
            ),
            Type::Struct(named) => {
                format!("  write{}(stack, {at}, value.{name});", ts_name(named))
            }
            Type::Node => format!("  writeNode(stack, {at}, value.{name});"),
            other => {
                return Err(format!("`{}` holds a `{}`", layout.name, other.c_name()));
            }
        };
        text.push_str(&line);
        text.push('\n');
    }
    text.push_str("}\n\n");
    Ok(text)
}

/// Emits the function that reads a struct back out of the module's memory.
fn reader(layout: &Layout, ts: &str, structure: &str) -> Result<String, String> {
    let mut fields = Vec::new();
    for field in &layout.fields {
        if left_out(structure, &field.name) {
            continue;
        }
        let at = format!("at + {}", field.offset);
        let value = match &field.kind {
            Type::Double => format!("view.getFloat64({at}, true)"),
            Type::Bool => format!("view.getUint8({at}) !== 0"),
            Type::Int32 => format!("view.getInt32({at}, true)"),
            Type::Uint32 | Type::Size => format!("view.getUint32({at}, true)"),
            Type::Int64 => format!("Number(view.getBigInt64({at}, true))"),
            Type::Uint64 => format!("Number(view.getBigUint64({at}, true))"),
            Type::Enum(named) => {
                format!("decode{}(view.getInt32({at}, true))", ts_name(named))
            }
            Type::Struct(named) => format!("read{}(view, {at})", ts_name(named)),
            Type::Node => format!("readNode(view, {at})"),
            Type::Text => {
                format!("readCString(view.getUint32({at}, true))")
            }
            other => {
                return Err(format!("`{}` holds a `{}`", layout.name, other.c_name()));
            }
        };
        fields.push((camel(&field.name), value));
    }

    let mut text = String::new();
    let _ = writeln!(
        text,
        "/** Reads a {ts} out of the module's memory at `at`. */\n\
         export function read{ts}(view: DataView, at: number): {ts} {{"
    );
    if is_value_class(ts) {
        let arguments: Vec<String> = fields.iter().map(|(_, value)| value.clone()).collect();
        let _ = writeln!(
            text,
            "  return new {ts}(\n    {},\n  );",
            arguments.join(",\n    ")
        );
    } else {
        let _ = writeln!(text, "  return {{");
        for (name, value) in &fields {
            let _ = writeln!(text, "    {name}: {value},");
        }
        let _ = writeln!(text, "  }};");
    }
    text.push_str("}\n\n");
    Ok(text)
}

/// Turns a `PascalCase` name into `snake_case`.
fn to_snake(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for (index, character) in name.chars().enumerate() {
        if character.is_uppercase() && index > 0 {
            out.push('_');
        }
        out.extend(character.to_lowercase());
    }
    out
}

/// Writes `src/layout.rs`: the assertions that hold the offsets above honest.
///
/// # Errors
///
/// Fails if a struct's layout cannot be computed.
pub fn assertions(api: &Api) -> Result<Artifact, String> {
    let mut text = preamble("//");
    text.push_str(
        "//! Proof that the byte offsets the TypeScript uses are the ones Rust\n\
         //! lays these structs out at.\n\
         //!\n\
         //! The generator works the offsets out itself, from `wasm32`'s rules rather\n\
         //! than the host's, because a pointer and a `usize` are four bytes there and\n\
         //! eight here. Getting one wrong would not fail anywhere: the TypeScript\n\
         //! would read the wrong part of the right struct and hand back a plausible\n\
         //! number. So the generator also writes these, and a wrong offset stops the\n\
         //! build.\n\n\
         #![cfg(target_arch = \"wasm32\")]\n\n\
         use core::mem::{align_of, offset_of, size_of};\n\n\
         use otio::{\n",
    );
    for name in CODECS {
        let _ = writeln!(text, "    {name},");
    }
    text.push_str("};\n\nconst _: () = {\n");
    for name in CODECS {
        let layout = layout_of(name, api)?;
        let _ = writeln!(
            text,
            "    assert!(size_of::<{name}>() == {});",
            layout.size.size
        );
        let _ = writeln!(
            text,
            "    assert!(align_of::<{name}>() == {});",
            layout.size.alignment
        );
        for field in &layout.fields {
            let _ = writeln!(
                text,
                "    assert!(offset_of!({name}, {}) == {});",
                field.name, field.offset
            );
        }
        text.push('\n');
    }
    text.push_str("};\n");

    Ok(Artifact {
        path: "src/layout.rs".to_string(),
        text,
    })
}

/// What a member answers with, in TypeScript.
pub fn result_type(member: &Member) -> Result<String, String> {
    let mut base = if member.list {
        match member.outputs.as_slice() {
            [single] => format!("{}[]", output_type(single)),
            several => format!(
                "{{ {} }}",
                several
                    .iter()
                    .map(|output| format!("{}: {}[]", camel(output.name()), output_type(output)))
                    .collect::<Vec<_>>()
                    .join("; ")
            ),
        }
    } else {
        match member.outputs.as_slice() {
            // A fallible call with nothing to report answers nothing: its
            // status became a thrown error on the way through.
            [] if member.fallible => "void".to_string(),
            [] => direct_type(&member.returns)?,
            [single] => output_type(single),
            several => format!(
                "{{ {} }}",
                several
                    .iter()
                    .map(|output| format!("{}: {}", camel(output.name()), output_type(output)))
                    .collect::<Vec<_>>()
                    .join("; ")
            ),
        }
    };
    if member.no_value {
        base.push_str(" | undefined");
    }
    Ok(base)
}

/// The TypeScript type of a value returned directly rather than through an
/// out-parameter.
fn direct_type(result: &CResult) -> Result<String, String> {
    let kind = match result {
        CResult::Void => return Ok("void".to_string()),
        // Text the library owns forever, which the binding copies out.
        CResult::StaticText => return Ok("string".to_string()),
        // A status never reaches the surface: it became a thrown error.
        CResult::Status => return Ok("void".to_string()),
        CResult::Value(kind) => kind,
    };
    Ok(match kind {
        Type::Bool => "boolean".to_string(),
        Type::Double | Type::Int32 | Type::Uint32 | Type::Int64 | Type::Uint64 | Type::Size => {
            "number".to_string()
        }
        Type::Enum(named) => format!("types.{}", ts_name(named)),
        Type::Struct(named) => qualified(named),
        Type::Node => qualified("OtioNode"),
        Type::Text => "string".to_string(),
        // A document is a pointer into the module's memory. The layers above
        // give it a name; here it is the number it is.
        Type::Document => "number".to_string(),
        other => return Err(format!("nothing returns a `{}`", other.c_name())),
    })
}

/// The TypeScript type of one result.
pub fn output_type(output: &Output) -> String {
    match output {
        Output::Number { .. } => "number".to_string(),
        Output::Boolean { .. } => "boolean".to_string(),
        Output::Enumeration { ts, .. } => format!("types.{ts}"),
        Output::Record { ts, .. } => qualified(&format!("Otio{ts}")),
        Output::Text { .. } => "string".to_string(),
        Output::Bytes { .. } => "Uint8Array".to_string(),
        Output::Node { .. } => "types.NodeHandle".to_string(),
        Output::Document { .. } => "number".to_string(),
    }
}

/// The TypeScript type of one argument.
pub fn input_type(input: &Input) -> String {
    match input {
        Input::Number { .. } => "number".to_string(),
        Input::Boolean { .. } => "boolean".to_string(),
        Input::Enumeration { ts, .. } => format!("types.{ts}"),
        Input::Record { ts, .. } => like(&format!("Otio{ts}")),
        Input::Text { .. } => "string".to_string(),
        Input::Bytes { .. } => "Uint8Array".to_string(),
        Input::Node { .. } => "types.NodeHandle".to_string(),
        Input::NodeList { .. } => "readonly types.NodeHandle[]".to_string(),
    }
}

mod body;

pub use body::{api, exports, raw, values};
