// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

//! The library's own interface, declared rather than translated.
//!
//! There is no `@cImport` here and no header is read at build time. The
//! description this is generated from carries every type and every struct
//! layout, so the declarations are written out directly and the C compiler is
//! left out of the loop entirely: the package builds wherever Zig builds, and
//! cross-compiling needs nothing but the static library.
//!
//! Nothing here is part of the SDK's surface. It is `pub` because the rest of
//! the package calls it.

const std = @import("std");
const values = @import("values.zig");
const enums = @import("enums.zig");

/// The arena a timeline's objects live in.
pub const Document = @import("document.zig").Document;

/// A handle to an object in a document: where it sits in the arena, and
/// which occupant of that slot it is. A handle to something that has been
/// removed fails a lookup rather than reaching whatever took its place.
pub const NodeHandle = extern struct {
    index: u32,
    generation: u32,
};

/// A run of bytes the library owns until `otio_buffer_free` is called on
/// it. The SDK copies out of one and frees it before its caller sees
/// anything.
pub const Buffer = extern struct {
    data: ?[*]const u8,
    len: usize,
};

const Box2d = values.Box2d;
const Color = values.Color;
const Handles = values.Handles;
const ImageSequence = values.ImageSequence;
const RationalTime = values.RationalTime;
const ReadOptions = values.ReadOptions;
const TimeRange = values.TimeRange;
const TimeTransform = values.TimeTransform;
const V2d = values.V2d;
const WriteOptions = values.WriteOptions;
const DropFrame = enums.DropFrame;
const EdlStyle = enums.EdlStyle;
const Format = enums.Format;
const MissingFramePolicy = enums.MissingFramePolicy;
const NeighborGapPolicy = enums.NeighborGapPolicy;
const NodeKind = enums.NodeKind;
const ReferencePoint = enums.ReferencePoint;
const Status = enums.Status;
const ValueKind = enums.ValueKind;

comptime {
    if (@alignOf(f64) != 8 or @alignOf(u64) != 8) @compileError(
        "otio: the struct layouts in this package were computed for an ABI " ++
            "that aligns 64-bit scalars to eight bytes. This target does not " ++
            "(i386 is the usual one: its System V ABI aligns a double to " ++
            "four), so the C library lays these structs out differently. " ++
            "Supported targets are the 64-bit ones and wasm32.",
    );
}

comptime {
    const pointers = @sizeOf(usize);
    std.debug.assert(@sizeOf(Buffer) == if (pointers == 4) 8 else 16);
    std.debug.assert(@alignOf(Buffer) == if (pointers == 4) 4 else 8);
    std.debug.assert(@offsetOf(Buffer, "data") == 0);
    std.debug.assert(@offsetOf(Buffer, "len") == if (pointers == 4) 4 else 8);
}

comptime {
    std.debug.assert(@sizeOf(NodeHandle) == 8);
    std.debug.assert(@alignOf(NodeHandle) == 4);
    std.debug.assert(@offsetOf(NodeHandle, "index") == 0);
    std.debug.assert(@offsetOf(NodeHandle, "generation") == 4);
}

pub extern fn otio_read_from_bytes(format: Format, data: ?[*]const u8, len: usize, options: ?*const ReadOptions, out_document: *?*Document, out_error: ?*Buffer) Status;
pub extern fn otio_read_from_file(format: Format, path: [*:0]const u8, options: ?*const ReadOptions, out_document: *?*Document, out_error: ?*Buffer) Status;
pub extern fn otio_read_options_default() ReadOptions;
pub extern fn otio_write_options_default() WriteOptions;
pub extern fn otio_write_to_bytes(format: Format, source: *Document, options: ?*const WriteOptions, out_bytes: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_write_to_file(format: Format, source: *Document, path: [*:0]const u8, options: ?*const WriteOptions, out_error: ?*Buffer) Status;
pub extern fn otio_algorithm_flatten_stack(target: *Document, stack: NodeHandle, out_track: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_algorithm_flatten_tracks(target: *Document, tracks: ?[*]const NodeHandle, count: usize, out_track: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_algorithm_track_trimmed_to_range(target: *Document, track: NodeHandle, trim_range: TimeRange, out_track: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_clip_active_media_reference_key(source: *Document, node_handle: NodeHandle, out_key: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_clip_media_reference(source: *Document, node_handle: NodeHandle, key: ?[*:0]const u8, out_reference: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_clip_media_reference_count(source: *Document, node_handle: NodeHandle, out_count: *usize, out_error: ?*Buffer) Status;
pub extern fn otio_clip_media_reference_key_at(source: *Document, node_handle: NodeHandle, index: usize, out_key: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_clip_new(target: *Document, name: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_clip_remove_media_reference(target: *Document, node_handle: NodeHandle, key: [*:0]const u8, out_reference: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_clip_set_active_media_reference_key(target: *Document, node_handle: NodeHandle, key: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_clip_set_media_reference(target: *Document, node_handle: NodeHandle, key: [*:0]const u8, reference: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_composable_new(target: *Document, name: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_composition_append_child(target: *Document, parent: NodeHandle, child: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_composition_child_at_time(source: *Document, parent: NodeHandle, time: RationalTime, shallow: bool, out_child: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_composition_children_in_range(source: *Document, parent: NodeHandle, search_range: TimeRange, out_nodes: ?[*]NodeHandle, capacity: usize, out_count: *usize, out_error: ?*Buffer) Status;
pub extern fn otio_composition_clear_children(target: *Document, parent: NodeHandle, out_nodes: ?[*]NodeHandle, capacity: usize, out_count: *usize, out_error: ?*Buffer) Status;
pub extern fn otio_composition_detach_child(target: *Document, parent: NodeHandle, child: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_composition_find_children_of_kind(source: *Document, parent: NodeHandle, kind: NodeKind, search_range: ?*const TimeRange, shallow: bool, out_nodes: ?[*]NodeHandle, capacity: usize, out_count: *usize, out_error: ?*Buffer) Status;
pub extern fn otio_composition_handles_of_child(source: *Document, parent: NodeHandle, child: NodeHandle, out_handles: *Handles, out_error: ?*Buffer) Status;
pub extern fn otio_composition_has_child(source: *Document, parent: NodeHandle, child: NodeHandle, out_has: *bool, out_error: ?*Buffer) Status;
pub extern fn otio_composition_index_of_child(source: *Document, parent: NodeHandle, child: NodeHandle, out_index: *usize, out_error: ?*Buffer) Status;
pub extern fn otio_composition_insert_child(target: *Document, parent: NodeHandle, index: i64, child: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_composition_is_parent_of(source: *Document, parent: NodeHandle, other: NodeHandle, out_is: *bool, out_error: ?*Buffer) Status;
pub extern fn otio_composition_neighbors_of(target: *Document, parent: NodeHandle, child: NodeHandle, policy: NeighborGapPolicy, out_before: *NodeHandle, out_after: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_composition_new(target: *Document, name: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_composition_range_of_child(source: *Document, parent: NodeHandle, child: NodeHandle, out_range: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_composition_range_of_child_at_index(source: *Document, parent: NodeHandle, index: i64, out_range: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_composition_ranges_of_children(source: *Document, parent: NodeHandle, out_nodes: ?[*]NodeHandle, out_ranges: ?[*]TimeRange, capacity: usize, out_count: *usize, out_error: ?*Buffer) Status;
pub extern fn otio_composition_remove_child(target: *Document, parent: NodeHandle, index: i64, out_child: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_composition_trim_child_range(source: *Document, parent: NodeHandle, child_range: TimeRange, out_range: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_composition_trimmed_range_of_child(source: *Document, parent: NodeHandle, child: NodeHandle, out_range: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_composition_trimmed_range_of_child_at_index(source: *Document, parent: NodeHandle, index: i64, out_range: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_document_absorb(target: *Document, source: *?*Document, out_from: ?[*]NodeHandle, out_to: ?[*]NodeHandle, capacity: usize, out_count: *usize, out_error: ?*Buffer) Status;
pub extern fn otio_document_clone(source: *Document, out_document: *?*Document, out_error: ?*Buffer) Status;
pub extern fn otio_document_contains(source: *Document, node: NodeHandle) bool;
pub extern fn otio_document_deep_clone(target: *Document, node: NodeHandle, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_document_free(document: *Document) void;
pub extern fn otio_document_from_json(json: [*:0]const u8, out_document: *?*Document, out_error: ?*Buffer) Status;
pub extern fn otio_document_new() ?*Document;
pub extern fn otio_document_node_count(source: *Document) usize;
pub extern fn otio_document_read_from_file(path: [*:0]const u8, out_document: *?*Document, out_error: ?*Buffer) Status;
pub extern fn otio_document_remove(target: *Document, node: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_document_remove_recursive(target: *Document, node: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_document_root(source: *Document, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_document_set_root(target: *Document, node: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_document_to_json(source: *Document, indent: usize, out_json: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_document_write_to_file(source: *Document, path: [*:0]const u8, indent: usize, out_error: ?*Buffer) Status;
pub extern fn otio_edit_fill(target: *Document, item: NodeHandle, track: NodeHandle, track_time: RationalTime, reference_point: ReferencePoint, out_error: ?*Buffer) Status;
pub extern fn otio_edit_insert(target: *Document, item: NodeHandle, composition: NodeHandle, time: RationalTime, remove_transitions: bool, fill_template: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_edit_overwrite(target: *Document, item: NodeHandle, composition: NodeHandle, range: TimeRange, remove_transitions: bool, fill_template: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_edit_remove(target: *Document, composition: NodeHandle, time: RationalTime, fill: bool, fill_template: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_edit_ripple(target: *Document, item: NodeHandle, delta_in: RationalTime, delta_out: RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_edit_roll(target: *Document, item: NodeHandle, delta_in: RationalTime, delta_out: RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_edit_slice(target: *Document, composition: NodeHandle, time: RationalTime, remove_transitions: bool, out_error: ?*Buffer) Status;
pub extern fn otio_edit_slide(target: *Document, item: NodeHandle, delta: RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_edit_slip(target: *Document, item: NodeHandle, delta: RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_edit_trim(target: *Document, item: NodeHandle, delta_in: RationalTime, delta_out: RationalTime, fill_template: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_effect_effect_name(source: *Document, node_handle: NodeHandle, out_name: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_effect_enabled(source: *Document, node_handle: NodeHandle, out_enabled: *bool, out_error: ?*Buffer) Status;
pub extern fn otio_effect_new(target: *Document, name: ?[*:0]const u8, effect_name: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_effect_set_effect_name(target: *Document, node_handle: NodeHandle, effect_name: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_effect_set_enabled(target: *Document, node_handle: NodeHandle, enabled: bool, out_error: ?*Buffer) Status;
pub extern fn otio_effect_set_time_scalar(target: *Document, node_handle: NodeHandle, scalar: f64, out_error: ?*Buffer) Status;
pub extern fn otio_effect_time_scalar(source: *Document, node_handle: NodeHandle, out_scalar: *f64, out_error: ?*Buffer) Status;
pub extern fn otio_external_reference_new(target: *Document, name: ?[*:0]const u8, target_url: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_external_reference_set_target_url(target: *Document, node_handle: NodeHandle, url: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_external_reference_target_url(source: *Document, node_handle: NodeHandle, out_url: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_format_from_suffix(suffix: [*:0]const u8, out_format: *Format, out_error: ?*Buffer) Status;
pub extern fn otio_format_name(format: Format) [*:0]const u8;
pub extern fn otio_freeze_frame_new(target: *Document, name: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_gap_new(target: *Document, name: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_generator_reference_kind(source: *Document, node_handle: NodeHandle, out_kind: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_generator_reference_new(target: *Document, name: ?[*:0]const u8, generator_kind: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_generator_reference_set_kind(target: *Document, node_handle: NodeHandle, kind: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_image_sequence_reference_name_prefix(source: *Document, node_handle: NodeHandle, out_prefix: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_image_sequence_reference_name_suffix(source: *Document, node_handle: NodeHandle, out_suffix: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_image_sequence_reference_new(target: *Document, name: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_image_sequence_reference_numbers(source: *Document, node_handle: NodeHandle, out_numbers: *ImageSequence, out_error: ?*Buffer) Status;
pub extern fn otio_image_sequence_reference_set_name_prefix(target: *Document, node_handle: NodeHandle, prefix: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_image_sequence_reference_set_name_suffix(target: *Document, node_handle: NodeHandle, suffix: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_image_sequence_reference_set_numbers(target: *Document, node_handle: NodeHandle, numbers: ImageSequence, out_error: ?*Buffer) Status;
pub extern fn otio_image_sequence_reference_set_target_url_base(target: *Document, node_handle: NodeHandle, url_base: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_image_sequence_reference_target_url_base(source: *Document, node_handle: NodeHandle, out_url_base: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_item_append_effect(target: *Document, node_handle: NodeHandle, effect_handle: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_item_append_marker(target: *Document, node_handle: NodeHandle, marker_handle: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_item_available_range(source: *Document, node_handle: NodeHandle, out_range: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_item_clear_color(target: *Document, node_handle: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_item_clear_source_range(target: *Document, node_handle: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_item_color(source: *Document, node_handle: NodeHandle, out_color: *Color, out_name: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_item_duration(source: *Document, node_handle: NodeHandle, out_duration: *RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_item_effect_at(source: *Document, node_handle: NodeHandle, index: usize, out_effect: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_item_effect_count(source: *Document, node_handle: NodeHandle, out_count: *usize, out_error: ?*Buffer) Status;
pub extern fn otio_item_enabled(source: *Document, node_handle: NodeHandle, out_enabled: *bool, out_error: ?*Buffer) Status;
pub extern fn otio_item_marker_at(source: *Document, node_handle: NodeHandle, index: usize, out_marker: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_item_marker_count(source: *Document, node_handle: NodeHandle, out_count: *usize, out_error: ?*Buffer) Status;
pub extern fn otio_item_new(target: *Document, name: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_item_range_in_parent(source: *Document, node_handle: NodeHandle, out_range: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_item_remove_effect(target: *Document, node_handle: NodeHandle, index: usize, out_effect: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_item_remove_marker(target: *Document, node_handle: NodeHandle, index: usize, out_marker: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_item_set_color(target: *Document, node_handle: NodeHandle, color: Color, name: ?[*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_item_set_enabled(target: *Document, node_handle: NodeHandle, enabled: bool, out_error: ?*Buffer) Status;
pub extern fn otio_item_set_source_range(target: *Document, node_handle: NodeHandle, range: TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_item_source_range(source: *Document, node_handle: NodeHandle, out_range: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_item_trimmed_range(source: *Document, node_handle: NodeHandle, out_range: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_item_trimmed_range_in_parent(source: *Document, node_handle: NodeHandle, out_range: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_item_visible_range(source: *Document, node_handle: NodeHandle, out_range: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_buffer_free(buffer: Buffer) void;
pub extern fn otio_default_epsilon_s() f64;
pub extern fn otio_default_indent() usize;
pub extern fn otio_status_name(status: Status) [*:0]const u8;
pub extern fn otio_version() [*:0]const u8;
pub extern fn otio_linear_time_warp_new(target: *Document, name: ?[*:0]const u8, time_scalar: f64, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_marker_color(source: *Document, node_handle: NodeHandle, out_color: *Color, out_name: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_marker_comment(source: *Document, node_handle: NodeHandle, out_comment: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_marker_marked_range(source: *Document, node_handle: NodeHandle, out_range: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_marker_new(target: *Document, name: ?[*:0]const u8, marked_range: TimeRange, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_marker_set_color(target: *Document, node_handle: NodeHandle, color: Color, name: ?[*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_marker_set_comment(target: *Document, node_handle: NodeHandle, comment: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_marker_set_marked_range(target: *Document, node_handle: NodeHandle, range: TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_media_reference_available_image_bounds(source: *Document, node_handle: NodeHandle, out_bounds: *Box2d, out_error: ?*Buffer) Status;
pub extern fn otio_media_reference_available_range(source: *Document, node_handle: NodeHandle, out_range: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_media_reference_clear_available_image_bounds(target: *Document, node_handle: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_media_reference_clear_available_range(target: *Document, node_handle: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_media_reference_set_available_image_bounds(target: *Document, node_handle: NodeHandle, bounds: Box2d, out_error: ?*Buffer) Status;
pub extern fn otio_media_reference_set_available_range(target: *Document, node_handle: NodeHandle, range: TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_clear(target: *Document, node_handle: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_contains(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_contains: *bool, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_get_bool(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_value: *bool, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_get_box2d(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_value: *Box2d, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_get_color(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_value: *Color, out_name: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_get_double(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_value: *f64, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_get_int(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_value: *i64, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_get_object(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_value: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_get_rational_time(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_value: *RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_get_string(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_value: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_get_time_range(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_value: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_get_time_transform(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_value: *TimeTransform, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_get_uint(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_value: *u64, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_get_v2d(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_value: *V2d, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_key_at(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, index: usize, out_key: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_kind(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_kind: *ValueKind, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_len(source: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_len: *usize, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_remove(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_bool(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, value: bool, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_box2d(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, value: Box2d, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_color(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, value: Color, name: ?[*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_dictionary(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_double(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, value: f64, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_int(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, value: i64, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_null(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_object(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, value: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_rational_time(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, value: RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_string(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, value: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_time_range(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, value: TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_time_transform(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, value: TimeTransform, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_uint(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, value: u64, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_v2d(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, value: V2d, out_error: ?*Buffer) Status;
pub extern fn otio_metadata_set_vector(target: *Document, node_handle: NodeHandle, path: [*:0]const u8, len: usize, out_error: ?*Buffer) Status;
pub extern fn otio_missing_reference_new(target: *Document, name: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_node_child_at(source: *Document, parent: NodeHandle, index: usize, out_child: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_node_child_count(source: *Document, parent: NodeHandle, out_count: *usize, out_error: ?*Buffer) Status;
pub extern fn otio_node_children(source: *Document, parent: NodeHandle, out_nodes: ?[*]NodeHandle, capacity: usize, out_count: *usize, out_error: ?*Buffer) Status;
pub extern fn otio_node_equal(left: NodeHandle, right: NodeHandle) bool;
pub extern fn otio_node_find_clips(source: *Document, node_handle: NodeHandle, out_nodes: ?[*]NodeHandle, capacity: usize, out_count: *usize, out_error: ?*Buffer) Status;
pub extern fn otio_node_highest_ancestor(source: *Document, node_handle: NodeHandle, out_ancestor: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_node_is_none(node: NodeHandle) bool;
pub extern fn otio_node_kind(source: *Document, node_handle: NodeHandle, out_kind: *NodeKind, out_error: ?*Buffer) Status;
pub extern fn otio_node_name(source: *Document, node_handle: NodeHandle, out_name: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_node_none() NodeHandle;
pub extern fn otio_node_overlapping(source: *Document, node_handle: NodeHandle, out_overlapping: *bool, out_error: ?*Buffer) Status;
pub extern fn otio_node_parent(source: *Document, node_handle: NodeHandle, out_parent: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_node_schema_name(source: *Document, node_handle: NodeHandle, out_name: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_node_schema_version(source: *Document, node_handle: NodeHandle, out_version: *u32, out_error: ?*Buffer) Status;
pub extern fn otio_node_set_name(target: *Document, node_handle: NodeHandle, name: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_node_to_json(source: *Document, node: NodeHandle, indent: usize, out_json: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_node_transformed_time(source: *Document, time: RationalTime, from: NodeHandle, to: NodeHandle, out_time: *RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_node_transformed_time_range(source: *Document, range: TimeRange, from: NodeHandle, to: NodeHandle, out_range: *TimeRange, out_error: ?*Buffer) Status;
pub extern fn otio_node_visible(source: *Document, node_handle: NodeHandle, out_visible: *bool, out_error: ?*Buffer) Status;
pub extern fn otio_is_drop_frame_rate(rate: f64) bool;
pub extern fn otio_is_smpte_timecode_rate(rate: f64) bool;
pub extern fn otio_nearest_smpte_timecode_rate(rate: f64) f64;
pub extern fn otio_rational_time_add(left: RationalTime, right: RationalTime) RationalTime;
pub extern fn otio_rational_time_almost_equal(left: RationalTime, right: RationalTime, delta: f64) bool;
pub extern fn otio_rational_time_ceil(time: RationalTime) RationalTime;
pub extern fn otio_rational_time_compare(left: RationalTime, right: RationalTime) i32;
pub extern fn otio_rational_time_duration_from_start_end_time(start_time: RationalTime, end_time_exclusive: RationalTime) RationalTime;
pub extern fn otio_rational_time_duration_from_start_end_time_inclusive(start_time: RationalTime, end_time_inclusive: RationalTime) RationalTime;
pub extern fn otio_rational_time_equal(left: RationalTime, right: RationalTime) bool;
pub extern fn otio_rational_time_floor(time: RationalTime) RationalTime;
pub extern fn otio_rational_time_from_frames(frame: f64, rate: f64) RationalTime;
pub extern fn otio_rational_time_from_seconds(seconds: f64) RationalTime;
pub extern fn otio_rational_time_from_seconds_at_rate(seconds: f64, rate: f64) RationalTime;
pub extern fn otio_rational_time_from_time_string(time_string: [*:0]const u8, rate: f64, out_time: *RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_rational_time_from_timecode(timecode: [*:0]const u8, rate: f64, out_time: *RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_rational_time_is_valid(time: RationalTime) bool;
pub extern fn otio_rational_time_negate(time: RationalTime) RationalTime;
pub extern fn otio_rational_time_rescaled_to(time: RationalTime, rate: f64) RationalTime;
pub extern fn otio_rational_time_rescaled_to_time(time: RationalTime, other: RationalTime) RationalTime;
pub extern fn otio_rational_time_round(time: RationalTime) RationalTime;
pub extern fn otio_rational_time_strictly_equal(left: RationalTime, right: RationalTime) bool;
pub extern fn otio_rational_time_subtract(left: RationalTime, right: RationalTime) RationalTime;
pub extern fn otio_rational_time_to_frames(time: RationalTime) i32;
pub extern fn otio_rational_time_to_frames_at_rate(time: RationalTime, rate: f64) i32;
pub extern fn otio_rational_time_to_nearest_timecode_at(time: RationalTime, rate: f64, drop_frame: DropFrame, out_timecode: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_rational_time_to_seconds(time: RationalTime) f64;
pub extern fn otio_rational_time_to_time_string(time: RationalTime, out_string: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_rational_time_to_timecode(time: RationalTime, out_timecode: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_rational_time_to_timecode_at(time: RationalTime, rate: f64, drop_frame: DropFrame, out_timecode: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_rational_time_value_rescaled_to(time: RationalTime, rate: f64) f64;
pub extern fn otio_serializable_collection_new(target: *Document, name: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_stack_new(target: *Document, name: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_time_effect_new(target: *Document, name: ?[*:0]const u8, effect_name: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_time_range_before_range(range: TimeRange, other: TimeRange, epsilon_s: f64) bool;
pub extern fn otio_time_range_before_time(range: TimeRange, time: RationalTime, epsilon_s: f64) bool;
pub extern fn otio_time_range_begins_range(range: TimeRange, other: TimeRange, epsilon_s: f64) bool;
pub extern fn otio_time_range_begins_time(range: TimeRange, time: RationalTime, epsilon_s: f64) bool;
pub extern fn otio_time_range_clamped_range(range: TimeRange, other: TimeRange) TimeRange;
pub extern fn otio_time_range_clamped_time(range: TimeRange, time: RationalTime) RationalTime;
pub extern fn otio_time_range_contains_range(range: TimeRange, other: TimeRange, epsilon_s: f64) bool;
pub extern fn otio_time_range_contains_time(range: TimeRange, time: RationalTime) bool;
pub extern fn otio_time_range_duration_extended_by(range: TimeRange, by: RationalTime) TimeRange;
pub extern fn otio_time_range_end_time_exclusive(range: TimeRange) RationalTime;
pub extern fn otio_time_range_end_time_inclusive(range: TimeRange) RationalTime;
pub extern fn otio_time_range_extended_by(range: TimeRange, other: TimeRange) TimeRange;
pub extern fn otio_time_range_finishes_range(range: TimeRange, other: TimeRange, epsilon_s: f64) bool;
pub extern fn otio_time_range_finishes_time(range: TimeRange, time: RationalTime, epsilon_s: f64) bool;
pub extern fn otio_time_range_from_start_end_time(start_time: RationalTime, end_time_exclusive: RationalTime) TimeRange;
pub extern fn otio_time_range_from_start_end_time_inclusive(start_time: RationalTime, end_time_inclusive: RationalTime) TimeRange;
pub extern fn otio_time_range_intersects(range: TimeRange, other: TimeRange, epsilon_s: f64) bool;
pub extern fn otio_time_range_is_valid(range: TimeRange) bool;
pub extern fn otio_time_range_meets(range: TimeRange, other: TimeRange, epsilon_s: f64) bool;
pub extern fn otio_time_range_overlaps_range(range: TimeRange, other: TimeRange, epsilon_s: f64) bool;
pub extern fn otio_time_range_overlaps_time(range: TimeRange, time: RationalTime) bool;
pub extern fn otio_time_transform_applied_to_range(transform: TimeTransform, range: TimeRange) TimeRange;
pub extern fn otio_time_transform_applied_to_time(transform: TimeTransform, time: RationalTime) RationalTime;
pub extern fn otio_time_transform_applied_to_transform(transform: TimeTransform, other: TimeTransform) TimeTransform;
pub extern fn otio_timeline_clear_global_start_time(target: *Document, node_handle: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_timeline_global_start_time(source: *Document, node_handle: NodeHandle, out_time: *RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_timeline_new(target: *Document, name: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_timeline_set_global_start_time(target: *Document, node_handle: NodeHandle, time: RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_timeline_set_tracks(target: *Document, node_handle: NodeHandle, tracks: NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_timeline_tracks(source: *Document, node_handle: NodeHandle, out_tracks: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_track_kind(source: *Document, node_handle: NodeHandle, out_kind: *Buffer, out_error: ?*Buffer) Status;
pub extern fn otio_track_new(target: *Document, name: ?[*:0]const u8, kind: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_track_set_kind(target: *Document, node_handle: NodeHandle, kind: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_transition_enabled(source: *Document, node_handle: NodeHandle, out_enabled: *bool, out_error: ?*Buffer) Status;
pub extern fn otio_transition_in_offset(source: *Document, node_handle: NodeHandle, out_offset: *RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_transition_new(target: *Document, name: ?[*:0]const u8, transition_type: ?[*:0]const u8, out_node: *NodeHandle, out_error: ?*Buffer) Status;
pub extern fn otio_transition_out_offset(source: *Document, node_handle: NodeHandle, out_offset: *RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_transition_set_enabled(target: *Document, node_handle: NodeHandle, enabled: bool, out_error: ?*Buffer) Status;
pub extern fn otio_transition_set_in_offset(target: *Document, node_handle: NodeHandle, offset: RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_transition_set_out_offset(target: *Document, node_handle: NodeHandle, offset: RationalTime, out_error: ?*Buffer) Status;
pub extern fn otio_transition_set_type(target: *Document, node_handle: NodeHandle, transition_type: [*:0]const u8, out_error: ?*Buffer) Status;
pub extern fn otio_transition_type(source: *Document, node_handle: NodeHandle, out_type: *Buffer, out_error: ?*Buffer) Status;
