// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

//! The metadata dictionary every named object carries.
//!
//! It is a view rather than part of the object, so that `len` and
//! `contains` do not sit beside `name` and `duration`, where they would
//! read as if they were about the object itself.

const std = @import("std");

const c = @import("c.zig");
const enums = @import("enums.zig");
const support = @import("support.zig");
const values = @import("values.zig");

const Allocator = std.mem.Allocator;
const Document = @import("document.zig").Document;
const Error = support.Error;
const Node = @import("schema.zig").Node;
const Box2d = values.Box2d;
const Color = values.Color;
const Handles = values.Handles;
const ImageSequence = values.ImageSequence;
const RationalTime = values.RationalTime;
const ReadOptions = values.ReadOptions;
const TimeRange = values.TimeRange;
const TimeTransform = values.TimeTransform;
const V2d = values.V2d;
const WriteOptions = values.WriteOptions;
const DropFrame = enums.DropFrame;
const EdlStyle = enums.EdlStyle;
const Format = enums.Format;
const MissingFramePolicy = enums.MissingFramePolicy;
const NeighborGapPolicy = enums.NeighborGapPolicy;
const NodeKind = enums.NodeKind;
const ReferencePoint = enums.ReferencePoint;
const Status = enums.Status;
const ValueKind = enums.ValueKind;

/// A Metadata is the free-form dictionary every named object carries.
///
/// A path names a value inside it, a step at a time, separated by dots:
/// "cmx_3600.reel" reaches the reel of the dictionary the EDL adapter left
/// behind, and "takes[0]" the first entry of a list.
///
/// A path is followed, not created. Writing one step deep always works, but
/// a deeper one needs its dictionary to exist first: call
/// setDictionary("cmx_3600") before setString("cmx_3600.reel", "ZZ100").
pub const Metadata = struct {
    /// The object whose dictionary this is.
    node: Node,

    /// clear empties an object's metadata.
    ///
    /// C: `otio_metadata_clear`
    pub fn clear(self: Metadata) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_clear(doc, self.node.handle, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// contains returns whether anything sits at a path.
    ///
    /// C: `otio_metadata_contains`
    pub fn contains(self: Metadata, path: [:0]const u8) Error!bool {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_contains: bool = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_contains(doc, self.node.handle, path.ptr, &out_contains, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
        return out_contains;
    }

    /// getBool reads a boolean from the metadata.
    ///
    /// C: `otio_metadata_get_bool`
    pub fn getBool(self: Metadata, path: [:0]const u8) Error!bool {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_value: bool = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_get_bool(doc, self.node.handle, path.ptr, &out_value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
        return out_value;
    }

    /// getBox2d reads a rectangle from the metadata.
    ///
    /// C: `otio_metadata_get_box2d`
    pub fn getBox2d(self: Metadata, path: [:0]const u8) Error!Box2d {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_value: Box2d = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_get_box2d(doc, self.node.handle, path.ptr, &out_value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
        return out_value;
    }

    /// What `getColor` answers with.
    pub const GetColorResult = struct {
        value: Color,
        name: []u8,

        /// Gives back the memory this holds.
        pub fn deinit(self: GetColorResult, allocator: Allocator) void {
            allocator.free(self.name);
        }
    };

    /// getColor reads a colour, and the name that goes with it, from the
    /// metadata.
    ///
    /// `out_name` may be null if the name is not wanted.
    ///
    /// What this hands back was allocated with allocator, and is the
    /// caller's to free.
    ///
    /// C: `otio_metadata_get_color`
    pub fn getColor(self: Metadata, allocator: Allocator, path: [:0]const u8) Error!GetColorResult {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_value: Color = undefined;
        var out_name: c.Buffer = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_get_color(doc, self.node.handle, path.ptr, &out_value, &out_name, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
        defer c.otio_buffer_free(out_name);
        return .{
            .value = out_value,
            .name = try support.copyBuffer(allocator, out_name),
        };
    }

    /// getDouble reads a number from the metadata.
    ///
    /// C: `otio_metadata_get_double`
    pub fn getDouble(self: Metadata, path: [:0]const u8) Error!f64 {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_value: f64 = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_get_double(doc, self.node.handle, path.ptr, &out_value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
        return out_value;
    }

    /// getInt reads a signed integer from the metadata.
    ///
    /// C: `otio_metadata_get_int`
    pub fn getInt(self: Metadata, path: [:0]const u8) Error!i64 {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_value: i64 = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_get_int(doc, self.node.handle, path.ptr, &out_value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
        return out_value;
    }

    /// getObject reads a handle to an OTIO object held in the metadata.
    ///
    /// C: `otio_metadata_get_object`
    pub fn getObject(self: Metadata, path: [:0]const u8) Error!Node {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_value: c.NodeHandle = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_get_object(doc, self.node.handle, path.ptr, &out_value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
        return Node{ .doc = self.node.doc, .handle = out_value };
    }

    /// getRationalTime reads a time from the metadata.
    ///
    /// C: `otio_metadata_get_rational_time`
    pub fn getRationalTime(self: Metadata, path: [:0]const u8) Error!RationalTime {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_value: RationalTime = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_get_rational_time(doc, self.node.handle, path.ptr, &out_value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
        return out_value;
    }

    /// getString reads a string from the metadata.
    ///
    /// What this hands back was allocated with allocator, and is the
    /// caller's to free.
    ///
    /// C: `otio_metadata_get_string`
    pub fn getString(self: Metadata, allocator: Allocator, path: [:0]const u8) Error![]u8 {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_value: c.Buffer = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_get_string(doc, self.node.handle, path.ptr, &out_value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
        defer c.otio_buffer_free(out_value);
        return try support.copyBuffer(allocator, out_value);
    }

    /// getTimeRange reads a span from the metadata.
    ///
    /// C: `otio_metadata_get_time_range`
    pub fn getTimeRange(self: Metadata, path: [:0]const u8) Error!TimeRange {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_value: TimeRange = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_get_time_range(doc, self.node.handle, path.ptr, &out_value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
        return out_value;
    }

    /// getTimeTransform reads a transform from the metadata.
    ///
    /// C: `otio_metadata_get_time_transform`
    pub fn getTimeTransform(self: Metadata, path: [:0]const u8) Error!TimeTransform {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_value: TimeTransform = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_get_time_transform(doc, self.node.handle, path.ptr, &out_value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
        return out_value;
    }

    /// getUint reads an unsigned integer from the metadata.
    ///
    /// C: `otio_metadata_get_uint`
    pub fn getUint(self: Metadata, path: [:0]const u8) Error!u64 {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_value: u64 = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_get_uint(doc, self.node.handle, path.ptr, &out_value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
        return out_value;
    }

    /// getV2d reads a point from the metadata.
    ///
    /// C: `otio_metadata_get_v2d`
    pub fn getV2d(self: Metadata, path: [:0]const u8) Error!V2d {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_value: V2d = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_get_v2d(doc, self.node.handle, path.ptr, &out_value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
        return out_value;
    }

    /// keyAt returns the key at an index of a dictionary at a path.
    ///
    /// Keys are ordered, so walking the indices walks them the same way
    /// twice.
    ///
    /// Where there is nothing to report this answers null, which is an
    /// answer rather than a failure.
    ///
    /// What this hands back was allocated with allocator, and is the
    /// caller's to free.
    ///
    /// C: `otio_metadata_key_at`
    pub fn keyAt(self: Metadata, allocator: Allocator, path: [:0]const u8, index: usize) Error!?[]u8 {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_key: c.Buffer = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_key_at(doc, self.node.handle, path.ptr, index, &out_key, &out_error);
        if (status == .no_value) return null;
        if (status != .ok) return support.statusError(status, out_error);
        defer c.otio_buffer_free(out_key);
        return try support.copyBuffer(allocator, out_key);
    }

    /// kind returns what kind of value sits at a path.
    ///
    /// An empty or null path names the metadata dictionary itself, which is
    /// always `ValueKind.dictionary`.
    ///
    /// Where there is nothing to report this answers null, which is an
    /// answer rather than a failure.
    ///
    /// C: `otio_metadata_kind`
    pub fn kind(self: Metadata, path: [:0]const u8) Error!?ValueKind {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_kind: ValueKind = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_kind(doc, self.node.handle, path.ptr, &out_kind, &out_error);
        if (status == .no_value) return null;
        if (status != .ok) return support.statusError(status, out_error);
        return out_kind;
    }

    /// len returns how many entries a dictionary or an array at a path
    /// holds.
    ///
    /// Where there is nothing to report this answers null, which is an
    /// answer rather than a failure.
    ///
    /// C: `otio_metadata_len`
    pub fn len(self: Metadata, path: [:0]const u8) Error!?usize {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_len: usize = undefined;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_len(doc, self.node.handle, path.ptr, &out_len, &out_error);
        if (status == .no_value) return null;
        if (status != .ok) return support.statusError(status, out_error);
        return out_len;
    }

    /// remove removes whatever sits at a path.
    ///
    /// Removing a key of a dictionary takes the key with it; removing an
    /// element of an array shortens the array.
    ///
    /// Where there was nothing to do this answers false, which is an answer
    /// rather than a failure.
    ///
    /// C: `otio_metadata_remove`
    pub fn remove(self: Metadata, path: [:0]const u8) Error!bool {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_remove(doc, self.node.handle, path.ptr, &out_error);
        if (status == .no_value) return false;
        if (status != .ok) return support.statusError(status, out_error);
        return true;
    }

    /// setBool writes a boolean into the metadata.
    ///
    /// C: `otio_metadata_set_bool`
    pub fn setBool(self: Metadata, path: [:0]const u8, value: bool) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_bool(doc, self.node.handle, path.ptr, value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// setBox2d writes a rectangle into the metadata.
    ///
    /// C: `otio_metadata_set_box2d`
    pub fn setBox2d(self: Metadata, path: [:0]const u8, value: Box2d) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_box2d(doc, self.node.handle, path.ptr, value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// setColor writes a colour into the metadata. `name` may be null for
    /// an unnamed one.
    ///
    /// C: `otio_metadata_set_color`
    pub fn setColor(self: Metadata, path: [:0]const u8, value: Color, name: ?[:0]const u8) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        const arg_name: ?[*:0]const u8 = if (name) |text| text.ptr else null;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_color(doc, self.node.handle, path.ptr, value, arg_name, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// setDictionary writes an empty dictionary into the metadata, to be
    /// filled through deeper paths.
    ///
    /// C: `otio_metadata_set_dictionary`
    pub fn setDictionary(self: Metadata, path: [:0]const u8) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_dictionary(doc, self.node.handle, path.ptr, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// setDouble writes a number into the metadata.
    ///
    /// C: `otio_metadata_set_double`
    pub fn setDouble(self: Metadata, path: [:0]const u8, value: f64) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_double(doc, self.node.handle, path.ptr, value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// setInt writes a signed integer into the metadata.
    ///
    /// C: `otio_metadata_set_int`
    pub fn setInt(self: Metadata, path: [:0]const u8, value: i64) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_int(doc, self.node.handle, path.ptr, value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// setNull writes a null into the metadata.
    ///
    /// C: `otio_metadata_set_null`
    pub fn setNull(self: Metadata, path: [:0]const u8) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_null(doc, self.node.handle, path.ptr, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// setObject writes a handle to an OTIO object into the metadata.
    ///
    /// The object stays where it is and the metadata names it. Nothing
    /// checks that the handle is live, because a document being built may
    /// not hold the object yet.
    ///
    /// C: `otio_metadata_set_object`
    pub fn setObject(self: Metadata, path: [:0]const u8, value: Node) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        if (!value.belongsTo(self.node.doc)) return Error.ForeignObject;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_object(doc, self.node.handle, path.ptr, value.handle, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// setRationalTime writes a time into the metadata.
    ///
    /// C: `otio_metadata_set_rational_time`
    pub fn setRationalTime(self: Metadata, path: [:0]const u8, value: RationalTime) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_rational_time(doc, self.node.handle, path.ptr, value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// setString writes a string into the metadata.
    ///
    /// C: `otio_metadata_set_string`
    pub fn setString(self: Metadata, path: [:0]const u8, value: [:0]const u8) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_string(doc, self.node.handle, path.ptr, value.ptr, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// setTimeRange writes a span into the metadata.
    ///
    /// C: `otio_metadata_set_time_range`
    pub fn setTimeRange(self: Metadata, path: [:0]const u8, value: TimeRange) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_time_range(doc, self.node.handle, path.ptr, value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// setTimeTransform writes a transform into the metadata.
    ///
    /// C: `otio_metadata_set_time_transform`
    pub fn setTimeTransform(self: Metadata, path: [:0]const u8, value: TimeTransform) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_time_transform(doc, self.node.handle, path.ptr, value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// setUint writes an unsigned integer into the metadata.
    ///
    /// C: `otio_metadata_set_uint`
    pub fn setUint(self: Metadata, path: [:0]const u8, value: u64) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_uint(doc, self.node.handle, path.ptr, value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// setV2d writes a point into the metadata.
    ///
    /// C: `otio_metadata_set_v2d`
    pub fn setV2d(self: Metadata, path: [:0]const u8, value: V2d) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_v2d(doc, self.node.handle, path.ptr, value, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }

    /// setVector writes an array of `len` nulls into the metadata, to be
    /// filled by index.
    ///
    /// C: `otio_metadata_set_vector`
    pub fn setVector(self: Metadata, path: [:0]const u8, length: usize) Error!void {
        const doc = self.node.doc orelse return Error.NullPointer;
        var out_error: c.Buffer = .{ .data = null, .len = 0 };
        defer c.otio_buffer_free(out_error);
        const status = c.otio_metadata_set_vector(doc, self.node.handle, path.ptr, length, &out_error);
        if (status != .ok) return support.statusError(status, out_error);
    }
};
