// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

//! What every generated call leans on: the error set the C interface's
//! status codes become, and the copying that gets a library-owned buffer
//! into memory the caller owns.

const std = @import("std");

const c = @import("c.zig");
const enums = @import("enums.zig");

const Status = enums.Status;

/// Every way a call in this package can fail.
///
/// A Zig error carries no message, so the sentence the library left about
/// the last failure is read separately, with `lastErrorMessage`.
///
/// `NoValue` is here for completeness. A call for which "there is nothing
/// here" is one of the answers hands back `null` instead, because that is
/// what Zig has optionals for.
pub const Error = error{
    /// An allocation the SDK made on the caller's behalf failed.
    OutOfMemory,
    /// An object from another document was passed to this one. A handle
    /// is an index into one arena, so it would otherwise have resolved to
    /// an unrelated object rather than failing.
    ForeignObject,
    /// The library reported something this package has no name for, which
    /// means it is newer than the SDK generated against it.
    Unexpected,
    /// NullPointer means a pointer argument that may not be null was null.
    NullPointer,
    /// InvalidUtf8 means a string argument was not valid UTF-8.
    InvalidUtf8,
    /// NoValue means the call succeeded, and the answer is that there is no
    /// value.
    ///
    /// An item with no `source_range` and a clip with no active media
    /// reference both report this. It is not an error.
    NoValue,
    /// StaleHandle means a node handle named an object that no longer
    /// exists.
    StaleHandle,
    /// InvalidArgument means an argument was outside the range the call
    /// accepts.
    InvalidArgument,
    /// CoreError means the document could not answer the question asked of
    /// it.
    ///
    /// Asking a marker for its duration, or a track for a child it does not
    /// hold, lands here. [`errorMessage`] says which.
    CoreError,
    /// TimeError means a timecode or time string could not be read or
    /// written.
    TimeError,
    /// ParseError means a file was not valid for the format it was read as.
    ParseError,
    /// Unsupported means the document holds something the target format
    /// cannot express.
    Unsupported,
    /// IoError means a file could not be read from or written to disk.
    IoError,
    /// Panic means a panic in the Rust core was caught at the boundary.
    ///
    /// The library is left in an unspecified state; a caller that sees this
    /// should stop using the document it was working on.
    Panic,
};

/// Turns a status the library reported into this package's error.
pub fn statusError(status: Status) Error {
    return switch (status) {
        .null_pointer => Error.NullPointer,
        .invalid_utf8 => Error.InvalidUtf8,
        .no_value => Error.NoValue,
        .stale_handle => Error.StaleHandle,
        .invalid_argument => Error.InvalidArgument,
        .core_error => Error.CoreError,
        .time_error => Error.TimeError,
        .parse_error => Error.ParseError,
        .unsupported => Error.Unsupported,
        .io_error => Error.IoError,
        .panic => Error.Panic,
        // Never asked of a success: every generated call tests for it
        // first. A status this package has no name for lands here too.
        else => Error.Unexpected,
    };
}

/// The sentence the library left about the last failure on this thread.
///
/// A Zig error is a value with no room for a message, so this is where the
/// detail is. It is worth reading immediately after a call fails: the next
/// failing call on this thread replaces it.
///
/// C: `otio_error_message`
pub fn lastErrorMessage() []const u8 {
    return std.mem.span(c.otio_error_message());
}

/// Copies a buffer the library owns into memory the caller owns.
///
/// Every call that answers with text or bytes goes through this, so what
/// reaches a caller is an ordinary slice from their own allocator, freed
/// with `allocator.free`, and the library's buffer is released before the
/// call returns.
pub fn copyBuffer(allocator: std.mem.Allocator, buffer: c.Buffer) Error![]u8 {
    const data = buffer.data orelse return allocator.alloc(u8, 0);
    return allocator.dupe(u8, data[0..buffer.len]);
}
