// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

#pragma once

// OpenTimelineIO for C++.
//
//     #include <opentimelineio/otio.hpp>
//
// Everything lives in namespace `otio`. Link against `otio`.

#include "enums.hpp"
#include "runtime.hpp"
#include "values.hpp"
#include "objects.hpp"
#include "calls.hpp"
