// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

#pragma once

#include <cstddef>
#include <cstring>
#include <exception>
#include <functional>
#include <memory>
#include <optional>
#include <string>
#include <utility>

#include "otio.h"

#include "calls.hpp"
#include "enums.hpp"
#include "objects.hpp"
#include "runtime.hpp"

namespace otio {

/// A media linker: handed each clip a read produced, and the arguments the
/// read was given for it, it answers the media reference the clip should use
/// in place of its active one. Upstream's `link_media_reference`.
///
/// It may build the reference with `ExternalReference::create` or any other
/// constructor, or edit the clip itself. An empty optional leaves the clip
/// as it is. The clip and the arguments are valid only for the call, so
/// neither may be kept; what it answers joins the timeline the clip is in.
///
/// An exception it throws stops the read, which then throws an `Error` with
/// `Status::PLUGIN_ERROR` and the exception's `what()`. A read may run on any
/// thread, so a linker must be safe to call from any of them.
using MediaLinker =
    std::function<std::optional<MediaReference>(const Clip &clip, const Metadata &arguments)>;

/// A hook script: handed what a hook runs on, and the arguments the read or
/// write was given for its hooks, it answers what to go on with: the same
/// object, changed or not, or another one. Upstream's `hook_function`.
///
/// What it is handed and the arguments are valid only for the call, so
/// neither may be kept; what it answers joins the timeline it was handed.
/// Answering an object of no timeline, or throwing, fails the hook with
/// `Status::PLUGIN_ERROR`.
using HookScript = std::function<SerializableObject(
    const SerializableObject &target, const Metadata &arguments)>;

/// Registers a media linker under `name`, replacing any registered already.
///
/// A read runs it on every clip when `ReadOptions::media_linker` names it, or
/// when the `OTIO_DEFAULT_MEDIA_LINKER` environment variable does and the
/// options name none. The function is kept until the name is registered
/// again or `unregister_media_linker` is called.
///
/// C: `otio_register_media_linker`
void register_media_linker(const std::string &name, MediaLinker linker);

/// Registers a hook script under `name`, replacing any registered already.
/// It runs at the hooks `attach_hook_script` attaches it to.
///
/// C: `otio_register_hook_script`
void register_hook_script(const std::string &name, HookScript script);

namespace detail {

/// What a registration's context points at: the one function it calls.
struct Plugin {
    MediaLinker linker;
    HookScript script;
};

/// Copies a message into the room the library gave for it, cut short to
/// fit and NUL-terminated.
inline void say(char *message, std::size_t capacity, const char *text) noexcept {
    if (message == nullptr || capacity == 0) {
        return;
    }
    const std::size_t length = text == nullptr ? 0 : std::strlen(text);
    const std::size_t written = length < capacity - 1 ? length : capacity - 1;
    if (written > 0) {
        std::memcpy(message, text, written);
    }
    message[written] = '\0';
}

/// The library's document, held as an arena for the length of one call.
///
/// It is the library's to free, so the arena is marked borrowed and the
/// document is marked lent, which also stops an arena the caller already
/// holds over it from freeing it during the call. Once the call is over the
/// arena's pointer is nulled: an object kept from it fails afterwards rather
/// than reaching a document that may have gone.
class Lent {
 public:
    explicit Lent(OtioDocument *document) : arena(std::make_shared<Arena>(document)) {
        arena->borrowed = true;
        lend(document);
    }
    Lent(const Lent &) = delete;
    Lent &operator=(const Lent &) = delete;
    ~Lent() {
        hand_back(arena->pointer);
        arena->pointer = nullptr;
    }

    std::shared_ptr<Arena> arena;
};

/// The handle, in the lent document, of what a plugin answered.
///
/// Built fresh, the object is in an arena of its own and is brought over.
/// But the document lent can be one the caller already holds as an arena of
/// its own: `run_hook` lends the document its object is in, and a script may
/// answer with an object it kept from outside. That is the same document
/// under another arena, so it is matched by the document and not moved,
/// which would be a document absorbing itself.
inline OtioNode bring_here(const Site &at, const SerializableObject &node) {
    const Site theirs = locate(node);
    if (theirs.arena != nullptr && theirs.pointer == at.pointer) {
        return theirs.handle;
    }
    check_move(at, node, false);
    return move_here(at, node);
}

/// What the library calls. Nothing may unwind out of it into the library,
/// so every exception stops here and becomes the failure's message.
inline OtioStatus run_plugin(
    void *context,
    OtioDocument *document,
    OtioNode target,
    OtioNode arguments,
    OtioNode *out_result,
    char *message,
    std::size_t message_capacity) noexcept {
    try {
        const Plugin &found = *static_cast<const Plugin *>(context);
        const Lent lent(document);
        Site at;
        at.arena = lent.arena;
        at.pointer = document;
        const Metadata held(SerializableObject(Adopt{}, lent.arena, arguments));
        OtioNode result = otio_node_none();
        if (found.linker) {
            const std::optional<MediaReference> linked =
                found.linker(Clip(Adopt{}, lent.arena, target), held);
            if (linked.has_value()) {
                result = bring_here(at, *linked);
            }
        } else {
            const SerializableObject next =
                found.script(SerializableObject(Adopt{}, lent.arena, target), held);
            if (!next.arena()) {
                say(message, message_capacity, "the hook script answered no object to go on with");
                return OTIO_STATUS_PLUGIN_ERROR;
            }
            result = bring_here(at, next);
        }
        if (out_result != nullptr) {
            *out_result = result;
        }
        return OTIO_STATUS_OK;
    } catch (const std::exception &failure) {
        say(message, message_capacity, failure.what());
    } catch (...) {
        say(message, message_capacity, "it threw something that is not a std::exception");
    }
    return OTIO_STATUS_PLUGIN_ERROR;
}

/// What the library calls once it has no more use for a registration.
inline void release_plugin(void *context) noexcept { delete static_cast<Plugin *>(context); }

/// Hands the library a plugin. On success the library owns it and releases
/// it; a registration that fails keeps nothing, so it is freed here.
inline void register_plugin(const std::string &name, std::unique_ptr<Plugin> plugin, bool linker) {
    Buffer error;
    const OtioStatus status = linker
        ? otio_register_media_linker(
              name.c_str(), run_plugin, plugin.get(), release_plugin, &error.raw)
        : otio_register_hook_script(
              name.c_str(), run_plugin, plugin.get(), release_plugin, &error.raw);
    check(status, error);
    plugin.release();
}

}  // namespace detail

inline void register_media_linker(const std::string &name, MediaLinker linker) {
    if (!linker) {
        throw Error(Status::NULL_POINTER, "otio: a media linker needs a function to call");
    }
    auto plugin = std::make_unique<detail::Plugin>();
    plugin->linker = std::move(linker);
    detail::register_plugin(name, std::move(plugin), true);
}

inline void register_hook_script(const std::string &name, HookScript script) {
    if (!script) {
        throw Error(Status::NULL_POINTER, "otio: a hook script needs a function to call");
    }
    auto plugin = std::make_unique<detail::Plugin>();
    plugin->script = std::move(script);
    detail::register_plugin(name, std::move(plugin), false);
}

}  // namespace otio
