[package]
name = "otio-aaf"
description = "Reading Advanced Authoring Format files as OpenTimelineIO timelines"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
aaf = { version = "0.1.0", path = "../aaf" }
opentime = { workspace = true }
otio-core = { version = "0.1.0", path = "../otio-core" }

[lints]
workspace = true
