//! The conformance scenarios, as Go tests.
//!
//! They land in `sdk/go/conformance_test.go`, beside the hand-written tests,
//! so `go test ./...` in the Go job runs them with everything else.

use std::fmt::Write as _;
use std::path::PathBuf;

use otio_sdk_model::Api;
use otio_sdk_model::conformance::{self, Attempt, Expect, Failure, Scenario, Step};
use otio_sdk_model::names;

use super::{comment, number, quoted};
use crate::emit::File;

/// Go hides the document, so it runs every scenario.
const HIDES_DOCUMENT: bool = true;

/// Renders every scenario Go runs into one test file.
///
/// # Errors
///
/// Fails if a scenario names a status the library does not have.
pub fn render(api: &Api) -> Result<File, String> {
    let mut out = String::new();
    out.push_str(
        "// Code generated by otio-sdk-gen from crates/otio-sdk-model/src/conformance.rs. DO NOT EDIT.\n\n\
         // The conformance scenarios: what every SDK has to agree on, stated once\n\
         // and rendered into each language's own tests. A failure here means this\n\
         // SDK disagrees with the others about what the library does.\n\n\
         package otio_test\n\n\
         import (\n\
         \t\"errors\"\n\
         \t\"testing\"\n\n\
         \totio \"github.com/alchemist-editor/otio-rust/sdk/go\"\n\
         )\n",
    );
    for scenario in conformance::for_target(HIDES_DOCUMENT) {
        out.push('\n');
        out.push_str(&test(api, scenario)?);
    }
    out.push_str(HELPERS);
    Ok(File {
        path: PathBuf::from("sdk/go/conformance_test.go"),
        contents: out,
    })
}

/// One scenario as one test function.
fn test(api: &Api, scenario: &Scenario) -> Result<String, String> {
    let name = format!("TestConformance{}", names::pascal(scenario.name));
    let mut out = String::new();
    let _ = writeln!(out, "// {name} is the scenario {}.", quoted(scenario.name));
    out.push_str("//\n");
    for line in comment(scenario, "// ", 80) {
        out.push_str(&line);
        out.push('\n');
    }
    let _ = writeln!(out, "func {name}(t *testing.T) {{");
    out.push_str("\tvar err error\n");
    for step in scenario.steps {
        for line in step_lines(api, step)? {
            out.push('\t');
            out.push_str(&line);
            out.push('\n');
        }
    }
    out.push_str("\t_ = err\n}\n");
    Ok(out)
}

/// The Go for one step.
fn step_lines(api: &Api, step: &Step) -> Result<Vec<String>, String> {
    let must = |call: String| vec![format!("conformanceMust(t, {call})")];
    Ok(match *step {
        Step::NewTimeline { var, name, .. } => vec![
            format!("{var}, err := otio.NewTimeline({})", quoted(name)),
            "conformanceMust(t, err)".to_string(),
        ],
        Step::Tracks { var, of } => vec![
            format!("{var}Node, err := {of}.Tracks()"),
            "conformanceMust(t, err)".to_string(),
            format!("{var}, ok := {var}Node.AsStack()"),
            "if !ok {".to_string(),
            format!(
                "\tt.Fatal({})",
                quoted(&format!("{of}'s tracks are not a stack"))
            ),
            "}".to_string(),
        ],
        Step::NewTrack {
            var, name, kind, ..
        } => vec![
            format!(
                "{var}, err := otio.NewTrack({}, {})",
                quoted(name),
                quoted(kind)
            ),
            "conformanceMust(t, err)".to_string(),
        ],
        Step::NewClip { var, name, .. } => vec![
            format!("{var}, err := otio.NewClip({})", quoted(name)),
            "conformanceMust(t, err)".to_string(),
        ],
        Step::SetSourceRange {
            item,
            start,
            duration,
            rate,
        } => must(format!(
            "{item}.SetSourceRange(otio.TimeRange{{StartTime: {}, Duration: {}}})",
            time(start, rate),
            time(duration, rate)
        )),
        Step::Append { parent, child } => must(format!("{parent}.AppendChild({child}.Node)")),
        Step::Remove { var } => must(format!("{var}.Remove()")),
        Step::Release { var } => vec![format!("{var}.Close()")],
        Step::Expect(expect) => expect_lines(expect),
        Step::Refused { attempt, failure } => {
            let (call, what) = match attempt {
                Attempt::Name { var } => {
                    (format!("_, err = {var}.Name()"), format!("{var}.Name()"))
                }
                Attempt::Append { parent, child } => (
                    format!("err = {parent}.AppendChild({child}.Node)"),
                    format!("{parent}.AppendChild({child})"),
                ),
                Attempt::Detach { parent, child } => (
                    format!("err = {parent}.DetachChild({child}.Node)"),
                    format!("{parent}.DetachChild({child})"),
                ),
                Attempt::FlattenTracks { tracks } => {
                    let list: Vec<String> =
                        tracks.iter().map(|track| format!("{track}.Node")).collect();
                    (
                        format!(
                            "_, err = otio.FlattenTracks([]otio.Node{{{}}})",
                            list.join(", ")
                        ),
                        format!("otio.FlattenTracks({})", tracks.join(", ")),
                    )
                }
            };
            let check = match failure {
                Failure::OtherTimeline => format!("conformanceForeign(t, {}, err)", quoted(&what)),
                Failure::Status(status) => format!(
                    "conformanceRefused(t, {}, err, otio.{})",
                    quoted(&what),
                    status_constant(api, status)?
                ),
            };
            vec![call, check]
        }
    })
}

/// The Go for one expectation.
fn expect_lines(expect: Expect) -> Vec<String> {
    match expect {
        Expect::Name { var, is } => vec![
            format!(
                "if got, err := {var}.Name(); err != nil || got != {} {{",
                quoted(is)
            ),
            format!(
                "\tt.Fatalf(\"{var}.Name() = %q, %v; want %q\", got, err, {})",
                quoted(is)
            ),
            "}".to_string(),
        ],
        Expect::ChildCount { var, is } => vec![
            format!("if got, err := {var}.ChildCount(); err != nil || got != {is} {{"),
            format!("\tt.Fatalf(\"{var}.ChildCount() = %d, %v; want {is}\", got, err)"),
            "}".to_string(),
        ],
        Expect::Duration { var, value, rate } => vec![
            format!(
                "if got, err := {var}.Duration(); err != nil || got.Value != {} || got.Rate != {} {{",
                number(value),
                number(rate)
            ),
            format!(
                "\tt.Fatalf(\"{var}.Duration() = %v, %v; want {} at {}\", got, err)",
                number(value),
                number(rate)
            ),
            "}".to_string(),
        ],
        Expect::Json { var, is } => vec![
            format!(
                "if got, err := {var}.ToJSON(4); err != nil || got != {} {{",
                quoted(is)
            ),
            format!("\tt.Fatalf(\"{var}.ToJSON(4) = %v; wrote\\n%s\", err, got)"),
            "}".to_string(),
        ],
    }
}

/// A time literal.
fn time(value: f64, rate: f64) -> String {
    format!(
        "otio.RationalTime{{Value: {}, Rate: {}}}",
        number(value),
        number(rate)
    )
}

/// The Go constant for a status, checked against the library's own enum so a
/// scenario cannot name one that does not exist.
fn status_constant(api: &Api, status: &str) -> Result<String, String> {
    let known = api.enumeration("OtioStatus").is_some_and(|statuses| {
        statuses
            .variants
            .iter()
            .any(|variant| variant.name == status)
    });
    if !known {
        return Err(format!(
            "a conformance scenario expects the status `{status}`, which `OtioStatus` does not have"
        ));
    }
    Ok(format!(
        "Status{}",
        names::respell(status, names::INITIALISMS)
    ))
}

/// What every rendered test leans on.
const HELPERS: &str = "
// conformanceMust stops the test on an unexpected failure.
func conformanceMust(t *testing.T, err error) {
\tt.Helper()
\tif err != nil {
\t\tt.Fatal(err)
\t}
}

// conformanceRefused insists the library refused with one status.
func conformanceRefused(t *testing.T, what string, err error, want otio.Status) {
\tt.Helper()
\tvar failure *otio.Error
\tif !errors.As(err, &failure) || failure.Status != want {
\t\tt.Fatalf(\"%s: got %v, want a failure with status %v\", what, err, want)
\t}
}

// conformanceForeign insists the binding refused an object from another
// timeline before asking the library, rather than letting the library fail.
func conformanceForeign(t *testing.T, what string, err error) {
\tt.Helper()
\tif !errors.Is(err, otio.ErrOtherTimeline) {
\t\tt.Fatalf(\"%s: got %v, want otio.ErrOtherTimeline\", what, err)
\t}
}
";
