// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

import COtio

/// The free-form dictionary every named object carries.
public struct Metadata {
    internal let object: SerializableObject
}

extension SerializableObjectWithMetadata {
    /// The object's metadata, which is a dictionary of its own.
    ///
    /// A path names a value inside it, a step at a time, separated by
    /// dots: `cmx_3600.reel` reaches the reel of the dictionary the EDL
    /// adapter left behind, and `takes[0]` the first entry of a list.
    ///
    /// A path is followed, not created. Writing one step deep always
    /// works, but a deeper one needs its dictionary to exist first:
    ///
    /// ```swift
    /// try clip.metadata.setDictionary("cmx_3600")
    /// try clip.metadata.setString("cmx_3600.reel", value: "ZZ100")
    /// ```
    public var metadata: Metadata {
        Metadata(object: self)
    }
}

extension Metadata {
    /// Empties an object's metadata.
    ///
    /// C: `otio_metadata_clear`
    public func clear() throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            var cError = OtioBuffer()
            defer { otio_buffer_free(cError) }
            let status = otio_metadata_clear(at.pointer, at.handle, &cError)
            try check(status, cError)
        }
    }

    /// Returns whether anything sits at a path.
    ///
    /// C: `otio_metadata_contains`
    public func contains(_ path: String) throws -> Bool {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Bool in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Bool in
                var outContains = false
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_contains(at.pointer, at.handle, cPath, &outContains, &cError)
                try check(status, cError)
                return outContains
            }
        }
    }

    /// Reads a boolean from the metadata.
    ///
    /// C: `otio_metadata_get_bool`
    public func getBool(_ path: String) throws -> Bool {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Bool in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Bool in
                var outValue = false
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_get_bool(at.pointer, at.handle, cPath, &outValue, &cError)
                try check(status, cError)
                return outValue
            }
        }
    }

    /// Reads a rectangle from the metadata.
    ///
    /// C: `otio_metadata_get_box2d`
    public func getBox2d(_ path: String) throws -> Box2d {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Box2d in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Box2d in
                var outValue = OtioBox2d()
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_get_box2d(at.pointer, at.handle, cPath, &outValue, &cError)
                try check(status, cError)
                return Box2d(outValue)
            }
        }
    }

    /// Reads a colour, and the name that goes with it, from the metadata.
    ///
    /// `out_name` may be nil if the name is not wanted.
    ///
    /// C: `otio_metadata_get_color`
    public func getColor(_ path: String) throws -> (value: Color, name: String) {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> (value: Color, name: String) in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> (value: Color, name: String) in
                var outValue = OtioColor()
                var outName = OtioBuffer()
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_get_color(at.pointer, at.handle, cPath, &outValue, &outName, &cError)
                try check(status, cError)
                defer { otio_buffer_free(outName) }
                return (value: Color(outValue), name: swiftText(outName))
            }
        }
    }

    /// Reads a number from the metadata.
    ///
    /// C: `otio_metadata_get_double`
    public func getDouble(_ path: String) throws -> Double {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Double in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Double in
                var outValue: Double = 0
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_get_double(at.pointer, at.handle, cPath, &outValue, &cError)
                try check(status, cError)
                return outValue
            }
        }
    }

    /// Reads a signed integer from the metadata.
    ///
    /// C: `otio_metadata_get_int`
    public func getInt(_ path: String) throws -> Int64 {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Int64 in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Int64 in
                var outValue: Int64 = 0
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_get_int(at.pointer, at.handle, cPath, &outValue, &cError)
                try check(status, cError)
                return outValue
            }
        }
    }

    /// Reads a handle to an OTIO object held in the metadata.
    ///
    /// C: `otio_metadata_get_object`
    public func getObject(_ path: String) throws -> SerializableObject {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> SerializableObject in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> SerializableObject in
                var outValue = OtioNode()
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_get_object(at.pointer, at.handle, cPath, &outValue, &cError)
                try check(status, cError)
                return makeObject(at.arena, outValue)
            }
        }
    }

    /// Reads a time from the metadata.
    ///
    /// C: `otio_metadata_get_rational_time`
    public func getRationalTime(_ path: String) throws -> RationalTime {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> RationalTime in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> RationalTime in
                var outValue = OtioRationalTime()
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_get_rational_time(at.pointer, at.handle, cPath, &outValue, &cError)
                try check(status, cError)
                return RationalTime(outValue)
            }
        }
    }

    /// Reads a string from the metadata.
    ///
    /// C: `otio_metadata_get_string`
    public func getString(_ path: String) throws -> String {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> String in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> String in
                var outValue = OtioBuffer()
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_get_string(at.pointer, at.handle, cPath, &outValue, &cError)
                try check(status, cError)
                defer { otio_buffer_free(outValue) }
                return swiftText(outValue)
            }
        }
    }

    /// Reads a span from the metadata.
    ///
    /// C: `otio_metadata_get_time_range`
    public func getTimeRange(_ path: String) throws -> TimeRange {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> TimeRange in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> TimeRange in
                var outValue = OtioTimeRange()
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_get_time_range(at.pointer, at.handle, cPath, &outValue, &cError)
                try check(status, cError)
                return TimeRange(outValue)
            }
        }
    }

    /// Reads a transform from the metadata.
    ///
    /// C: `otio_metadata_get_time_transform`
    public func getTimeTransform(_ path: String) throws -> TimeTransform {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> TimeTransform in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> TimeTransform in
                var outValue = OtioTimeTransform()
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_get_time_transform(at.pointer, at.handle, cPath, &outValue, &cError)
                try check(status, cError)
                return TimeTransform(outValue)
            }
        }
    }

    /// Reads an unsigned integer from the metadata.
    ///
    /// C: `otio_metadata_get_uint`
    public func getUint(_ path: String) throws -> UInt64 {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> UInt64 in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> UInt64 in
                var outValue: UInt64 = 0
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_get_uint(at.pointer, at.handle, cPath, &outValue, &cError)
                try check(status, cError)
                return outValue
            }
        }
    }

    /// Reads a point from the metadata.
    ///
    /// C: `otio_metadata_get_v2d`
    public func getV2d(_ path: String) throws -> V2d {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> V2d in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> V2d in
                var outValue = OtioV2d()
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_get_v2d(at.pointer, at.handle, cPath, &outValue, &cError)
                try check(status, cError)
                return V2d(outValue)
            }
        }
    }

    /// Returns the key at an index of a dictionary at a path.
    ///
    /// Keys are ordered, so walking the indices walks them the same way twice.
    ///
    /// Where there is nothing to report this answers nil, which is an answer
    /// rather than a failure.
    ///
    /// C: `otio_metadata_key_at`
    public func keyAt(_ path: String, index: Int) throws -> String? {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> String? in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> String? in
                var outKey = OtioBuffer()
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_key_at(at.pointer, at.handle, cPath, index, &outKey, &cError)
                if isNoValue(status) { return nil }
                try check(status, cError)
                defer { otio_buffer_free(outKey) }
                return swiftText(outKey)
            }
        }
    }

    /// Returns what kind of value sits at a path.
    ///
    /// An empty or nil path names the metadata dictionary itself, which is
    /// always `ValueKind.dictionary`.
    ///
    /// Where there is nothing to report this answers nil, which is an answer
    /// rather than a failure.
    ///
    /// C: `otio_metadata_kind`
    public func kind(_ path: String) throws -> ValueKind? {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> ValueKind? in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> ValueKind? in
                var outKind = cEnum(0, OtioValueKind.self)
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_kind(at.pointer, at.handle, cPath, &outKind, &cError)
                if isNoValue(status) { return nil }
                try check(status, cError)
                return enumValue(outKind, ValueKind.self)
            }
        }
    }

    /// Returns how many entries a dictionary or an array at a path holds.
    ///
    /// Where there is nothing to report this answers nil, which is an answer
    /// rather than a failure.
    ///
    /// C: `otio_metadata_len`
    public func len(_ path: String) throws -> Int? {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Int? in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Int? in
                var outLen = 0
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_len(at.pointer, at.handle, cPath, &outLen, &cError)
                if isNoValue(status) { return nil }
                try check(status, cError)
                return outLen
            }
        }
    }

    /// Removes whatever sits at a path.
    ///
    /// Removing a key of a dictionary takes the key with it; removing an
    /// element of an array shortens the array.
    ///
    /// Where there was nothing to do this throws an `OTIOError` whose status is
    /// `.noValue`, which is an answer rather than a failure.
    ///
    /// C: `otio_metadata_remove`
    public func remove(_ path: String) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_remove(at.pointer, at.handle, cPath, &cError)
                try check(status, cError)
            }
        }
    }

    /// Writes a boolean into the metadata.
    ///
    /// C: `otio_metadata_set_bool`
    public func setBool(_ path: String, value: Bool) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_set_bool(at.pointer, at.handle, cPath, value, &cError)
                try check(status, cError)
            }
        }
    }

    /// Writes a rectangle into the metadata.
    ///
    /// C: `otio_metadata_set_box2d`
    public func setBox2d(_ path: String, value: Box2d) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                return try value.withC { (cValue: OtioBox2d) -> Void in
                    var cError = OtioBuffer()
                    defer { otio_buffer_free(cError) }
                    let status = otio_metadata_set_box2d(at.pointer, at.handle, cPath, cValue, &cError)
                    try check(status, cError)
                }
            }
        }
    }

    /// Writes a colour into the metadata. `name` may be nil for an unnamed one.
    ///
    /// C: `otio_metadata_set_color`
    public func setColor(_ path: String, value: Color, name: String? = nil) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                return try value.withC { (cValue: OtioColor) -> Void in
                    return try withOptionalCString(name) { (cName: UnsafePointer<CChar>?) -> Void in
                        var cError = OtioBuffer()
                        defer { otio_buffer_free(cError) }
                        let status = otio_metadata_set_color(at.pointer, at.handle, cPath, cValue, cName, &cError)
                        try check(status, cError)
                    }
                }
            }
        }
    }

    /// Writes an empty dictionary into the metadata, to be filled through
    /// deeper paths.
    ///
    /// C: `otio_metadata_set_dictionary`
    public func setDictionary(_ path: String) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_set_dictionary(at.pointer, at.handle, cPath, &cError)
                try check(status, cError)
            }
        }
    }

    /// Writes a number into the metadata.
    ///
    /// C: `otio_metadata_set_double`
    public func setDouble(_ path: String, value: Double) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_set_double(at.pointer, at.handle, cPath, value, &cError)
                try check(status, cError)
            }
        }
    }

    /// Writes a signed integer into the metadata.
    ///
    /// C: `otio_metadata_set_int`
    public func setInt(_ path: String, value: Int64) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_set_int(at.pointer, at.handle, cPath, value, &cError)
                try check(status, cError)
            }
        }
    }

    /// Writes a nil into the metadata.
    ///
    /// C: `otio_metadata_set_null`
    public func setNull(_ path: String) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_set_null(at.pointer, at.handle, cPath, &cError)
                try check(status, cError)
            }
        }
    }

    /// Writes a handle to an OTIO object into the metadata.
    ///
    /// The object stays where it is and the metadata names it. Nothing checks
    /// that the handle is live, because a document being built may not hold the
    /// object yet.
    ///
    /// C: `otio_metadata_set_object`
    public func setObject(_ path: String, value: SerializableObject) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                let cValue = try adopt(at, value)
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_set_object(at.pointer, at.handle, cPath, cValue, &cError)
                try check(status, cError)
            }
        }
    }

    /// Writes a time into the metadata.
    ///
    /// C: `otio_metadata_set_rational_time`
    public func setRationalTime(_ path: String, value: RationalTime) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                return try value.withC { (cValue: OtioRationalTime) -> Void in
                    var cError = OtioBuffer()
                    defer { otio_buffer_free(cError) }
                    let status = otio_metadata_set_rational_time(at.pointer, at.handle, cPath, cValue, &cError)
                    try check(status, cError)
                }
            }
        }
    }

    /// Writes a string into the metadata.
    ///
    /// C: `otio_metadata_set_string`
    public func setString(_ path: String, value: String) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                return try value.withCString { (cValue: UnsafePointer<CChar>) -> Void in
                    var cError = OtioBuffer()
                    defer { otio_buffer_free(cError) }
                    let status = otio_metadata_set_string(at.pointer, at.handle, cPath, cValue, &cError)
                    try check(status, cError)
                }
            }
        }
    }

    /// Writes a span into the metadata.
    ///
    /// C: `otio_metadata_set_time_range`
    public func setTimeRange(_ path: String, value: TimeRange) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                return try value.withC { (cValue: OtioTimeRange) -> Void in
                    var cError = OtioBuffer()
                    defer { otio_buffer_free(cError) }
                    let status = otio_metadata_set_time_range(at.pointer, at.handle, cPath, cValue, &cError)
                    try check(status, cError)
                }
            }
        }
    }

    /// Writes a transform into the metadata.
    ///
    /// C: `otio_metadata_set_time_transform`
    public func setTimeTransform(_ path: String, value: TimeTransform) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                return try value.withC { (cValue: OtioTimeTransform) -> Void in
                    var cError = OtioBuffer()
                    defer { otio_buffer_free(cError) }
                    let status = otio_metadata_set_time_transform(at.pointer, at.handle, cPath, cValue, &cError)
                    try check(status, cError)
                }
            }
        }
    }

    /// Writes an unsigned integer into the metadata.
    ///
    /// C: `otio_metadata_set_uint`
    public func setUint(_ path: String, value: UInt64) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_set_uint(at.pointer, at.handle, cPath, value, &cError)
                try check(status, cError)
            }
        }
    }

    /// Writes a point into the metadata.
    ///
    /// C: `otio_metadata_set_v2d`
    public func setV2d(_ path: String, value: V2d) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                return try value.withC { (cValue: OtioV2d) -> Void in
                    var cError = OtioBuffer()
                    defer { otio_buffer_free(cError) }
                    let status = otio_metadata_set_v2d(at.pointer, at.handle, cPath, cValue, &cError)
                    try check(status, cError)
                }
            }
        }
    }

    /// Writes an array of `len` nulls into the metadata, to be filled by index.
    ///
    /// C: `otio_metadata_set_vector`
    public func setVector(_ path: String, len: Int) throws {
        let at = locate(self.object)
        return try withExtendedLifetime(at.arena) { () -> Void in
            return try path.withCString { (cPath: UnsafePointer<CChar>) -> Void in
                var cError = OtioBuffer()
                defer { otio_buffer_free(cError) }
                let status = otio_metadata_set_vector(at.pointer, at.handle, cPath, len, &cError)
                try check(status, cError)
            }
        }
    }
}
