// Code generated by otio-sdk-gen from crates/otio-capi. DO NOT EDIT.

import COtio

/// A `SerializableObjectWithMetadata`.
public class SerializableObjectWithMetadata: SerializableObject {}

/// A `Composable`.
public class Composable: SerializableObjectWithMetadata {}

/// A bare `Item`.
public class Item: Composable {}

/// A `Transition`.
public class Transition: Composable {}

/// A bare `Composition`.
public class Composition: Item {}

/// A `Track`.
public class Track: Composition {}

/// A `Stack`.
public class Stack: Composition {}

/// A `Clip`.
public class Clip: Item {}

/// A `Gap`.
public class Gap: Item {}

/// A `Timeline`.
public class Timeline: SerializableObjectWithMetadata {}

/// A `Marker`.
public class Marker: SerializableObjectWithMetadata {}

/// A `SerializableCollection`.
public class SerializableCollection: SerializableObjectWithMetadata {}

/// An `Effect`.
public class Effect: SerializableObjectWithMetadata {}

/// A `TimeEffect`.
public class TimeEffect: Effect {}

/// A `LinearTimeWarp`.
public class LinearTimeWarp: TimeEffect {}

/// A `FreezeFrame`.
public class FreezeFrame: LinearTimeWarp {}

/// A bare `MediaReference`.
public class MediaReference: SerializableObjectWithMetadata {}

/// An `ExternalReference`.
public class ExternalReference: MediaReference {}

/// A `MissingReference`.
public class MissingReference: MediaReference {}

/// A `GeneratorReference`.
public class GeneratorReference: MediaReference {}

/// An `ImageSequenceReference`.
public class ImageSequenceReference: MediaReference {}

/// An object whose schema this library does not know.
public class UnknownSchema: SerializableObject {}

/// A schema added to the core since this ABI was written.
///
/// Nothing produces this today. It exists so that a core that grows a new
/// object reports something honest to a caller built against this header
/// rather than a kind that means something else.
public class Other: SerializableObject {}

/// Which schema each one derives from, so that asking whether an object is an
/// `Item` can say yes for a clip.
internal let schemaParents: [NodeKind: NodeKind] = [
    .serializableObjectWithMetadata: .serializableObject,
    .composable: .serializableObjectWithMetadata,
    .item: .composable,
    .transition: .composable,
    .composition: .item,
    .track: .composition,
    .stack: .composition,
    .clip: .item,
    .gap: .item,
    .timeline: .serializableObjectWithMetadata,
    .marker: .serializableObjectWithMetadata,
    .serializableCollection: .serializableObjectWithMetadata,
    .effect: .serializableObjectWithMetadata,
    .timeEffect: .effect,
    .linearTimeWarp: .timeEffect,
    .freezeFrame: .linearTimeWarp,
    .mediaReference: .serializableObjectWithMetadata,
    .externalReference: .mediaReference,
    .missingReference: .mediaReference,
    .generatorReference: .mediaReference,
    .imageSequenceReference: .mediaReference,
    .unknownSchema: .serializableObject,
    .other: .serializableObject,
]

extension SerializableObject {
    /// Whether the object is of a schema, or of one deriving from it.
    ///
    /// An object whose document has gone, or whose handle no longer resolves,
    /// is of no schema at all, so this answers false rather than guessing.
    public func isA(_ schema: NodeKind) -> Bool {
        guard var kind = try? schemaKind() else { return false }
        while true {
            if kind == schema { return true }
            guard let parent = schemaParents[kind] else { return false }
            kind = parent
        }
    }
}

/// Builds the class an object's schema names.
///
/// Every handle that comes back from the library goes through this, so a
/// downcast tells the truth: `node as? Clip` succeeds exactly when the object
/// really is a clip. An object whose kind cannot be read — a handle that no
/// longer resolves, or one belonging to no document — comes back as a plain
/// `SerializableObject` rather than as a guess.
internal func makeObject(_ document: Document?, _ handle: OtioNode) -> SerializableObject {
    guard let document, document.pointer != nil else {
        return SerializableObject(document: document, handle: handle)
    }
    var outKind = cEnum(0, OtioNodeKind.self)
    guard isOK(otio_node_kind(document.pointer, handle, &outKind)) else {
        return SerializableObject(document: document, handle: handle)
    }
    switch enumValue(outKind, NodeKind.self) {
    case .serializableObject: return SerializableObject(document: document, handle: handle)
    case .serializableObjectWithMetadata: return SerializableObjectWithMetadata(document: document, handle: handle)
    case .composable: return Composable(document: document, handle: handle)
    case .item: return Item(document: document, handle: handle)
    case .transition: return Transition(document: document, handle: handle)
    case .composition: return Composition(document: document, handle: handle)
    case .track: return Track(document: document, handle: handle)
    case .stack: return Stack(document: document, handle: handle)
    case .clip: return Clip(document: document, handle: handle)
    case .gap: return Gap(document: document, handle: handle)
    case .timeline: return Timeline(document: document, handle: handle)
    case .marker: return Marker(document: document, handle: handle)
    case .serializableCollection: return SerializableCollection(document: document, handle: handle)
    case .effect: return Effect(document: document, handle: handle)
    case .timeEffect: return TimeEffect(document: document, handle: handle)
    case .linearTimeWarp: return LinearTimeWarp(document: document, handle: handle)
    case .freezeFrame: return FreezeFrame(document: document, handle: handle)
    case .mediaReference: return MediaReference(document: document, handle: handle)
    case .externalReference: return ExternalReference(document: document, handle: handle)
    case .missingReference: return MissingReference(document: document, handle: handle)
    case .generatorReference: return GeneratorReference(document: document, handle: handle)
    case .imageSequenceReference: return ImageSequenceReference(document: document, handle: handle)
    case .unknownSchema: return UnknownSchema(document: document, handle: handle)
    case .other: return Other(document: document, handle: handle)
    }
}
